// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"polar/models/components"
)

type CheckoutLinksGetRequest struct {
	// The checkout link ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *CheckoutLinksGetRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type CheckoutLinksGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	CheckoutLink *components.CheckoutLink
}

func (o *CheckoutLinksGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CheckoutLinksGetResponse) GetCheckoutLink() *components.CheckoutLink {
	if o == nil {
		return nil
	}
	return o.CheckoutLink
}
