// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/polarsource/polar-go/models/components"
)

type CustomerPortalOrganizationsGetRequest struct {
	// The organization slug.
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (c *CustomerPortalOrganizationsGetRequest) GetSlug() string {
	if c == nil {
		return ""
	}
	return c.Slug
}

type CustomerPortalOrganizationsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	CustomerOrganizationData *components.CustomerOrganizationData
}

func (c *CustomerPortalOrganizationsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CustomerPortalOrganizationsGetResponse) GetCustomerOrganizationData() *components.CustomerOrganizationData {
	if c == nil {
		return nil
	}
	return c.CustomerOrganizationData
}
