// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/polarsource/polar-go/models/components"
)

type CustomerPortalOrdersGetPaymentStatusSecurity struct {
	CustomerSession string `security:"scheme,type=http,subtype=bearer,name=Authorization,env=polar_customer_session"`
}

func (o *CustomerPortalOrdersGetPaymentStatusSecurity) GetCustomerSession() string {
	if o == nil {
		return ""
	}
	return o.CustomerSession
}

type CustomerPortalOrdersGetPaymentStatusRequest struct {
	// The order ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *CustomerPortalOrdersGetPaymentStatusRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type CustomerPortalOrdersGetPaymentStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	CustomerOrderPaymentStatus *components.CustomerOrderPaymentStatus
}

func (o *CustomerPortalOrdersGetPaymentStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CustomerPortalOrdersGetPaymentStatusResponse) GetCustomerOrderPaymentStatus() *components.CustomerOrderPaymentStatus {
	if o == nil {
		return nil
	}
	return o.CustomerOrderPaymentStatus
}
