// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/polarsource/polar-go/models/components"
)

type CustomerPortalCustomersUpdateSecurity struct {
	CustomerSession string `security:"scheme,type=http,subtype=bearer,name=Authorization,env=polar_customer_session"`
}

func (o *CustomerPortalCustomersUpdateSecurity) GetCustomerSession() string {
	if o == nil {
		return ""
	}
	return o.CustomerSession
}

type CustomerPortalCustomersUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Customer updated.
	CustomerPortalCustomer *components.CustomerPortalCustomer
}

func (o *CustomerPortalCustomersUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CustomerPortalCustomersUpdateResponse) GetCustomerPortalCustomer() *components.CustomerPortalCustomer {
	if o == nil {
		return nil
	}
	return o.CustomerPortalCustomer
}
