// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
	"github.com/polarsource/polar-go/models/components"
)

type CustomerPortalCustomerMetersListSecurity struct {
	CustomerSession *string `security:"scheme,type=http,subtype=bearer,name=Authorization,env=polar_customer_session"`
	MemberSession   *string `security:"scheme,type=http,subtype=bearer,name=Authorization,env=polar_member_session"`
}

func (c *CustomerPortalCustomerMetersListSecurity) GetCustomerSession() *string {
	if c == nil {
		return nil
	}
	return c.CustomerSession
}

func (c *CustomerPortalCustomerMetersListSecurity) GetMemberSession() *string {
	if c == nil {
		return nil
	}
	return c.MemberSession
}

type MeterIDFilterType string

const (
	MeterIDFilterTypeStr        MeterIDFilterType = "str"
	MeterIDFilterTypeArrayOfStr MeterIDFilterType = "arrayOfStr"
)

// MeterIDFilter - Filter by meter ID.
type MeterIDFilter struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type MeterIDFilterType
}

func CreateMeterIDFilterStr(str string) MeterIDFilter {
	typ := MeterIDFilterTypeStr

	return MeterIDFilter{
		Str:  &str,
		Type: typ,
	}
}

func CreateMeterIDFilterArrayOfStr(arrayOfStr []string) MeterIDFilter {
	typ := MeterIDFilterTypeArrayOfStr

	return MeterIDFilter{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *MeterIDFilter) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = MeterIDFilterTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = MeterIDFilterTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for MeterIDFilter", string(data))
}

func (u MeterIDFilter) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type MeterIDFilter: all fields are null")
}

type CustomerPortalCustomerMetersListRequest struct {
	// Filter by meter ID.
	MeterID *MeterIDFilter `queryParam:"style=form,explode=true,name=meter_id"`
	// Filter by meter name.
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Page number, defaults to 1.
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Size of a page, defaults to 10. Maximum is 100.
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	Sorting []components.CustomerCustomerMeterSortProperty `queryParam:"style=form,explode=true,name=sorting"`
}

func (c CustomerPortalCustomerMetersListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomerPortalCustomerMetersListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomerPortalCustomerMetersListRequest) GetMeterID() *MeterIDFilter {
	if c == nil {
		return nil
	}
	return c.MeterID
}

func (c *CustomerPortalCustomerMetersListRequest) GetQuery() *string {
	if c == nil {
		return nil
	}
	return c.Query
}

func (c *CustomerPortalCustomerMetersListRequest) GetPage() *int64 {
	if c == nil {
		return nil
	}
	return c.Page
}

func (c *CustomerPortalCustomerMetersListRequest) GetLimit() *int64 {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *CustomerPortalCustomerMetersListRequest) GetSorting() []components.CustomerCustomerMeterSortProperty {
	if c == nil {
		return nil
	}
	return c.Sorting
}

type CustomerPortalCustomerMetersListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ListResourceCustomerCustomerMeter *components.ListResourceCustomerCustomerMeter

	Next func() (*CustomerPortalCustomerMetersListResponse, error)
}

func (c *CustomerPortalCustomerMetersListResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CustomerPortalCustomerMetersListResponse) GetListResourceCustomerCustomerMeter() *components.ListResourceCustomerCustomerMeter {
	if c == nil {
		return nil
	}
	return c.ListResourceCustomerCustomerMeter
}
