// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"polar/models/components"
)

type CustomerPortalDownloadablesCustomerPortalDownloadablesGetRequest struct {
	Token string `pathParam:"style=simple,explode=false,name=token"`
}

func (o *CustomerPortalDownloadablesCustomerPortalDownloadablesGetRequest) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

type CustomerPortalDownloadablesCustomerPortalDownloadablesGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	Any any
}

func (o *CustomerPortalDownloadablesCustomerPortalDownloadablesGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CustomerPortalDownloadablesCustomerPortalDownloadablesGetResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}
