// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"polar/models/components"
)

type DiscountsCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Discount created.
	Discount *components.Discount
}

func (o *DiscountsCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DiscountsCreateResponse) GetDiscount() *components.Discount {
	if o == nil {
		return nil
	}
	return o.Discount
}
