// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/polarsource/polar-go/models/components"
)

type MembersCreateMemberResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Member created.
	Member *components.Member
}

func (m *MembersCreateMemberResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MembersCreateMemberResponse) GetMember() *components.Member {
	if m == nil {
		return nil
	}
	return m.Member
}
