// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/polarsource/polar-go/models/components"
)

type OrdersReceiptRequest struct {
	// The order ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *OrdersReceiptRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type OrdersReceiptResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	OrderReceipt *components.OrderReceipt
}

func (o *OrdersReceiptResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrdersReceiptResponse) GetOrderReceipt() *components.OrderReceipt {
	if o == nil {
		return nil
	}
	return o.OrderReceipt
}
