// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
	"github.com/polarsource/polar-go/models/components"
)

type RefundIDFilterType string

const (
	RefundIDFilterTypeStr        RefundIDFilterType = "str"
	RefundIDFilterTypeArrayOfStr RefundIDFilterType = "arrayOfStr"
)

// RefundIDFilter - Filter by refund ID.
type RefundIDFilter struct {
	Str        *string  `queryParam:"inline"`
	ArrayOfStr []string `queryParam:"inline"`

	Type RefundIDFilterType
}

func CreateRefundIDFilterStr(str string) RefundIDFilter {
	typ := RefundIDFilterTypeStr

	return RefundIDFilter{
		Str:  &str,
		Type: typ,
	}
}

func CreateRefundIDFilterArrayOfStr(arrayOfStr []string) RefundIDFilter {
	typ := RefundIDFilterTypeArrayOfStr

	return RefundIDFilter{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *RefundIDFilter) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, false); err == nil {
		u.Str = &str
		u.Type = RefundIDFilterTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, false); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = RefundIDFilterTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RefundIDFilter", string(data))
}

func (u RefundIDFilter) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type RefundIDFilter: all fields are null")
}

type RefundsListQueryParamOrganizationIDFilterType string

const (
	RefundsListQueryParamOrganizationIDFilterTypeStr        RefundsListQueryParamOrganizationIDFilterType = "str"
	RefundsListQueryParamOrganizationIDFilterTypeArrayOfStr RefundsListQueryParamOrganizationIDFilterType = "arrayOfStr"
)

// RefundsListQueryParamOrganizationIDFilter - Filter by organization ID.
type RefundsListQueryParamOrganizationIDFilter struct {
	Str        *string  `queryParam:"inline"`
	ArrayOfStr []string `queryParam:"inline"`

	Type RefundsListQueryParamOrganizationIDFilterType
}

func CreateRefundsListQueryParamOrganizationIDFilterStr(str string) RefundsListQueryParamOrganizationIDFilter {
	typ := RefundsListQueryParamOrganizationIDFilterTypeStr

	return RefundsListQueryParamOrganizationIDFilter{
		Str:  &str,
		Type: typ,
	}
}

func CreateRefundsListQueryParamOrganizationIDFilterArrayOfStr(arrayOfStr []string) RefundsListQueryParamOrganizationIDFilter {
	typ := RefundsListQueryParamOrganizationIDFilterTypeArrayOfStr

	return RefundsListQueryParamOrganizationIDFilter{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *RefundsListQueryParamOrganizationIDFilter) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, false); err == nil {
		u.Str = &str
		u.Type = RefundsListQueryParamOrganizationIDFilterTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, false); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = RefundsListQueryParamOrganizationIDFilterTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RefundsListQueryParamOrganizationIDFilter", string(data))
}

func (u RefundsListQueryParamOrganizationIDFilter) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type RefundsListQueryParamOrganizationIDFilter: all fields are null")
}

type OrderIDFilterType string

const (
	OrderIDFilterTypeStr        OrderIDFilterType = "str"
	OrderIDFilterTypeArrayOfStr OrderIDFilterType = "arrayOfStr"
)

// OrderIDFilter - Filter by order ID.
type OrderIDFilter struct {
	Str        *string  `queryParam:"inline"`
	ArrayOfStr []string `queryParam:"inline"`

	Type OrderIDFilterType
}

func CreateOrderIDFilterStr(str string) OrderIDFilter {
	typ := OrderIDFilterTypeStr

	return OrderIDFilter{
		Str:  &str,
		Type: typ,
	}
}

func CreateOrderIDFilterArrayOfStr(arrayOfStr []string) OrderIDFilter {
	typ := OrderIDFilterTypeArrayOfStr

	return OrderIDFilter{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *OrderIDFilter) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, false); err == nil {
		u.Str = &str
		u.Type = OrderIDFilterTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, false); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = OrderIDFilterTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for OrderIDFilter", string(data))
}

func (u OrderIDFilter) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type OrderIDFilter: all fields are null")
}

type SubscriptionIDFilterType string

const (
	SubscriptionIDFilterTypeStr        SubscriptionIDFilterType = "str"
	SubscriptionIDFilterTypeArrayOfStr SubscriptionIDFilterType = "arrayOfStr"
)

// SubscriptionIDFilter - Filter by subscription ID.
type SubscriptionIDFilter struct {
	Str        *string  `queryParam:"inline"`
	ArrayOfStr []string `queryParam:"inline"`

	Type SubscriptionIDFilterType
}

func CreateSubscriptionIDFilterStr(str string) SubscriptionIDFilter {
	typ := SubscriptionIDFilterTypeStr

	return SubscriptionIDFilter{
		Str:  &str,
		Type: typ,
	}
}

func CreateSubscriptionIDFilterArrayOfStr(arrayOfStr []string) SubscriptionIDFilter {
	typ := SubscriptionIDFilterTypeArrayOfStr

	return SubscriptionIDFilter{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *SubscriptionIDFilter) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, false); err == nil {
		u.Str = &str
		u.Type = SubscriptionIDFilterTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, false); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = SubscriptionIDFilterTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SubscriptionIDFilter", string(data))
}

func (u SubscriptionIDFilter) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type SubscriptionIDFilter: all fields are null")
}

type RefundsListQueryParamCustomerIDFilterType string

const (
	RefundsListQueryParamCustomerIDFilterTypeStr        RefundsListQueryParamCustomerIDFilterType = "str"
	RefundsListQueryParamCustomerIDFilterTypeArrayOfStr RefundsListQueryParamCustomerIDFilterType = "arrayOfStr"
)

// RefundsListQueryParamCustomerIDFilter - Filter by customer ID.
type RefundsListQueryParamCustomerIDFilter struct {
	Str        *string  `queryParam:"inline"`
	ArrayOfStr []string `queryParam:"inline"`

	Type RefundsListQueryParamCustomerIDFilterType
}

func CreateRefundsListQueryParamCustomerIDFilterStr(str string) RefundsListQueryParamCustomerIDFilter {
	typ := RefundsListQueryParamCustomerIDFilterTypeStr

	return RefundsListQueryParamCustomerIDFilter{
		Str:  &str,
		Type: typ,
	}
}

func CreateRefundsListQueryParamCustomerIDFilterArrayOfStr(arrayOfStr []string) RefundsListQueryParamCustomerIDFilter {
	typ := RefundsListQueryParamCustomerIDFilterTypeArrayOfStr

	return RefundsListQueryParamCustomerIDFilter{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *RefundsListQueryParamCustomerIDFilter) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, false); err == nil {
		u.Str = &str
		u.Type = RefundsListQueryParamCustomerIDFilterTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, false); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = RefundsListQueryParamCustomerIDFilterTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RefundsListQueryParamCustomerIDFilter", string(data))
}

func (u RefundsListQueryParamCustomerIDFilter) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type RefundsListQueryParamCustomerIDFilter: all fields are null")
}

type RefundsListRequest struct {
	// Filter by refund ID.
	ID *RefundIDFilter `queryParam:"style=form,explode=true,name=id"`
	// Filter by organization ID.
	OrganizationID *RefundsListQueryParamOrganizationIDFilter `queryParam:"style=form,explode=true,name=organization_id"`
	// Filter by order ID.
	OrderID *OrderIDFilter `queryParam:"style=form,explode=true,name=order_id"`
	// Filter by subscription ID.
	SubscriptionID *SubscriptionIDFilter `queryParam:"style=form,explode=true,name=subscription_id"`
	// Filter by customer ID.
	CustomerID *RefundsListQueryParamCustomerIDFilter `queryParam:"style=form,explode=true,name=customer_id"`
	// Filter by `succeeded`.
	Succeeded *bool `queryParam:"style=form,explode=true,name=succeeded"`
	// Page number, defaults to 1.
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Size of a page, defaults to 10. Maximum is 100.
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	Sorting []components.RefundSortProperty `queryParam:"style=form,explode=true,name=sorting"`
}

func (r RefundsListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RefundsListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *RefundsListRequest) GetID() *RefundIDFilter {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *RefundsListRequest) GetOrganizationID() *RefundsListQueryParamOrganizationIDFilter {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

func (o *RefundsListRequest) GetOrderID() *OrderIDFilter {
	if o == nil {
		return nil
	}
	return o.OrderID
}

func (o *RefundsListRequest) GetSubscriptionID() *SubscriptionIDFilter {
	if o == nil {
		return nil
	}
	return o.SubscriptionID
}

func (o *RefundsListRequest) GetCustomerID() *RefundsListQueryParamCustomerIDFilter {
	if o == nil {
		return nil
	}
	return o.CustomerID
}

func (o *RefundsListRequest) GetSucceeded() *bool {
	if o == nil {
		return nil
	}
	return o.Succeeded
}

func (o *RefundsListRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *RefundsListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *RefundsListRequest) GetSorting() []components.RefundSortProperty {
	if o == nil {
		return nil
	}
	return o.Sorting
}

type RefundsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ListResourceRefund *components.ListResourceRefund

	Next func() (*RefundsListResponse, error)
}

func (o *RefundsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RefundsListResponse) GetListResourceRefund() *components.ListResourceRefund {
	if o == nil {
		return nil
	}
	return o.ListResourceRefund
}
