// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
)

type AuthorizationCodeTokenRequest struct {
	grantType    string `const:"authorization_code" form:"name=grant_type"`
	ClientID     string `form:"name=client_id"`
	ClientSecret string `form:"name=client_secret"`
	Code         string `form:"name=code"`
	RedirectURI  string `form:"name=redirect_uri"`
}

func (a AuthorizationCodeTokenRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthorizationCodeTokenRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"grant_type", "client_id", "client_secret", "code", "redirect_uri"}); err != nil {
		return err
	}
	return nil
}

func (o *AuthorizationCodeTokenRequest) GetGrantType() string {
	return "authorization_code"
}

func (o *AuthorizationCodeTokenRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *AuthorizationCodeTokenRequest) GetClientSecret() string {
	if o == nil {
		return ""
	}
	return o.ClientSecret
}

func (o *AuthorizationCodeTokenRequest) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *AuthorizationCodeTokenRequest) GetRedirectURI() string {
	if o == nil {
		return ""
	}
	return o.RedirectURI
}
