// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

// BalanceRefundEvent - An event created by Polar when an order is refunded.
type BalanceRefundEvent struct {
	// The ID of the object.
	ID string `json:"id"`
	// The timestamp of the event.
	Timestamp time.Time `json:"timestamp"`
	// The ID of the organization owning the event.
	OrganizationID string `json:"organization_id"`
	// ID of the customer in your Polar organization associated with the event.
	CustomerID *string `json:"customer_id"`
	// The customer associated with the event.
	Customer *Customer `json:"customer"`
	// ID of the customer in your system associated with the event.
	ExternalCustomerID *string `json:"external_customer_id"`
	// ID of the member within the customer's organization who performed the action inside B2B.
	MemberID *string `json:"member_id,omitempty"`
	// ID of the member in your system within the customer's organization who performed the action inside B2B.
	ExternalMemberID *string `json:"external_member_id,omitempty"`
	// Number of direct child events linked to this event.
	ChildCount *int64 `default:"0" json:"child_count"`
	// The ID of the parent event.
	ParentID *string `json:"parent_id,omitempty"`
	// Human readable label of the event type.
	Label string `json:"label"`
	// The source of the event. `system` events are created by Polar. `user` events are the one you create through our ingestion API.
	source string `const:"system" json:"source"`
	// The name of the event.
	name     string                `const:"balance.refund" json:"name"`
	Metadata BalanceRefundMetadata `json:"metadata"`
}

func (b BalanceRefundEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BalanceRefundEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"id", "timestamp", "organization_id", "label", "source", "name", "metadata"}); err != nil {
		return err
	}
	return nil
}

func (b *BalanceRefundEvent) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BalanceRefundEvent) GetTimestamp() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.Timestamp
}

func (b *BalanceRefundEvent) GetOrganizationID() string {
	if b == nil {
		return ""
	}
	return b.OrganizationID
}

func (b *BalanceRefundEvent) GetCustomerID() *string {
	if b == nil {
		return nil
	}
	return b.CustomerID
}

func (b *BalanceRefundEvent) GetCustomer() *Customer {
	if b == nil {
		return nil
	}
	return b.Customer
}

func (b *BalanceRefundEvent) GetExternalCustomerID() *string {
	if b == nil {
		return nil
	}
	return b.ExternalCustomerID
}

func (b *BalanceRefundEvent) GetMemberID() *string {
	if b == nil {
		return nil
	}
	return b.MemberID
}

func (b *BalanceRefundEvent) GetExternalMemberID() *string {
	if b == nil {
		return nil
	}
	return b.ExternalMemberID
}

func (b *BalanceRefundEvent) GetChildCount() *int64 {
	if b == nil {
		return nil
	}
	return b.ChildCount
}

func (b *BalanceRefundEvent) GetParentID() *string {
	if b == nil {
		return nil
	}
	return b.ParentID
}

func (b *BalanceRefundEvent) GetLabel() string {
	if b == nil {
		return ""
	}
	return b.Label
}

func (b *BalanceRefundEvent) GetSource() string {
	return "system"
}

func (b *BalanceRefundEvent) GetName() string {
	return "balance.refund"
}

func (b *BalanceRefundEvent) GetMetadata() BalanceRefundMetadata {
	if b == nil {
		return BalanceRefundMetadata{}
	}
	return b.Metadata
}
