// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
)

type BenefitAdsUpdate struct {
	// The description of the benefit. Will be displayed on products having this benefit.
	Description *string               `json:"description,omitempty"`
	type_       string                `const:"ads" json:"type"`
	Properties  *BenefitAdsProperties `json:"properties,omitempty"`
}

func (b BenefitAdsUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BenefitAdsUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *BenefitAdsUpdate) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *BenefitAdsUpdate) GetType() string {
	return "ads"
}

func (o *BenefitAdsUpdate) GetProperties() *BenefitAdsProperties {
	if o == nil {
		return nil
	}
	return o.Properties
}
