// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type BenefitFeatureFlagSubscriber struct {
	// The ID of the benefit.
	ID string `json:"id"`
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	type_      string     `const:"feature_flag" json:"type"`
	// The description of the benefit.
	Description string `json:"description"`
	// Whether the benefit is selectable when creating a product.
	Selectable bool `json:"selectable"`
	// Whether the benefit is deletable.
	Deletable bool `json:"deletable"`
	// The ID of the organization owning the benefit.
	OrganizationID string                        `json:"organization_id"`
	Metadata       map[string]MetadataOutputType `json:"metadata"`
	Organization   BenefitSubscriberOrganization `json:"organization"`
	// Properties available to subscribers for a benefit of type `feature_flag`.
	Properties BenefitFeatureFlagSubscriberProperties `json:"properties"`
}

func (b BenefitFeatureFlagSubscriber) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BenefitFeatureFlagSubscriber) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"id", "created_at", "type", "description", "selectable", "deletable", "organization_id", "metadata", "organization", "properties"}); err != nil {
		return err
	}
	return nil
}

func (b *BenefitFeatureFlagSubscriber) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BenefitFeatureFlagSubscriber) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}

func (b *BenefitFeatureFlagSubscriber) GetModifiedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.ModifiedAt
}

func (b *BenefitFeatureFlagSubscriber) GetType() string {
	return "feature_flag"
}

func (b *BenefitFeatureFlagSubscriber) GetDescription() string {
	if b == nil {
		return ""
	}
	return b.Description
}

func (b *BenefitFeatureFlagSubscriber) GetSelectable() bool {
	if b == nil {
		return false
	}
	return b.Selectable
}

func (b *BenefitFeatureFlagSubscriber) GetDeletable() bool {
	if b == nil {
		return false
	}
	return b.Deletable
}

func (b *BenefitFeatureFlagSubscriber) GetOrganizationID() string {
	if b == nil {
		return ""
	}
	return b.OrganizationID
}

func (b *BenefitFeatureFlagSubscriber) GetMetadata() map[string]MetadataOutputType {
	if b == nil {
		return map[string]MetadataOutputType{}
	}
	return b.Metadata
}

func (b *BenefitFeatureFlagSubscriber) GetOrganization() BenefitSubscriberOrganization {
	if b == nil {
		return BenefitSubscriberOrganization{}
	}
	return b.Organization
}

func (b *BenefitFeatureFlagSubscriber) GetProperties() BenefitFeatureFlagSubscriberProperties {
	if b == nil {
		return BenefitFeatureFlagSubscriberProperties{}
	}
	return b.Properties
}
