// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type PropertiesType string

const (
	PropertiesTypeBenefitGrantDiscordProperties          PropertiesType = "BenefitGrantDiscordProperties"
	PropertiesTypeBenefitGrantGitHubRepositoryProperties PropertiesType = "BenefitGrantGitHubRepositoryProperties"
	PropertiesTypeBenefitGrantDownloadablesProperties    PropertiesType = "BenefitGrantDownloadablesProperties"
	PropertiesTypeBenefitGrantLicenseKeysProperties      PropertiesType = "BenefitGrantLicenseKeysProperties"
	PropertiesTypeBenefitGrantCustomProperties           PropertiesType = "BenefitGrantCustomProperties"
	PropertiesTypeBenefitGrantFeatureFlagProperties      PropertiesType = "BenefitGrantFeatureFlagProperties"
)

type Properties struct {
	BenefitGrantDiscordProperties          *BenefitGrantDiscordProperties          `queryParam:"inline" union:"member"`
	BenefitGrantGitHubRepositoryProperties *BenefitGrantGitHubRepositoryProperties `queryParam:"inline" union:"member"`
	BenefitGrantDownloadablesProperties    *BenefitGrantDownloadablesProperties    `queryParam:"inline" union:"member"`
	BenefitGrantLicenseKeysProperties      *BenefitGrantLicenseKeysProperties      `queryParam:"inline" union:"member"`
	BenefitGrantCustomProperties           *BenefitGrantCustomProperties           `queryParam:"inline" union:"member"`
	BenefitGrantFeatureFlagProperties      *BenefitGrantFeatureFlagProperties      `queryParam:"inline" union:"member"`

	Type PropertiesType
}

func CreatePropertiesBenefitGrantDiscordProperties(benefitGrantDiscordProperties BenefitGrantDiscordProperties) Properties {
	typ := PropertiesTypeBenefitGrantDiscordProperties

	return Properties{
		BenefitGrantDiscordProperties: &benefitGrantDiscordProperties,
		Type:                          typ,
	}
}

func CreatePropertiesBenefitGrantGitHubRepositoryProperties(benefitGrantGitHubRepositoryProperties BenefitGrantGitHubRepositoryProperties) Properties {
	typ := PropertiesTypeBenefitGrantGitHubRepositoryProperties

	return Properties{
		BenefitGrantGitHubRepositoryProperties: &benefitGrantGitHubRepositoryProperties,
		Type:                                   typ,
	}
}

func CreatePropertiesBenefitGrantDownloadablesProperties(benefitGrantDownloadablesProperties BenefitGrantDownloadablesProperties) Properties {
	typ := PropertiesTypeBenefitGrantDownloadablesProperties

	return Properties{
		BenefitGrantDownloadablesProperties: &benefitGrantDownloadablesProperties,
		Type:                                typ,
	}
}

func CreatePropertiesBenefitGrantLicenseKeysProperties(benefitGrantLicenseKeysProperties BenefitGrantLicenseKeysProperties) Properties {
	typ := PropertiesTypeBenefitGrantLicenseKeysProperties

	return Properties{
		BenefitGrantLicenseKeysProperties: &benefitGrantLicenseKeysProperties,
		Type:                              typ,
	}
}

func CreatePropertiesBenefitGrantCustomProperties(benefitGrantCustomProperties BenefitGrantCustomProperties) Properties {
	typ := PropertiesTypeBenefitGrantCustomProperties

	return Properties{
		BenefitGrantCustomProperties: &benefitGrantCustomProperties,
		Type:                         typ,
	}
}

func CreatePropertiesBenefitGrantFeatureFlagProperties(benefitGrantFeatureFlagProperties BenefitGrantFeatureFlagProperties) Properties {
	typ := PropertiesTypeBenefitGrantFeatureFlagProperties

	return Properties{
		BenefitGrantFeatureFlagProperties: &benefitGrantFeatureFlagProperties,
		Type:                              typ,
	}
}

func (u *Properties) UnmarshalJSON(data []byte) error {

	var benefitGrantDiscordProperties BenefitGrantDiscordProperties = BenefitGrantDiscordProperties{}
	if err := utils.UnmarshalJSON(data, &benefitGrantDiscordProperties, "", true, nil); err == nil {
		u.BenefitGrantDiscordProperties = &benefitGrantDiscordProperties
		u.Type = PropertiesTypeBenefitGrantDiscordProperties
		return nil
	}

	var benefitGrantGitHubRepositoryProperties BenefitGrantGitHubRepositoryProperties = BenefitGrantGitHubRepositoryProperties{}
	if err := utils.UnmarshalJSON(data, &benefitGrantGitHubRepositoryProperties, "", true, nil); err == nil {
		u.BenefitGrantGitHubRepositoryProperties = &benefitGrantGitHubRepositoryProperties
		u.Type = PropertiesTypeBenefitGrantGitHubRepositoryProperties
		return nil
	}

	var benefitGrantDownloadablesProperties BenefitGrantDownloadablesProperties = BenefitGrantDownloadablesProperties{}
	if err := utils.UnmarshalJSON(data, &benefitGrantDownloadablesProperties, "", true, nil); err == nil {
		u.BenefitGrantDownloadablesProperties = &benefitGrantDownloadablesProperties
		u.Type = PropertiesTypeBenefitGrantDownloadablesProperties
		return nil
	}

	var benefitGrantLicenseKeysProperties BenefitGrantLicenseKeysProperties = BenefitGrantLicenseKeysProperties{}
	if err := utils.UnmarshalJSON(data, &benefitGrantLicenseKeysProperties, "", true, nil); err == nil {
		u.BenefitGrantLicenseKeysProperties = &benefitGrantLicenseKeysProperties
		u.Type = PropertiesTypeBenefitGrantLicenseKeysProperties
		return nil
	}

	var benefitGrantCustomProperties BenefitGrantCustomProperties = BenefitGrantCustomProperties{}
	if err := utils.UnmarshalJSON(data, &benefitGrantCustomProperties, "", true, nil); err == nil {
		u.BenefitGrantCustomProperties = &benefitGrantCustomProperties
		u.Type = PropertiesTypeBenefitGrantCustomProperties
		return nil
	}

	var benefitGrantFeatureFlagProperties BenefitGrantFeatureFlagProperties = BenefitGrantFeatureFlagProperties{}
	if err := utils.UnmarshalJSON(data, &benefitGrantFeatureFlagProperties, "", true, nil); err == nil {
		u.BenefitGrantFeatureFlagProperties = &benefitGrantFeatureFlagProperties
		u.Type = PropertiesTypeBenefitGrantFeatureFlagProperties
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Properties", string(data))
}

func (u Properties) MarshalJSON() ([]byte, error) {
	if u.BenefitGrantDiscordProperties != nil {
		return utils.MarshalJSON(u.BenefitGrantDiscordProperties, "", true)
	}

	if u.BenefitGrantGitHubRepositoryProperties != nil {
		return utils.MarshalJSON(u.BenefitGrantGitHubRepositoryProperties, "", true)
	}

	if u.BenefitGrantDownloadablesProperties != nil {
		return utils.MarshalJSON(u.BenefitGrantDownloadablesProperties, "", true)
	}

	if u.BenefitGrantLicenseKeysProperties != nil {
		return utils.MarshalJSON(u.BenefitGrantLicenseKeysProperties, "", true)
	}

	if u.BenefitGrantCustomProperties != nil {
		return utils.MarshalJSON(u.BenefitGrantCustomProperties, "", true)
	}

	if u.BenefitGrantFeatureFlagProperties != nil {
		return utils.MarshalJSON(u.BenefitGrantFeatureFlagProperties, "", true)
	}

	return nil, errors.New("could not marshal union type Properties: all fields are null")
}

type BenefitGrant struct {
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the grant.
	ID string `json:"id"`
	// The timestamp when the benefit was granted. If `None`, the benefit is not granted.
	GrantedAt *time.Time `json:"granted_at,omitempty"`
	// Whether the benefit is granted.
	IsGranted bool `json:"is_granted"`
	// The timestamp when the benefit was revoked. If `None`, the benefit is not revoked.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// Whether the benefit is revoked.
	IsRevoked bool `json:"is_revoked"`
	// The ID of the subscription that granted this benefit.
	SubscriptionID *string `json:"subscription_id"`
	// The ID of the order that granted this benefit.
	OrderID *string `json:"order_id"`
	// The ID of the customer concerned by this grant.
	CustomerID string `json:"customer_id"`
	// The ID of the member concerned by this grant.
	MemberID *string `json:"member_id,omitempty"`
	// The ID of the benefit concerned by this grant.
	BenefitID string `json:"benefit_id"`
	// The error information if the benefit grant failed with an unrecoverable error.
	Error *BenefitGrantError `json:"error,omitempty"`
	// A customer in an organization.
	Customer   Customer   `json:"customer"`
	Member     *Member    `json:"member,omitempty"`
	Benefit    Benefit    `json:"benefit"`
	Properties Properties `json:"properties"`
}

func (b BenefitGrant) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BenefitGrant) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BenefitGrant) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}

func (b *BenefitGrant) GetModifiedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.ModifiedAt
}

func (b *BenefitGrant) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BenefitGrant) GetGrantedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.GrantedAt
}

func (b *BenefitGrant) GetIsGranted() bool {
	if b == nil {
		return false
	}
	return b.IsGranted
}

func (b *BenefitGrant) GetRevokedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.RevokedAt
}

func (b *BenefitGrant) GetIsRevoked() bool {
	if b == nil {
		return false
	}
	return b.IsRevoked
}

func (b *BenefitGrant) GetSubscriptionID() *string {
	if b == nil {
		return nil
	}
	return b.SubscriptionID
}

func (b *BenefitGrant) GetOrderID() *string {
	if b == nil {
		return nil
	}
	return b.OrderID
}

func (b *BenefitGrant) GetCustomerID() string {
	if b == nil {
		return ""
	}
	return b.CustomerID
}

func (b *BenefitGrant) GetMemberID() *string {
	if b == nil {
		return nil
	}
	return b.MemberID
}

func (b *BenefitGrant) GetBenefitID() string {
	if b == nil {
		return ""
	}
	return b.BenefitID
}

func (b *BenefitGrant) GetError() *BenefitGrantError {
	if b == nil {
		return nil
	}
	return b.Error
}

func (b *BenefitGrant) GetCustomer() Customer {
	if b == nil {
		return Customer{}
	}
	return b.Customer
}

func (b *BenefitGrant) GetMember() *Member {
	if b == nil {
		return nil
	}
	return b.Member
}

func (b *BenefitGrant) GetBenefit() Benefit {
	if b == nil {
		return Benefit{}
	}
	return b.Benefit
}

func (b *BenefitGrant) GetBenefitCustom() *BenefitCustom {
	return b.GetBenefit().BenefitCustom
}

func (b *BenefitGrant) GetBenefitDiscord() *BenefitDiscord {
	return b.GetBenefit().BenefitDiscord
}

func (b *BenefitGrant) GetBenefitDownloadables() *BenefitDownloadables {
	return b.GetBenefit().BenefitDownloadables
}

func (b *BenefitGrant) GetBenefitFeatureFlag() *BenefitFeatureFlag {
	return b.GetBenefit().BenefitFeatureFlag
}

func (b *BenefitGrant) GetBenefitGithubRepository() *BenefitGitHubRepository {
	return b.GetBenefit().BenefitGitHubRepository
}

func (b *BenefitGrant) GetBenefitLicenseKeys() *BenefitLicenseKeys {
	return b.GetBenefit().BenefitLicenseKeys
}

func (b *BenefitGrant) GetBenefitMeterCredit() *BenefitMeterCredit {
	return b.GetBenefit().BenefitMeterCredit
}

func (b *BenefitGrant) GetProperties() Properties {
	if b == nil {
		return Properties{}
	}
	return b.Properties
}
