// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type BenefitGrantDiscordWebhook struct {
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the grant.
	ID string `json:"id"`
	// The timestamp when the benefit was granted. If `None`, the benefit is not granted.
	GrantedAt *time.Time `json:"granted_at,omitempty"`
	// Whether the benefit is granted.
	IsGranted bool `json:"is_granted"`
	// The timestamp when the benefit was revoked. If `None`, the benefit is not revoked.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// Whether the benefit is revoked.
	IsRevoked bool `json:"is_revoked"`
	// The ID of the subscription that granted this benefit.
	SubscriptionID *string `json:"subscription_id"`
	// The ID of the order that granted this benefit.
	OrderID *string `json:"order_id"`
	// The ID of the customer concerned by this grant.
	CustomerID string `json:"customer_id"`
	// The ID of the benefit concerned by this grant.
	BenefitID string `json:"benefit_id"`
	// The error information if the benefit grant failed with an unrecoverable error.
	Error *BenefitGrantError `json:"error,omitempty"`
	// A customer in an organization.
	Customer Customer `json:"customer"`
	// A benefit of type `discord`.
	//
	// Use it to automatically invite your backers to a Discord server.
	Benefit            BenefitDiscord                 `json:"benefit"`
	Properties         BenefitGrantDiscordProperties  `json:"properties"`
	PreviousProperties *BenefitGrantDiscordProperties `json:"previous_properties,omitempty"`
}

func (b BenefitGrantDiscordWebhook) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BenefitGrantDiscordWebhook) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"created_at", "modified_at", "id", "is_granted", "is_revoked", "subscription_id", "order_id", "customer_id", "benefit_id", "customer", "benefit", "properties"}); err != nil {
		return err
	}
	return nil
}

func (b *BenefitGrantDiscordWebhook) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}

func (b *BenefitGrantDiscordWebhook) GetModifiedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.ModifiedAt
}

func (b *BenefitGrantDiscordWebhook) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BenefitGrantDiscordWebhook) GetGrantedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.GrantedAt
}

func (b *BenefitGrantDiscordWebhook) GetIsGranted() bool {
	if b == nil {
		return false
	}
	return b.IsGranted
}

func (b *BenefitGrantDiscordWebhook) GetRevokedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.RevokedAt
}

func (b *BenefitGrantDiscordWebhook) GetIsRevoked() bool {
	if b == nil {
		return false
	}
	return b.IsRevoked
}

func (b *BenefitGrantDiscordWebhook) GetSubscriptionID() *string {
	if b == nil {
		return nil
	}
	return b.SubscriptionID
}

func (b *BenefitGrantDiscordWebhook) GetOrderID() *string {
	if b == nil {
		return nil
	}
	return b.OrderID
}

func (b *BenefitGrantDiscordWebhook) GetCustomerID() string {
	if b == nil {
		return ""
	}
	return b.CustomerID
}

func (b *BenefitGrantDiscordWebhook) GetBenefitID() string {
	if b == nil {
		return ""
	}
	return b.BenefitID
}

func (b *BenefitGrantDiscordWebhook) GetError() *BenefitGrantError {
	if b == nil {
		return nil
	}
	return b.Error
}

func (b *BenefitGrantDiscordWebhook) GetCustomer() Customer {
	if b == nil {
		return Customer{}
	}
	return b.Customer
}

func (b *BenefitGrantDiscordWebhook) GetBenefit() BenefitDiscord {
	if b == nil {
		return BenefitDiscord{}
	}
	return b.Benefit
}

func (b *BenefitGrantDiscordWebhook) GetProperties() BenefitGrantDiscordProperties {
	if b == nil {
		return BenefitGrantDiscordProperties{}
	}
	return b.Properties
}

func (b *BenefitGrantDiscordWebhook) GetPreviousProperties() *BenefitGrantDiscordProperties {
	if b == nil {
		return nil
	}
	return b.PreviousProperties
}
