// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

// BenefitDiscord - A benefit of type `discord`.
//
// Use it to automatically invite your backers to a Discord server.
type BenefitDiscord struct {
	// The ID of the benefit.
	ID string `json:"id"`
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"discord" json:"type"`
	// The description of the benefit.
	Description string `json:"description"`
	// Whether the benefit is selectable when creating a product.
	Selectable bool `json:"selectable"`
	// Whether the benefit is deletable.
	Deletable bool `json:"deletable"`
	// Whether the benefit is deleted.
	IsDeleted bool `json:"is_deleted"`
	// The ID of the organization owning the benefit.
	OrganizationID string                        `json:"organization_id"`
	Metadata       map[string]MetadataOutputType `json:"metadata"`
	Visibility     BenefitVisibility             `json:"visibility"`
	// Properties for a benefit of type `discord`.
	Properties             BenefitDiscordProperties `json:"properties"`
	VisibilityConfigurable bool                     `json:"visibility_configurable"`
}

func (b BenefitDiscord) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BenefitDiscord) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"id", "created_at", "type", "description", "selectable", "deletable", "is_deleted", "organization_id", "metadata", "visibility", "properties", "visibility_configurable"}); err != nil {
		return err
	}
	return nil
}

func (b *BenefitDiscord) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BenefitDiscord) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}

func (b *BenefitDiscord) GetModifiedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.ModifiedAt
}

func (b *BenefitDiscord) GetType() string {
	return "discord"
}

func (b *BenefitDiscord) GetDescription() string {
	if b == nil {
		return ""
	}
	return b.Description
}

func (b *BenefitDiscord) GetSelectable() bool {
	if b == nil {
		return false
	}
	return b.Selectable
}

func (b *BenefitDiscord) GetDeletable() bool {
	if b == nil {
		return false
	}
	return b.Deletable
}

func (b *BenefitDiscord) GetIsDeleted() bool {
	if b == nil {
		return false
	}
	return b.IsDeleted
}

func (b *BenefitDiscord) GetOrganizationID() string {
	if b == nil {
		return ""
	}
	return b.OrganizationID
}

func (b *BenefitDiscord) GetMetadata() map[string]MetadataOutputType {
	if b == nil {
		return map[string]MetadataOutputType{}
	}
	return b.Metadata
}

func (b *BenefitDiscord) GetVisibility() BenefitVisibility {
	if b == nil {
		return BenefitVisibility("")
	}
	return b.Visibility
}

func (b *BenefitDiscord) GetProperties() BenefitDiscordProperties {
	if b == nil {
		return BenefitDiscordProperties{}
	}
	return b.Properties
}

func (b *BenefitDiscord) GetVisibilityConfigurable() bool {
	if b == nil {
		return false
	}
	return b.VisibilityConfigurable
}
