// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BenefitLicenseKeyActivationCreateProperties struct {
	Limit               int64 `json:"limit"`
	EnableCustomerAdmin bool  `json:"enable_customer_admin"`
}

func (o *BenefitLicenseKeyActivationCreateProperties) GetLimit() int64 {
	if o == nil {
		return 0
	}
	return o.Limit
}

func (o *BenefitLicenseKeyActivationCreateProperties) GetEnableCustomerAdmin() bool {
	if o == nil {
		return false
	}
	return o.EnableCustomerAdmin
}
