// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type BenefitDownloadables struct {
	// The ID of the benefit.
	ID string `json:"id"`
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"downloadables" json:"type"`
	// The description of the benefit.
	Description string `json:"description"`
	// Whether the benefit is selectable when creating a product.
	Selectable bool `json:"selectable"`
	// Whether the benefit is deletable.
	Deletable bool `json:"deletable"`
	// Whether the benefit is deleted.
	IsDeleted bool `json:"is_deleted"`
	// The ID of the organization owning the benefit.
	OrganizationID         string                         `json:"organization_id"`
	Metadata               map[string]MetadataOutputType  `json:"metadata"`
	Visibility             BenefitVisibility              `json:"visibility"`
	Properties             BenefitDownloadablesProperties `json:"properties"`
	VisibilityConfigurable bool                           `json:"visibility_configurable"`
}

func (b BenefitDownloadables) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BenefitDownloadables) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"id", "created_at", "type", "description", "selectable", "deletable", "is_deleted", "organization_id", "metadata", "visibility", "properties", "visibility_configurable"}); err != nil {
		return err
	}
	return nil
}

func (b *BenefitDownloadables) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BenefitDownloadables) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}

func (b *BenefitDownloadables) GetModifiedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.ModifiedAt
}

func (b *BenefitDownloadables) GetType() string {
	return "downloadables"
}

func (b *BenefitDownloadables) GetDescription() string {
	if b == nil {
		return ""
	}
	return b.Description
}

func (b *BenefitDownloadables) GetSelectable() bool {
	if b == nil {
		return false
	}
	return b.Selectable
}

func (b *BenefitDownloadables) GetDeletable() bool {
	if b == nil {
		return false
	}
	return b.Deletable
}

func (b *BenefitDownloadables) GetIsDeleted() bool {
	if b == nil {
		return false
	}
	return b.IsDeleted
}

func (b *BenefitDownloadables) GetOrganizationID() string {
	if b == nil {
		return ""
	}
	return b.OrganizationID
}

func (b *BenefitDownloadables) GetMetadata() map[string]MetadataOutputType {
	if b == nil {
		return map[string]MetadataOutputType{}
	}
	return b.Metadata
}

func (b *BenefitDownloadables) GetVisibility() BenefitVisibility {
	if b == nil {
		return BenefitVisibility("")
	}
	return b.Visibility
}

func (b *BenefitDownloadables) GetProperties() BenefitDownloadablesProperties {
	if b == nil {
		return BenefitDownloadablesProperties{}
	}
	return b.Properties
}

func (b *BenefitDownloadables) GetVisibilityConfigurable() bool {
	if b == nil {
		return false
	}
	return b.VisibilityConfigurable
}
