// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type BenefitAdsSubscriberType string

const (
	BenefitAdsSubscriberTypeAds BenefitAdsSubscriberType = "ads"
)

func (e BenefitAdsSubscriberType) ToPointer() *BenefitAdsSubscriberType {
	return &e
}
func (e *BenefitAdsSubscriberType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ads":
		*e = BenefitAdsSubscriberType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BenefitAdsSubscriberType: %v", v)
	}
}

type BenefitAdsSubscriber struct {
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the benefit.
	ID    string                   `json:"id"`
	type_ BenefitAdsSubscriberType `const:"ads" json:"type"`
	// The description of the benefit.
	Description string `json:"description"`
	// Whether the benefit is selectable when creating a product.
	Selectable bool `json:"selectable"`
	// Whether the benefit is deletable.
	Deletable bool `json:"deletable"`
	// The ID of the organization owning the benefit.
	OrganizationID string       `json:"organization_id"`
	Organization   Organization `json:"organization"`
	// Properties for a benefit of type `ads`.
	Properties BenefitAdsProperties `json:"properties"`
}

func (b BenefitAdsSubscriber) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BenefitAdsSubscriber) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *BenefitAdsSubscriber) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *BenefitAdsSubscriber) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}

func (o *BenefitAdsSubscriber) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *BenefitAdsSubscriber) GetType() BenefitAdsSubscriberType {
	return BenefitAdsSubscriberTypeAds
}

func (o *BenefitAdsSubscriber) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *BenefitAdsSubscriber) GetSelectable() bool {
	if o == nil {
		return false
	}
	return o.Selectable
}

func (o *BenefitAdsSubscriber) GetDeletable() bool {
	if o == nil {
		return false
	}
	return o.Deletable
}

func (o *BenefitAdsSubscriber) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *BenefitAdsSubscriber) GetOrganization() Organization {
	if o == nil {
		return Organization{}
	}
	return o.Organization
}

func (o *BenefitAdsSubscriber) GetProperties() BenefitAdsProperties {
	if o == nil {
		return BenefitAdsProperties{}
	}
	return o.Properties
}
