// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
)

// BenefitMeterCreditCreate - Schema to create a benefit of type `meter_unit`.
type BenefitMeterCreditCreate struct {
	type_ string `const:"meter_credit" json:"type"`
	// The description of the benefit. Will be displayed on products having this benefit.
	Description string `json:"description"`
	// The ID of the organization owning the benefit. **Required unless you use an organization token.**
	OrganizationID *string `json:"organization_id,omitempty"`
	// Properties for creating a benefit of type `meter_unit`.
	Properties BenefitMeterCreditCreateProperties `json:"properties"`
}

func (b BenefitMeterCreditCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BenefitMeterCreditCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *BenefitMeterCreditCreate) GetType() string {
	return "meter_credit"
}

func (o *BenefitMeterCreditCreate) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *BenefitMeterCreditCreate) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

func (o *BenefitMeterCreditCreate) GetProperties() BenefitMeterCreditCreateProperties {
	if o == nil {
		return BenefitMeterCreditCreateProperties{}
	}
	return o.Properties
}
