// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type BenefitCustomSubscriber struct {
	// The ID of the benefit.
	ID string `json:"id"`
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"custom" json:"type"`
	// The description of the benefit.
	Description string `json:"description"`
	// Whether the benefit is selectable when creating a product.
	Selectable bool `json:"selectable"`
	// Whether the benefit is deletable.
	Deletable bool `json:"deletable"`
	// Whether the benefit is deleted.
	IsDeleted bool `json:"is_deleted"`
	// The ID of the organization owning the benefit.
	OrganizationID string                        `json:"organization_id"`
	Organization   BenefitSubscriberOrganization `json:"organization"`
	// Properties available to subscribers for a benefit of type `custom`.
	Properties BenefitCustomSubscriberProperties `json:"properties"`
}

func (b BenefitCustomSubscriber) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BenefitCustomSubscriber) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"id", "created_at", "type", "description", "selectable", "deletable", "is_deleted", "organization_id", "organization", "properties"}); err != nil {
		return err
	}
	return nil
}

func (b *BenefitCustomSubscriber) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BenefitCustomSubscriber) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}

func (b *BenefitCustomSubscriber) GetModifiedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.ModifiedAt
}

func (b *BenefitCustomSubscriber) GetType() string {
	return "custom"
}

func (b *BenefitCustomSubscriber) GetDescription() string {
	if b == nil {
		return ""
	}
	return b.Description
}

func (b *BenefitCustomSubscriber) GetSelectable() bool {
	if b == nil {
		return false
	}
	return b.Selectable
}

func (b *BenefitCustomSubscriber) GetDeletable() bool {
	if b == nil {
		return false
	}
	return b.Deletable
}

func (b *BenefitCustomSubscriber) GetIsDeleted() bool {
	if b == nil {
		return false
	}
	return b.IsDeleted
}

func (b *BenefitCustomSubscriber) GetOrganizationID() string {
	if b == nil {
		return ""
	}
	return b.OrganizationID
}

func (b *BenefitCustomSubscriber) GetOrganization() BenefitSubscriberOrganization {
	if b == nil {
		return BenefitSubscriberOrganization{}
	}
	return b.Organization
}

func (b *BenefitCustomSubscriber) GetProperties() BenefitCustomSubscriberProperties {
	if b == nil {
		return BenefitCustomSubscriberProperties{}
	}
	return b.Properties
}
