// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
)

type BenefitGitHubRepositoryUpdate struct {
	// The description of the benefit. Will be displayed on products having this benefit.
	Description *string                                  `json:"description,omitempty"`
	type_       string                                   `const:"github_repository" json:"type"`
	Properties  *BenefitGitHubRepositoryCreateProperties `json:"properties,omitempty"`
}

func (b BenefitGitHubRepositoryUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BenefitGitHubRepositoryUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *BenefitGitHubRepositoryUpdate) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *BenefitGitHubRepositoryUpdate) GetType() string {
	return "github_repository"
}

func (o *BenefitGitHubRepositoryUpdate) GetProperties() *BenefitGitHubRepositoryCreateProperties {
	if o == nil {
		return nil
	}
	return o.Properties
}
