// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type CheckoutLinkDiscountType string

const (
	CheckoutLinkDiscountTypeDiscountFixedOnceForeverDurationBase      CheckoutLinkDiscountType = "DiscountFixedOnceForeverDurationBase"
	CheckoutLinkDiscountTypeDiscountFixedRepeatDurationBase           CheckoutLinkDiscountType = "DiscountFixedRepeatDurationBase"
	CheckoutLinkDiscountTypeDiscountPercentageOnceForeverDurationBase CheckoutLinkDiscountType = "DiscountPercentageOnceForeverDurationBase"
	CheckoutLinkDiscountTypeDiscountPercentageRepeatDurationBase      CheckoutLinkDiscountType = "DiscountPercentageRepeatDurationBase"
)

type CheckoutLinkDiscount struct {
	DiscountFixedOnceForeverDurationBase      *DiscountFixedOnceForeverDurationBase      `queryParam:"inline" union:"member"`
	DiscountFixedRepeatDurationBase           *DiscountFixedRepeatDurationBase           `queryParam:"inline" union:"member"`
	DiscountPercentageOnceForeverDurationBase *DiscountPercentageOnceForeverDurationBase `queryParam:"inline" union:"member"`
	DiscountPercentageRepeatDurationBase      *DiscountPercentageRepeatDurationBase      `queryParam:"inline" union:"member"`

	Type CheckoutLinkDiscountType
}

func CreateCheckoutLinkDiscountDiscountFixedOnceForeverDurationBase(discountFixedOnceForeverDurationBase DiscountFixedOnceForeverDurationBase) CheckoutLinkDiscount {
	typ := CheckoutLinkDiscountTypeDiscountFixedOnceForeverDurationBase

	return CheckoutLinkDiscount{
		DiscountFixedOnceForeverDurationBase: &discountFixedOnceForeverDurationBase,
		Type:                                 typ,
	}
}

func CreateCheckoutLinkDiscountDiscountFixedRepeatDurationBase(discountFixedRepeatDurationBase DiscountFixedRepeatDurationBase) CheckoutLinkDiscount {
	typ := CheckoutLinkDiscountTypeDiscountFixedRepeatDurationBase

	return CheckoutLinkDiscount{
		DiscountFixedRepeatDurationBase: &discountFixedRepeatDurationBase,
		Type:                            typ,
	}
}

func CreateCheckoutLinkDiscountDiscountPercentageOnceForeverDurationBase(discountPercentageOnceForeverDurationBase DiscountPercentageOnceForeverDurationBase) CheckoutLinkDiscount {
	typ := CheckoutLinkDiscountTypeDiscountPercentageOnceForeverDurationBase

	return CheckoutLinkDiscount{
		DiscountPercentageOnceForeverDurationBase: &discountPercentageOnceForeverDurationBase,
		Type: typ,
	}
}

func CreateCheckoutLinkDiscountDiscountPercentageRepeatDurationBase(discountPercentageRepeatDurationBase DiscountPercentageRepeatDurationBase) CheckoutLinkDiscount {
	typ := CheckoutLinkDiscountTypeDiscountPercentageRepeatDurationBase

	return CheckoutLinkDiscount{
		DiscountPercentageRepeatDurationBase: &discountPercentageRepeatDurationBase,
		Type:                                 typ,
	}
}

func (u *CheckoutLinkDiscount) UnmarshalJSON(data []byte) error {

	var discountFixedRepeatDurationBase DiscountFixedRepeatDurationBase = DiscountFixedRepeatDurationBase{}
	if err := utils.UnmarshalJSON(data, &discountFixedRepeatDurationBase, "", true, nil); err == nil {
		u.DiscountFixedRepeatDurationBase = &discountFixedRepeatDurationBase
		u.Type = CheckoutLinkDiscountTypeDiscountFixedRepeatDurationBase
		return nil
	}

	var discountFixedOnceForeverDurationBase DiscountFixedOnceForeverDurationBase = DiscountFixedOnceForeverDurationBase{}
	if err := utils.UnmarshalJSON(data, &discountFixedOnceForeverDurationBase, "", true, nil); err == nil {
		u.DiscountFixedOnceForeverDurationBase = &discountFixedOnceForeverDurationBase
		u.Type = CheckoutLinkDiscountTypeDiscountFixedOnceForeverDurationBase
		return nil
	}

	var discountPercentageRepeatDurationBase DiscountPercentageRepeatDurationBase = DiscountPercentageRepeatDurationBase{}
	if err := utils.UnmarshalJSON(data, &discountPercentageRepeatDurationBase, "", true, nil); err == nil {
		u.DiscountPercentageRepeatDurationBase = &discountPercentageRepeatDurationBase
		u.Type = CheckoutLinkDiscountTypeDiscountPercentageRepeatDurationBase
		return nil
	}

	var discountPercentageOnceForeverDurationBase DiscountPercentageOnceForeverDurationBase = DiscountPercentageOnceForeverDurationBase{}
	if err := utils.UnmarshalJSON(data, &discountPercentageOnceForeverDurationBase, "", true, nil); err == nil {
		u.DiscountPercentageOnceForeverDurationBase = &discountPercentageOnceForeverDurationBase
		u.Type = CheckoutLinkDiscountTypeDiscountPercentageOnceForeverDurationBase
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CheckoutLinkDiscount", string(data))
}

func (u CheckoutLinkDiscount) MarshalJSON() ([]byte, error) {
	if u.DiscountFixedOnceForeverDurationBase != nil {
		return utils.MarshalJSON(u.DiscountFixedOnceForeverDurationBase, "", true)
	}

	if u.DiscountFixedRepeatDurationBase != nil {
		return utils.MarshalJSON(u.DiscountFixedRepeatDurationBase, "", true)
	}

	if u.DiscountPercentageOnceForeverDurationBase != nil {
		return utils.MarshalJSON(u.DiscountPercentageOnceForeverDurationBase, "", true)
	}

	if u.DiscountPercentageRepeatDurationBase != nil {
		return utils.MarshalJSON(u.DiscountPercentageRepeatDurationBase, "", true)
	}

	return nil, errors.New("could not marshal union type CheckoutLinkDiscount: all fields are null")
}

// CheckoutLink - Checkout link data.
type CheckoutLink struct {
	// The ID of the object.
	ID string `json:"id"`
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The interval unit for the trial period.
	TrialInterval *TrialInterval `json:"trial_interval"`
	// The number of interval units for the trial period.
	TrialIntervalCount *int64                        `json:"trial_interval_count"`
	Metadata           map[string]MetadataOutputType `json:"metadata"`
	PaymentProcessor   PaymentProcessor              `json:"payment_processor"`
	// Client secret used to access the checkout link.
	ClientSecret string `json:"client_secret"`
	// URL where the customer will be redirected after a successful payment.
	SuccessURL *string `json:"success_url"`
	// When set, a back button will be shown in the checkout to return to this URL.
	ReturnURL *string `json:"return_url"`
	// Optional label to distinguish links internally
	Label *string `json:"label"`
	// Whether to allow the customer to apply discount codes. If you apply a discount through `discount_id`, it'll still be applied, but the customer won't be able to change it.
	AllowDiscountCodes bool `json:"allow_discount_codes"`
	// Whether to require the customer to fill their full billing address, instead of just the country. Customers in the US will always be required to fill their full address, regardless of this setting.
	RequireBillingAddress bool `json:"require_billing_address"`
	// ID of the discount to apply to the checkout. If the discount is not applicable anymore when opening the checkout link, it'll be ignored.
	DiscountID *string `json:"discount_id"`
	// The organization ID.
	OrganizationID string                `json:"organization_id"`
	Products       []CheckoutLinkProduct `json:"products"`
	Discount       *CheckoutLinkDiscount `json:"discount"`
	URL            string                `json:"url"`
}

func (c CheckoutLink) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CheckoutLink) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CheckoutLink) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CheckoutLink) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CheckoutLink) GetModifiedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ModifiedAt
}

func (c *CheckoutLink) GetTrialInterval() *TrialInterval {
	if c == nil {
		return nil
	}
	return c.TrialInterval
}

func (c *CheckoutLink) GetTrialIntervalCount() *int64 {
	if c == nil {
		return nil
	}
	return c.TrialIntervalCount
}

func (c *CheckoutLink) GetMetadata() map[string]MetadataOutputType {
	if c == nil {
		return map[string]MetadataOutputType{}
	}
	return c.Metadata
}

func (c *CheckoutLink) GetPaymentProcessor() PaymentProcessor {
	if c == nil {
		return PaymentProcessor("")
	}
	return c.PaymentProcessor
}

func (c *CheckoutLink) GetClientSecret() string {
	if c == nil {
		return ""
	}
	return c.ClientSecret
}

func (c *CheckoutLink) GetSuccessURL() *string {
	if c == nil {
		return nil
	}
	return c.SuccessURL
}

func (c *CheckoutLink) GetReturnURL() *string {
	if c == nil {
		return nil
	}
	return c.ReturnURL
}

func (c *CheckoutLink) GetLabel() *string {
	if c == nil {
		return nil
	}
	return c.Label
}

func (c *CheckoutLink) GetAllowDiscountCodes() bool {
	if c == nil {
		return false
	}
	return c.AllowDiscountCodes
}

func (c *CheckoutLink) GetRequireBillingAddress() bool {
	if c == nil {
		return false
	}
	return c.RequireBillingAddress
}

func (c *CheckoutLink) GetDiscountID() *string {
	if c == nil {
		return nil
	}
	return c.DiscountID
}

func (c *CheckoutLink) GetOrganizationID() string {
	if c == nil {
		return ""
	}
	return c.OrganizationID
}

func (c *CheckoutLink) GetProducts() []CheckoutLinkProduct {
	if c == nil {
		return []CheckoutLinkProduct{}
	}
	return c.Products
}

func (c *CheckoutLink) GetDiscount() *CheckoutLinkDiscount {
	if c == nil {
		return nil
	}
	return c.Discount
}

func (c *CheckoutLink) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}
