// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type CheckoutProductPricesType string

const (
	CheckoutProductPricesTypeLegacyRecurringProductPrice CheckoutProductPricesType = "LegacyRecurringProductPrice"
	CheckoutProductPricesTypeProductPrice                CheckoutProductPricesType = "ProductPrice"
)

type CheckoutProductPrices struct {
	LegacyRecurringProductPrice *LegacyRecurringProductPrice `queryParam:"inline" name:"prices"`
	ProductPrice                *ProductPrice                `queryParam:"inline" name:"prices"`

	Type CheckoutProductPricesType
}

func CreateCheckoutProductPricesLegacyRecurringProductPrice(legacyRecurringProductPrice LegacyRecurringProductPrice) CheckoutProductPrices {
	typ := CheckoutProductPricesTypeLegacyRecurringProductPrice

	return CheckoutProductPrices{
		LegacyRecurringProductPrice: &legacyRecurringProductPrice,
		Type:                        typ,
	}
}

func CreateCheckoutProductPricesProductPrice(productPrice ProductPrice) CheckoutProductPrices {
	typ := CheckoutProductPricesTypeProductPrice

	return CheckoutProductPrices{
		ProductPrice: &productPrice,
		Type:         typ,
	}
}

func (u *CheckoutProductPrices) UnmarshalJSON(data []byte) error {

	var legacyRecurringProductPrice LegacyRecurringProductPrice = LegacyRecurringProductPrice{}
	if err := utils.UnmarshalJSON(data, &legacyRecurringProductPrice, "", true, nil); err == nil {
		u.LegacyRecurringProductPrice = &legacyRecurringProductPrice
		u.Type = CheckoutProductPricesTypeLegacyRecurringProductPrice
		return nil
	}

	var productPrice ProductPrice = ProductPrice{}
	if err := utils.UnmarshalJSON(data, &productPrice, "", true, nil); err == nil {
		u.ProductPrice = &productPrice
		u.Type = CheckoutProductPricesTypeProductPrice
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CheckoutProductPrices", string(data))
}

func (u CheckoutProductPrices) MarshalJSON() ([]byte, error) {
	if u.LegacyRecurringProductPrice != nil {
		return utils.MarshalJSON(u.LegacyRecurringProductPrice, "", true)
	}

	if u.ProductPrice != nil {
		return utils.MarshalJSON(u.ProductPrice, "", true)
	}

	return nil, errors.New("could not marshal union type CheckoutProductPrices: all fields are null")
}

// CheckoutProduct - Product data for a checkout session.
type CheckoutProduct struct {
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the product.
	ID string `json:"id"`
	// The name of the product.
	Name string `json:"name"`
	// The description of the product.
	Description *string `json:"description"`
	// The recurring interval of the product. If `None`, the product is a one-time purchase.Note that the `day` and `week` values are for internal Polar staff use only.
	RecurringInterval *SubscriptionRecurringInterval `json:"recurring_interval"`
	// Whether the product is a subscription.
	IsRecurring bool `json:"is_recurring"`
	// Whether the product is archived and no longer available.
	IsArchived bool `json:"is_archived"`
	// The ID of the organization owning the product.
	OrganizationID string `json:"organization_id"`
	// List of prices for this product.
	Prices []CheckoutProductPrices `json:"prices"`
	// List of benefits granted by the product.
	Benefits []BenefitPublic `json:"benefits"`
	// List of medias associated to the product.
	Medias []ProductMediaFileRead `json:"medias"`
}

func (c CheckoutProduct) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CheckoutProduct) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"created_at", "modified_at", "id", "name", "description", "recurring_interval", "is_recurring", "is_archived", "organization_id", "prices", "benefits", "medias"}); err != nil {
		return err
	}
	return nil
}

func (c *CheckoutProduct) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CheckoutProduct) GetModifiedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ModifiedAt
}

func (c *CheckoutProduct) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CheckoutProduct) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CheckoutProduct) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CheckoutProduct) GetRecurringInterval() *SubscriptionRecurringInterval {
	if c == nil {
		return nil
	}
	return c.RecurringInterval
}

func (c *CheckoutProduct) GetIsRecurring() bool {
	if c == nil {
		return false
	}
	return c.IsRecurring
}

func (c *CheckoutProduct) GetIsArchived() bool {
	if c == nil {
		return false
	}
	return c.IsArchived
}

func (c *CheckoutProduct) GetOrganizationID() string {
	if c == nil {
		return ""
	}
	return c.OrganizationID
}

func (c *CheckoutProduct) GetPrices() []CheckoutProductPrices {
	if c == nil {
		return []CheckoutProductPrices{}
	}
	return c.Prices
}

func (c *CheckoutProduct) GetBenefits() []BenefitPublic {
	if c == nil {
		return []BenefitPublic{}
	}
	return c.Benefits
}

func (c *CheckoutProduct) GetMedias() []ProductMediaFileRead {
	if c == nil {
		return []ProductMediaFileRead{}
	}
	return c.Medias
}
