// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
)

// CheckoutDiscountFixedOnceForeverDuration - Schema for a fixed amount discount that is applied once or forever.
type CheckoutDiscountFixedOnceForeverDuration struct {
	Duration DiscountDuration `json:"duration"`
	Type     DiscountType     `json:"type"`
	Amount   int64            `json:"amount"`
	Currency string           `json:"currency"`
	// The ID of the object.
	ID   string  `json:"id"`
	Name string  `json:"name"`
	Code *string `json:"code"`
}

func (c CheckoutDiscountFixedOnceForeverDuration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CheckoutDiscountFixedOnceForeverDuration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"duration", "type", "amount", "currency", "id", "name", "code"}); err != nil {
		return err
	}
	return nil
}

func (o *CheckoutDiscountFixedOnceForeverDuration) GetDuration() DiscountDuration {
	if o == nil {
		return DiscountDuration("")
	}
	return o.Duration
}

func (o *CheckoutDiscountFixedOnceForeverDuration) GetType() DiscountType {
	if o == nil {
		return DiscountType("")
	}
	return o.Type
}

func (o *CheckoutDiscountFixedOnceForeverDuration) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}

func (o *CheckoutDiscountFixedOnceForeverDuration) GetCurrency() string {
	if o == nil {
		return ""
	}
	return o.Currency
}

func (o *CheckoutDiscountFixedOnceForeverDuration) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CheckoutDiscountFixedOnceForeverDuration) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CheckoutDiscountFixedOnceForeverDuration) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}
