// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type CheckoutConfirmStripeCustomFieldDataType string

const (
	CheckoutConfirmStripeCustomFieldDataTypeStr      CheckoutConfirmStripeCustomFieldDataType = "str"
	CheckoutConfirmStripeCustomFieldDataTypeInteger  CheckoutConfirmStripeCustomFieldDataType = "integer"
	CheckoutConfirmStripeCustomFieldDataTypeBoolean  CheckoutConfirmStripeCustomFieldDataType = "boolean"
	CheckoutConfirmStripeCustomFieldDataTypeDateTime CheckoutConfirmStripeCustomFieldDataType = "date-time"
)

type CheckoutConfirmStripeCustomFieldData struct {
	Str      *string    `queryParam:"inline,name=custom_field_data"`
	Integer  *int64     `queryParam:"inline,name=custom_field_data"`
	Boolean  *bool      `queryParam:"inline,name=custom_field_data"`
	DateTime *time.Time `queryParam:"inline,name=custom_field_data"`

	Type CheckoutConfirmStripeCustomFieldDataType
}

func CreateCheckoutConfirmStripeCustomFieldDataStr(str string) CheckoutConfirmStripeCustomFieldData {
	typ := CheckoutConfirmStripeCustomFieldDataTypeStr

	return CheckoutConfirmStripeCustomFieldData{
		Str:  &str,
		Type: typ,
	}
}

func CreateCheckoutConfirmStripeCustomFieldDataInteger(integer int64) CheckoutConfirmStripeCustomFieldData {
	typ := CheckoutConfirmStripeCustomFieldDataTypeInteger

	return CheckoutConfirmStripeCustomFieldData{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateCheckoutConfirmStripeCustomFieldDataBoolean(boolean bool) CheckoutConfirmStripeCustomFieldData {
	typ := CheckoutConfirmStripeCustomFieldDataTypeBoolean

	return CheckoutConfirmStripeCustomFieldData{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateCheckoutConfirmStripeCustomFieldDataDateTime(dateTime time.Time) CheckoutConfirmStripeCustomFieldData {
	typ := CheckoutConfirmStripeCustomFieldDataTypeDateTime

	return CheckoutConfirmStripeCustomFieldData{
		DateTime: &dateTime,
		Type:     typ,
	}
}

func (u *CheckoutConfirmStripeCustomFieldData) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = CheckoutConfirmStripeCustomFieldDataTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = CheckoutConfirmStripeCustomFieldDataTypeInteger
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = CheckoutConfirmStripeCustomFieldDataTypeBoolean
		return nil
	}

	var dateTime time.Time = time.Time{}
	if err := utils.UnmarshalJSON(data, &dateTime, "", true, nil); err == nil {
		u.DateTime = &dateTime
		u.Type = CheckoutConfirmStripeCustomFieldDataTypeDateTime
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CheckoutConfirmStripeCustomFieldData", string(data))
}

func (u CheckoutConfirmStripeCustomFieldData) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.DateTime != nil {
		return utils.MarshalJSON(u.DateTime, "", true)
	}

	return nil, errors.New("could not marshal union type CheckoutConfirmStripeCustomFieldData: all fields are null")
}

// CheckoutConfirmStripe - Confirm a checkout session using a Stripe confirmation token.
type CheckoutConfirmStripe struct {
	// Key-value object storing custom field values.
	CustomFieldData map[string]*CheckoutConfirmStripeCustomFieldData `json:"custom_field_data,omitempty"`
	// ID of the product to checkout. Must be present in the checkout's product list.
	ProductID *string `json:"product_id,omitempty"`
	// ID of the product price to checkout. Must correspond to a price present in the checkout's product list.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ProductPriceID         *string       `json:"product_price_id,omitempty"`
	Amount                 *int64        `json:"amount,omitempty"`
	IsBusinessCustomer     *bool         `json:"is_business_customer,omitempty"`
	CustomerName           *string       `json:"customer_name,omitempty"`
	CustomerEmail          *string       `json:"customer_email,omitempty"`
	CustomerBillingName    *string       `json:"customer_billing_name,omitempty"`
	CustomerBillingAddress *AddressInput `json:"customer_billing_address,omitempty"`
	CustomerTaxID          *string       `json:"customer_tax_id,omitempty"`
	// Discount code to apply to the checkout.
	DiscountCode *string `json:"discount_code,omitempty"`
	// ID of the Stripe confirmation token. Required for fixed prices and custom prices.
	ConfirmationTokenID *string `json:"confirmation_token_id,omitempty"`
}

func (c *CheckoutConfirmStripe) GetCustomFieldData() map[string]*CheckoutConfirmStripeCustomFieldData {
	if c == nil {
		return nil
	}
	return c.CustomFieldData
}

func (c *CheckoutConfirmStripe) GetProductID() *string {
	if c == nil {
		return nil
	}
	return c.ProductID
}

func (c *CheckoutConfirmStripe) GetProductPriceID() *string {
	if c == nil {
		return nil
	}
	return c.ProductPriceID
}

func (c *CheckoutConfirmStripe) GetAmount() *int64 {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CheckoutConfirmStripe) GetIsBusinessCustomer() *bool {
	if c == nil {
		return nil
	}
	return c.IsBusinessCustomer
}

func (c *CheckoutConfirmStripe) GetCustomerName() *string {
	if c == nil {
		return nil
	}
	return c.CustomerName
}

func (c *CheckoutConfirmStripe) GetCustomerEmail() *string {
	if c == nil {
		return nil
	}
	return c.CustomerEmail
}

func (c *CheckoutConfirmStripe) GetCustomerBillingName() *string {
	if c == nil {
		return nil
	}
	return c.CustomerBillingName
}

func (c *CheckoutConfirmStripe) GetCustomerBillingAddress() *AddressInput {
	if c == nil {
		return nil
	}
	return c.CustomerBillingAddress
}

func (c *CheckoutConfirmStripe) GetCustomerTaxID() *string {
	if c == nil {
		return nil
	}
	return c.CustomerTaxID
}

func (c *CheckoutConfirmStripe) GetDiscountCode() *string {
	if c == nil {
		return nil
	}
	return c.DiscountCode
}

func (c *CheckoutConfirmStripe) GetConfirmationTokenID() *string {
	if c == nil {
		return nil
	}
	return c.ConfirmationTokenID
}
