// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type CheckoutCreateMetadataType string

const (
	CheckoutCreateMetadataTypeStr     CheckoutCreateMetadataType = "str"
	CheckoutCreateMetadataTypeInteger CheckoutCreateMetadataType = "integer"
	CheckoutCreateMetadataTypeNumber  CheckoutCreateMetadataType = "number"
	CheckoutCreateMetadataTypeBoolean CheckoutCreateMetadataType = "boolean"
)

type CheckoutCreateMetadata struct {
	Str     *string  `queryParam:"inline" union:"member"`
	Integer *int64   `queryParam:"inline" union:"member"`
	Number  *float64 `queryParam:"inline" union:"member"`
	Boolean *bool    `queryParam:"inline" union:"member"`

	Type CheckoutCreateMetadataType
}

func CreateCheckoutCreateMetadataStr(str string) CheckoutCreateMetadata {
	typ := CheckoutCreateMetadataTypeStr

	return CheckoutCreateMetadata{
		Str:  &str,
		Type: typ,
	}
}

func CreateCheckoutCreateMetadataInteger(integer int64) CheckoutCreateMetadata {
	typ := CheckoutCreateMetadataTypeInteger

	return CheckoutCreateMetadata{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateCheckoutCreateMetadataNumber(number float64) CheckoutCreateMetadata {
	typ := CheckoutCreateMetadataTypeNumber

	return CheckoutCreateMetadata{
		Number: &number,
		Type:   typ,
	}
}

func CreateCheckoutCreateMetadataBoolean(boolean bool) CheckoutCreateMetadata {
	typ := CheckoutCreateMetadataTypeBoolean

	return CheckoutCreateMetadata{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *CheckoutCreateMetadata) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = CheckoutCreateMetadataTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = CheckoutCreateMetadataTypeInteger
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = CheckoutCreateMetadataTypeNumber
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = CheckoutCreateMetadataTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CheckoutCreateMetadata", string(data))
}

func (u CheckoutCreateMetadata) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type CheckoutCreateMetadata: all fields are null")
}

type CheckoutCreateCustomFieldDataType string

const (
	CheckoutCreateCustomFieldDataTypeStr      CheckoutCreateCustomFieldDataType = "str"
	CheckoutCreateCustomFieldDataTypeInteger  CheckoutCreateCustomFieldDataType = "integer"
	CheckoutCreateCustomFieldDataTypeBoolean  CheckoutCreateCustomFieldDataType = "boolean"
	CheckoutCreateCustomFieldDataTypeDateTime CheckoutCreateCustomFieldDataType = "date-time"
)

type CheckoutCreateCustomFieldData struct {
	Str      *string    `queryParam:"inline" union:"member"`
	Integer  *int64     `queryParam:"inline" union:"member"`
	Boolean  *bool      `queryParam:"inline" union:"member"`
	DateTime *time.Time `queryParam:"inline" union:"member"`

	Type CheckoutCreateCustomFieldDataType
}

func CreateCheckoutCreateCustomFieldDataStr(str string) CheckoutCreateCustomFieldData {
	typ := CheckoutCreateCustomFieldDataTypeStr

	return CheckoutCreateCustomFieldData{
		Str:  &str,
		Type: typ,
	}
}

func CreateCheckoutCreateCustomFieldDataInteger(integer int64) CheckoutCreateCustomFieldData {
	typ := CheckoutCreateCustomFieldDataTypeInteger

	return CheckoutCreateCustomFieldData{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateCheckoutCreateCustomFieldDataBoolean(boolean bool) CheckoutCreateCustomFieldData {
	typ := CheckoutCreateCustomFieldDataTypeBoolean

	return CheckoutCreateCustomFieldData{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateCheckoutCreateCustomFieldDataDateTime(dateTime time.Time) CheckoutCreateCustomFieldData {
	typ := CheckoutCreateCustomFieldDataTypeDateTime

	return CheckoutCreateCustomFieldData{
		DateTime: &dateTime,
		Type:     typ,
	}
}

func (u *CheckoutCreateCustomFieldData) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = CheckoutCreateCustomFieldDataTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = CheckoutCreateCustomFieldDataTypeInteger
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = CheckoutCreateCustomFieldDataTypeBoolean
		return nil
	}

	var dateTime time.Time = time.Time{}
	if err := utils.UnmarshalJSON(data, &dateTime, "", true, nil); err == nil {
		u.DateTime = &dateTime
		u.Type = CheckoutCreateCustomFieldDataTypeDateTime
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CheckoutCreateCustomFieldData", string(data))
}

func (u CheckoutCreateCustomFieldData) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.DateTime != nil {
		return utils.MarshalJSON(u.DateTime, "", true)
	}

	return nil, errors.New("could not marshal union type CheckoutCreateCustomFieldData: all fields are null")
}

type CheckoutCreateCustomerMetadataType string

const (
	CheckoutCreateCustomerMetadataTypeStr     CheckoutCreateCustomerMetadataType = "str"
	CheckoutCreateCustomerMetadataTypeInteger CheckoutCreateCustomerMetadataType = "integer"
	CheckoutCreateCustomerMetadataTypeNumber  CheckoutCreateCustomerMetadataType = "number"
	CheckoutCreateCustomerMetadataTypeBoolean CheckoutCreateCustomerMetadataType = "boolean"
)

type CheckoutCreateCustomerMetadata struct {
	Str     *string  `queryParam:"inline" union:"member"`
	Integer *int64   `queryParam:"inline" union:"member"`
	Number  *float64 `queryParam:"inline" union:"member"`
	Boolean *bool    `queryParam:"inline" union:"member"`

	Type CheckoutCreateCustomerMetadataType
}

func CreateCheckoutCreateCustomerMetadataStr(str string) CheckoutCreateCustomerMetadata {
	typ := CheckoutCreateCustomerMetadataTypeStr

	return CheckoutCreateCustomerMetadata{
		Str:  &str,
		Type: typ,
	}
}

func CreateCheckoutCreateCustomerMetadataInteger(integer int64) CheckoutCreateCustomerMetadata {
	typ := CheckoutCreateCustomerMetadataTypeInteger

	return CheckoutCreateCustomerMetadata{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateCheckoutCreateCustomerMetadataNumber(number float64) CheckoutCreateCustomerMetadata {
	typ := CheckoutCreateCustomerMetadataTypeNumber

	return CheckoutCreateCustomerMetadata{
		Number: &number,
		Type:   typ,
	}
}

func CreateCheckoutCreateCustomerMetadataBoolean(boolean bool) CheckoutCreateCustomerMetadata {
	typ := CheckoutCreateCustomerMetadataTypeBoolean

	return CheckoutCreateCustomerMetadata{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *CheckoutCreateCustomerMetadata) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = CheckoutCreateCustomerMetadataTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = CheckoutCreateCustomerMetadataTypeInteger
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = CheckoutCreateCustomerMetadataTypeNumber
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = CheckoutCreateCustomerMetadataTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CheckoutCreateCustomerMetadata", string(data))
}

func (u CheckoutCreateCustomerMetadata) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type CheckoutCreateCustomerMetadata: all fields are null")
}

type CheckoutCreatePricesType string

const (
	CheckoutCreatePricesTypeCustom      CheckoutCreatePricesType = "custom"
	CheckoutCreatePricesTypeFixed       CheckoutCreatePricesType = "fixed"
	CheckoutCreatePricesTypeFree        CheckoutCreatePricesType = "free"
	CheckoutCreatePricesTypeMeteredUnit CheckoutCreatePricesType = "metered_unit"
	CheckoutCreatePricesTypeSeatBased   CheckoutCreatePricesType = "seat_based"
)

type CheckoutCreatePrices struct {
	ProductPriceFixedCreate       *ProductPriceFixedCreate       `queryParam:"inline" union:"member"`
	ProductPriceCustomCreate      *ProductPriceCustomCreate      `queryParam:"inline" union:"member"`
	ProductPriceFreeCreate        *ProductPriceFreeCreate        `queryParam:"inline" union:"member"`
	ProductPriceSeatBasedCreate   *ProductPriceSeatBasedCreate   `queryParam:"inline" union:"member"`
	ProductPriceMeteredUnitCreate *ProductPriceMeteredUnitCreate `queryParam:"inline" union:"member"`

	Type CheckoutCreatePricesType
}

func CreateCheckoutCreatePricesCustom(custom ProductPriceCustomCreate) CheckoutCreatePrices {
	typ := CheckoutCreatePricesTypeCustom

	return CheckoutCreatePrices{
		ProductPriceCustomCreate: &custom,
		Type:                     typ,
	}
}

func CreateCheckoutCreatePricesFixed(fixed ProductPriceFixedCreate) CheckoutCreatePrices {
	typ := CheckoutCreatePricesTypeFixed

	return CheckoutCreatePrices{
		ProductPriceFixedCreate: &fixed,
		Type:                    typ,
	}
}

func CreateCheckoutCreatePricesFree(free ProductPriceFreeCreate) CheckoutCreatePrices {
	typ := CheckoutCreatePricesTypeFree

	return CheckoutCreatePrices{
		ProductPriceFreeCreate: &free,
		Type:                   typ,
	}
}

func CreateCheckoutCreatePricesMeteredUnit(meteredUnit ProductPriceMeteredUnitCreate) CheckoutCreatePrices {
	typ := CheckoutCreatePricesTypeMeteredUnit

	return CheckoutCreatePrices{
		ProductPriceMeteredUnitCreate: &meteredUnit,
		Type:                          typ,
	}
}

func CreateCheckoutCreatePricesSeatBased(seatBased ProductPriceSeatBasedCreate) CheckoutCreatePrices {
	typ := CheckoutCreatePricesTypeSeatBased

	return CheckoutCreatePrices{
		ProductPriceSeatBasedCreate: &seatBased,
		Type:                        typ,
	}
}

func (u *CheckoutCreatePrices) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		AmountType string `json:"amount_type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.AmountType {
	case "custom":
		productPriceCustomCreate := new(ProductPriceCustomCreate)
		if err := utils.UnmarshalJSON(data, &productPriceCustomCreate, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (AmountType == custom) type ProductPriceCustomCreate within CheckoutCreatePrices: %w", string(data), err)
		}

		u.ProductPriceCustomCreate = productPriceCustomCreate
		u.Type = CheckoutCreatePricesTypeCustom
		return nil
	case "fixed":
		productPriceFixedCreate := new(ProductPriceFixedCreate)
		if err := utils.UnmarshalJSON(data, &productPriceFixedCreate, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (AmountType == fixed) type ProductPriceFixedCreate within CheckoutCreatePrices: %w", string(data), err)
		}

		u.ProductPriceFixedCreate = productPriceFixedCreate
		u.Type = CheckoutCreatePricesTypeFixed
		return nil
	case "free":
		productPriceFreeCreate := new(ProductPriceFreeCreate)
		if err := utils.UnmarshalJSON(data, &productPriceFreeCreate, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (AmountType == free) type ProductPriceFreeCreate within CheckoutCreatePrices: %w", string(data), err)
		}

		u.ProductPriceFreeCreate = productPriceFreeCreate
		u.Type = CheckoutCreatePricesTypeFree
		return nil
	case "metered_unit":
		productPriceMeteredUnitCreate := new(ProductPriceMeteredUnitCreate)
		if err := utils.UnmarshalJSON(data, &productPriceMeteredUnitCreate, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (AmountType == metered_unit) type ProductPriceMeteredUnitCreate within CheckoutCreatePrices: %w", string(data), err)
		}

		u.ProductPriceMeteredUnitCreate = productPriceMeteredUnitCreate
		u.Type = CheckoutCreatePricesTypeMeteredUnit
		return nil
	case "seat_based":
		productPriceSeatBasedCreate := new(ProductPriceSeatBasedCreate)
		if err := utils.UnmarshalJSON(data, &productPriceSeatBasedCreate, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (AmountType == seat_based) type ProductPriceSeatBasedCreate within CheckoutCreatePrices: %w", string(data), err)
		}

		u.ProductPriceSeatBasedCreate = productPriceSeatBasedCreate
		u.Type = CheckoutCreatePricesTypeSeatBased
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CheckoutCreatePrices", string(data))
}

func (u CheckoutCreatePrices) MarshalJSON() ([]byte, error) {
	if u.ProductPriceFixedCreate != nil {
		return utils.MarshalJSON(u.ProductPriceFixedCreate, "", true)
	}

	if u.ProductPriceCustomCreate != nil {
		return utils.MarshalJSON(u.ProductPriceCustomCreate, "", true)
	}

	if u.ProductPriceFreeCreate != nil {
		return utils.MarshalJSON(u.ProductPriceFreeCreate, "", true)
	}

	if u.ProductPriceSeatBasedCreate != nil {
		return utils.MarshalJSON(u.ProductPriceSeatBasedCreate, "", true)
	}

	if u.ProductPriceMeteredUnitCreate != nil {
		return utils.MarshalJSON(u.ProductPriceMeteredUnitCreate, "", true)
	}

	return nil, errors.New("could not marshal union type CheckoutCreatePrices: all fields are null")
}

// CheckoutCreate - Create a new checkout session from a list of products.
// Customers will be able to switch between those products.
//
// Metadata set on the checkout will be copied
// to the resulting order and/or subscription.
type CheckoutCreate struct {
	// The interval unit for the trial period.
	TrialInterval *TrialInterval `json:"trial_interval,omitempty"`
	// The number of interval units for the trial period.
	TrialIntervalCount *int64 `json:"trial_interval_count,omitempty"`
	// Key-value object allowing you to store additional information.
	//
	// The key must be a string with a maximum length of **40 characters**.
	// The value must be either:
	//
	// * A string with a maximum length of **500 characters**
	// * An integer
	// * A floating-point number
	// * A boolean
	//
	// You can store up to **50 key-value pairs**.
	Metadata map[string]CheckoutCreateMetadata `json:"metadata,omitempty"`
	// Key-value object storing custom field values.
	CustomFieldData map[string]*CheckoutCreateCustomFieldData `json:"custom_field_data,omitempty"`
	// ID of the discount to apply to the checkout.
	DiscountID *string `json:"discount_id,omitempty"`
	// Whether to allow the customer to apply discount codes. If you apply a discount through `discount_id`, it'll still be applied, but the customer won't be able to change it.
	AllowDiscountCodes *bool `default:"true" json:"allow_discount_codes"`
	// Whether to require the customer to fill their full billing address, instead of just the country. Customers in the US will always be required to fill their full address, regardless of this setting. If you preset the billing address, this setting will be automatically set to `true`.
	RequireBillingAddress *bool  `default:"false" json:"require_billing_address"`
	Amount                *int64 `json:"amount,omitempty"`
	// Predefined number of seats (works with seat-based pricing only)
	Seats *int64 `json:"seats,omitempty"`
	// Minimum number of seats (works with seat-based pricing only)
	MinSeats *int64 `json:"min_seats,omitempty"`
	// Maximum number of seats (works with seat-based pricing only)
	MaxSeats *int64 `json:"max_seats,omitempty"`
	// Whether to enable the trial period for the checkout session. If `false`, the trial period will be disabled, even if the selected product has a trial configured.
	AllowTrial *bool `default:"true" json:"allow_trial"`
	// ID of an existing customer in the organization. The customer data will be pre-filled in the checkout form. The resulting order will be linked to this customer.
	CustomerID *string `json:"customer_id,omitempty"`
	// Whether the customer is a business or an individual. If `true`, the customer will be required to fill their full billing address and billing name.
	IsBusinessCustomer *bool `default:"false" json:"is_business_customer"`
	// ID of the customer in your system. If a matching customer exists on Polar, the resulting order will be linked to this customer. Otherwise, a new customer will be created with this external ID set.
	ExternalCustomerID     *string       `json:"external_customer_id,omitempty"`
	CustomerName           *string       `json:"customer_name,omitempty"`
	CustomerEmail          *string       `json:"customer_email,omitempty"`
	CustomerIPAddress      *string       `json:"customer_ip_address,omitempty"`
	CustomerBillingName    *string       `json:"customer_billing_name,omitempty"`
	CustomerBillingAddress *AddressInput `json:"customer_billing_address,omitempty"`
	CustomerTaxID          *string       `json:"customer_tax_id,omitempty"`
	// Key-value object allowing you to store additional information that'll be copied to the created customer.
	//
	// The key must be a string with a maximum length of **40 characters**.
	// The value must be either:
	//
	// * A string with a maximum length of **500 characters**
	// * An integer
	// * A floating-point number
	// * A boolean
	//
	// You can store up to **50 key-value pairs**.
	CustomerMetadata map[string]CheckoutCreateCustomerMetadata `json:"customer_metadata,omitempty"`
	// ID of a subscription to upgrade. It must be on a free pricing. If checkout is successful, metadata set on this checkout will be copied to the subscription, and existing keys will be overwritten.
	SubscriptionID *string `json:"subscription_id,omitempty"`
	// URL where the customer will be redirected after a successful payment.You can add the `checkout_id={CHECKOUT_ID}` query parameter to retrieve the checkout session id.
	SuccessURL *string `json:"success_url,omitempty"`
	// When set, a back button will be shown in the checkout to return to this URL.
	ReturnURL *string `json:"return_url,omitempty"`
	// If you plan to embed the checkout session, set this to the Origin of the embedding page. It'll allow the Polar iframe to communicate with the parent page.
	EmbedOrigin *string              `json:"embed_origin,omitempty"`
	Locale      *string              `json:"locale,omitempty"`
	Currency    *PresentmentCurrency `json:"currency,omitempty"`
	// List of product IDs available to select at that checkout. The first one will be selected by default.
	Products []string `json:"products"`
	// Optional mapping of product IDs to a list of ad-hoc prices to create for that product. If not set, catalog prices of the product will be used.
	Prices map[string][]CheckoutCreatePrices `json:"prices,omitempty"`
}

func (c CheckoutCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CheckoutCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CheckoutCreate) GetTrialInterval() *TrialInterval {
	if c == nil {
		return nil
	}
	return c.TrialInterval
}

func (c *CheckoutCreate) GetTrialIntervalCount() *int64 {
	if c == nil {
		return nil
	}
	return c.TrialIntervalCount
}

func (c *CheckoutCreate) GetMetadata() map[string]CheckoutCreateMetadata {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CheckoutCreate) GetCustomFieldData() map[string]*CheckoutCreateCustomFieldData {
	if c == nil {
		return nil
	}
	return c.CustomFieldData
}

func (c *CheckoutCreate) GetDiscountID() *string {
	if c == nil {
		return nil
	}
	return c.DiscountID
}

func (c *CheckoutCreate) GetAllowDiscountCodes() *bool {
	if c == nil {
		return nil
	}
	return c.AllowDiscountCodes
}

func (c *CheckoutCreate) GetRequireBillingAddress() *bool {
	if c == nil {
		return nil
	}
	return c.RequireBillingAddress
}

func (c *CheckoutCreate) GetAmount() *int64 {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CheckoutCreate) GetSeats() *int64 {
	if c == nil {
		return nil
	}
	return c.Seats
}

func (c *CheckoutCreate) GetMinSeats() *int64 {
	if c == nil {
		return nil
	}
	return c.MinSeats
}

func (c *CheckoutCreate) GetMaxSeats() *int64 {
	if c == nil {
		return nil
	}
	return c.MaxSeats
}

func (c *CheckoutCreate) GetAllowTrial() *bool {
	if c == nil {
		return nil
	}
	return c.AllowTrial
}

func (c *CheckoutCreate) GetCustomerID() *string {
	if c == nil {
		return nil
	}
	return c.CustomerID
}

func (c *CheckoutCreate) GetIsBusinessCustomer() *bool {
	if c == nil {
		return nil
	}
	return c.IsBusinessCustomer
}

func (c *CheckoutCreate) GetExternalCustomerID() *string {
	if c == nil {
		return nil
	}
	return c.ExternalCustomerID
}

func (c *CheckoutCreate) GetCustomerName() *string {
	if c == nil {
		return nil
	}
	return c.CustomerName
}

func (c *CheckoutCreate) GetCustomerEmail() *string {
	if c == nil {
		return nil
	}
	return c.CustomerEmail
}

func (c *CheckoutCreate) GetCustomerIPAddress() *string {
	if c == nil {
		return nil
	}
	return c.CustomerIPAddress
}

func (c *CheckoutCreate) GetCustomerBillingName() *string {
	if c == nil {
		return nil
	}
	return c.CustomerBillingName
}

func (c *CheckoutCreate) GetCustomerBillingAddress() *AddressInput {
	if c == nil {
		return nil
	}
	return c.CustomerBillingAddress
}

func (c *CheckoutCreate) GetCustomerTaxID() *string {
	if c == nil {
		return nil
	}
	return c.CustomerTaxID
}

func (c *CheckoutCreate) GetCustomerMetadata() map[string]CheckoutCreateCustomerMetadata {
	if c == nil {
		return nil
	}
	return c.CustomerMetadata
}

func (c *CheckoutCreate) GetSubscriptionID() *string {
	if c == nil {
		return nil
	}
	return c.SubscriptionID
}

func (c *CheckoutCreate) GetSuccessURL() *string {
	if c == nil {
		return nil
	}
	return c.SuccessURL
}

func (c *CheckoutCreate) GetReturnURL() *string {
	if c == nil {
		return nil
	}
	return c.ReturnURL
}

func (c *CheckoutCreate) GetEmbedOrigin() *string {
	if c == nil {
		return nil
	}
	return c.EmbedOrigin
}

func (c *CheckoutCreate) GetLocale() *string {
	if c == nil {
		return nil
	}
	return c.Locale
}

func (c *CheckoutCreate) GetCurrency() *PresentmentCurrency {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CheckoutCreate) GetProducts() []string {
	if c == nil {
		return []string{}
	}
	return c.Products
}

func (c *CheckoutCreate) GetPrices() map[string][]CheckoutCreatePrices {
	if c == nil {
		return nil
	}
	return c.Prices
}
