// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"polar/internal/utils"
	"time"
)

type CustomerBenefitGrantLicenseKeys struct {
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the object.
	ID             string                            `json:"id"`
	GrantedAt      *time.Time                        `json:"granted_at"`
	RevokedAt      *time.Time                        `json:"revoked_at"`
	CustomerID     string                            `json:"customer_id"`
	BenefitID      string                            `json:"benefit_id"`
	SubscriptionID *string                           `json:"subscription_id"`
	OrderID        *string                           `json:"order_id"`
	IsGranted      bool                              `json:"is_granted"`
	IsRevoked      bool                              `json:"is_revoked"`
	Benefit        BenefitLicenseKeysSubscriber      `json:"benefit"`
	Properties     BenefitGrantLicenseKeysProperties `json:"properties"`
}

func (c CustomerBenefitGrantLicenseKeys) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomerBenefitGrantLicenseKeys) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *CustomerBenefitGrantLicenseKeys) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *CustomerBenefitGrantLicenseKeys) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}

func (o *CustomerBenefitGrantLicenseKeys) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CustomerBenefitGrantLicenseKeys) GetGrantedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.GrantedAt
}

func (o *CustomerBenefitGrantLicenseKeys) GetRevokedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RevokedAt
}

func (o *CustomerBenefitGrantLicenseKeys) GetCustomerID() string {
	if o == nil {
		return ""
	}
	return o.CustomerID
}

func (o *CustomerBenefitGrantLicenseKeys) GetBenefitID() string {
	if o == nil {
		return ""
	}
	return o.BenefitID
}

func (o *CustomerBenefitGrantLicenseKeys) GetSubscriptionID() *string {
	if o == nil {
		return nil
	}
	return o.SubscriptionID
}

func (o *CustomerBenefitGrantLicenseKeys) GetOrderID() *string {
	if o == nil {
		return nil
	}
	return o.OrderID
}

func (o *CustomerBenefitGrantLicenseKeys) GetIsGranted() bool {
	if o == nil {
		return false
	}
	return o.IsGranted
}

func (o *CustomerBenefitGrantLicenseKeys) GetIsRevoked() bool {
	if o == nil {
		return false
	}
	return o.IsRevoked
}

func (o *CustomerBenefitGrantLicenseKeys) GetBenefit() BenefitLicenseKeysSubscriber {
	if o == nil {
		return BenefitLicenseKeysSubscriber{}
	}
	return o.Benefit
}

func (o *CustomerBenefitGrantLicenseKeys) GetProperties() BenefitGrantLicenseKeysProperties {
	if o == nil {
		return BenefitGrantLicenseKeysProperties{}
	}
	return o.Properties
}
