// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type CustomerWalletSortProperty string

const (
	CustomerWalletSortPropertyCreatedAt      CustomerWalletSortProperty = "created_at"
	CustomerWalletSortPropertyMinusCreatedAt CustomerWalletSortProperty = "-created_at"
	CustomerWalletSortPropertyBalance        CustomerWalletSortProperty = "balance"
	CustomerWalletSortPropertyMinusBalance   CustomerWalletSortProperty = "-balance"
)

func (e CustomerWalletSortProperty) ToPointer() *CustomerWalletSortProperty {
	return &e
}
func (e *CustomerWalletSortProperty) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "balance":
		fallthrough
	case "-balance":
		*e = CustomerWalletSortProperty(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomerWalletSortProperty: %v", v)
	}
}
