// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
	"github.com/polarsource/polar-go/types"
)

type CustomerIndividualCreateMetadataType string

const (
	CustomerIndividualCreateMetadataTypeStr     CustomerIndividualCreateMetadataType = "str"
	CustomerIndividualCreateMetadataTypeInteger CustomerIndividualCreateMetadataType = "integer"
	CustomerIndividualCreateMetadataTypeNumber  CustomerIndividualCreateMetadataType = "number"
	CustomerIndividualCreateMetadataTypeBoolean CustomerIndividualCreateMetadataType = "boolean"
)

type CustomerIndividualCreateMetadata struct {
	Str     *string  `queryParam:"inline" union:"member"`
	Integer *int64   `queryParam:"inline" union:"member"`
	Number  *float64 `queryParam:"inline" union:"member"`
	Boolean *bool    `queryParam:"inline" union:"member"`

	Type CustomerIndividualCreateMetadataType
}

func CreateCustomerIndividualCreateMetadataStr(str string) CustomerIndividualCreateMetadata {
	typ := CustomerIndividualCreateMetadataTypeStr

	return CustomerIndividualCreateMetadata{
		Str:  &str,
		Type: typ,
	}
}

func CreateCustomerIndividualCreateMetadataInteger(integer int64) CustomerIndividualCreateMetadata {
	typ := CustomerIndividualCreateMetadataTypeInteger

	return CustomerIndividualCreateMetadata{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateCustomerIndividualCreateMetadataNumber(number float64) CustomerIndividualCreateMetadata {
	typ := CustomerIndividualCreateMetadataTypeNumber

	return CustomerIndividualCreateMetadata{
		Number: &number,
		Type:   typ,
	}
}

func CreateCustomerIndividualCreateMetadataBoolean(boolean bool) CustomerIndividualCreateMetadata {
	typ := CustomerIndividualCreateMetadataTypeBoolean

	return CustomerIndividualCreateMetadata{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *CustomerIndividualCreateMetadata) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = CustomerIndividualCreateMetadataTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = CustomerIndividualCreateMetadataTypeInteger
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = CustomerIndividualCreateMetadataTypeNumber
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = CustomerIndividualCreateMetadataTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CustomerIndividualCreateMetadata", string(data))
}

func (u CustomerIndividualCreateMetadata) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type CustomerIndividualCreateMetadata: all fields are null")
}

type CustomerIndividualCreate struct {
	// Key-value object allowing you to store additional information.
	//
	// The key must be a string with a maximum length of **40 characters**.
	// The value must be either:
	//
	// * A string with a maximum length of **500 characters**
	// * An integer
	// * A floating-point number
	// * A boolean
	//
	// You can store up to **50 key-value pairs**.
	Metadata map[string]CustomerIndividualCreateMetadata `json:"metadata,omitempty"`
	// The ID of the customer in your system. This must be unique within the organization. Once set, it can't be updated.
	ExternalID     *string       `json:"external_id,omitempty"`
	Name           *string       `json:"name,omitempty"`
	BillingAddress *AddressInput `json:"billing_address,omitempty"`
	TaxID          *string       `json:"tax_id,omitempty"`
	Locale         *string       `json:"locale,omitempty"`
	// The ID of the organization owning the customer. **Required unless you use an organization token.**
	OrganizationID *string `json:"organization_id,omitempty"`
	// Optional owner member to create with the customer. If not provided, an owner member will be automatically created using the customer's email and name.
	Owner *MemberOwnerCreate `json:"owner,omitempty"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ *string `const:"individual" json:"type"`
	// The email address of the customer. This must be unique within the organization.
	Email string `json:"email"`
}

func (c CustomerIndividualCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomerIndividualCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"email"}); err != nil {
		return err
	}
	return nil
}

func (c *CustomerIndividualCreate) GetMetadata() map[string]CustomerIndividualCreateMetadata {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CustomerIndividualCreate) GetExternalID() *string {
	if c == nil {
		return nil
	}
	return c.ExternalID
}

func (c *CustomerIndividualCreate) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CustomerIndividualCreate) GetBillingAddress() *AddressInput {
	if c == nil {
		return nil
	}
	return c.BillingAddress
}

func (c *CustomerIndividualCreate) GetTaxID() *string {
	if c == nil {
		return nil
	}
	return c.TaxID
}

func (c *CustomerIndividualCreate) GetLocale() *string {
	if c == nil {
		return nil
	}
	return c.Locale
}

func (c *CustomerIndividualCreate) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CustomerIndividualCreate) GetOwner() *MemberOwnerCreate {
	if c == nil {
		return nil
	}
	return c.Owner
}

func (c *CustomerIndividualCreate) GetType() *string {
	return types.Pointer("individual")
}

func (c *CustomerIndividualCreate) GetEmail() string {
	if c == nil {
		return ""
	}
	return c.Email
}
