// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
)

type CustomerTeamCreateMetadataType string

const (
	CustomerTeamCreateMetadataTypeStr     CustomerTeamCreateMetadataType = "str"
	CustomerTeamCreateMetadataTypeInteger CustomerTeamCreateMetadataType = "integer"
	CustomerTeamCreateMetadataTypeNumber  CustomerTeamCreateMetadataType = "number"
	CustomerTeamCreateMetadataTypeBoolean CustomerTeamCreateMetadataType = "boolean"
)

type CustomerTeamCreateMetadata struct {
	Str     *string  `queryParam:"inline" union:"member"`
	Integer *int64   `queryParam:"inline" union:"member"`
	Number  *float64 `queryParam:"inline" union:"member"`
	Boolean *bool    `queryParam:"inline" union:"member"`

	Type CustomerTeamCreateMetadataType
}

func CreateCustomerTeamCreateMetadataStr(str string) CustomerTeamCreateMetadata {
	typ := CustomerTeamCreateMetadataTypeStr

	return CustomerTeamCreateMetadata{
		Str:  &str,
		Type: typ,
	}
}

func CreateCustomerTeamCreateMetadataInteger(integer int64) CustomerTeamCreateMetadata {
	typ := CustomerTeamCreateMetadataTypeInteger

	return CustomerTeamCreateMetadata{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateCustomerTeamCreateMetadataNumber(number float64) CustomerTeamCreateMetadata {
	typ := CustomerTeamCreateMetadataTypeNumber

	return CustomerTeamCreateMetadata{
		Number: &number,
		Type:   typ,
	}
}

func CreateCustomerTeamCreateMetadataBoolean(boolean bool) CustomerTeamCreateMetadata {
	typ := CustomerTeamCreateMetadataTypeBoolean

	return CustomerTeamCreateMetadata{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *CustomerTeamCreateMetadata) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = CustomerTeamCreateMetadataTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = CustomerTeamCreateMetadataTypeInteger
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = CustomerTeamCreateMetadataTypeNumber
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = CustomerTeamCreateMetadataTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CustomerTeamCreateMetadata", string(data))
}

func (u CustomerTeamCreateMetadata) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type CustomerTeamCreateMetadata: all fields are null")
}

type CustomerTeamCreate struct {
	// Key-value object allowing you to store additional information.
	//
	// The key must be a string with a maximum length of **40 characters**.
	// The value must be either:
	//
	// * A string with a maximum length of **500 characters**
	// * An integer
	// * A floating-point number
	// * A boolean
	//
	// You can store up to **50 key-value pairs**.
	Metadata map[string]CustomerTeamCreateMetadata `json:"metadata,omitempty"`
	// The ID of the customer in your system. This must be unique within the organization. Once set, it can't be updated.
	ExternalID     *string       `json:"external_id,omitempty"`
	Name           *string       `json:"name,omitempty"`
	BillingAddress *AddressInput `json:"billing_address,omitempty"`
	TaxID          *string       `json:"tax_id,omitempty"`
	Locale         *string       `json:"locale,omitempty"`
	// The ID of the organization owning the customer. **Required unless you use an organization token.**
	OrganizationID *string `json:"organization_id,omitempty"`
	// Optional owner member to create with the customer. If not provided, an owner member will be automatically created using the customer's email and name.
	Owner *MemberOwnerCreate `json:"owner,omitempty"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"team" json:"type"`
	// The email address of the team customer. Optional for team customers — if omitted, an owner with an email must be provided.
	Email *string `json:"email,omitempty"`
}

func (c CustomerTeamCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomerTeamCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (c *CustomerTeamCreate) GetMetadata() map[string]CustomerTeamCreateMetadata {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CustomerTeamCreate) GetExternalID() *string {
	if c == nil {
		return nil
	}
	return c.ExternalID
}

func (c *CustomerTeamCreate) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CustomerTeamCreate) GetBillingAddress() *AddressInput {
	if c == nil {
		return nil
	}
	return c.BillingAddress
}

func (c *CustomerTeamCreate) GetTaxID() *string {
	if c == nil {
		return nil
	}
	return c.TaxID
}

func (c *CustomerTeamCreate) GetLocale() *string {
	if c == nil {
		return nil
	}
	return c.Locale
}

func (c *CustomerTeamCreate) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CustomerTeamCreate) GetOwner() *MemberOwnerCreate {
	if c == nil {
		return nil
	}
	return c.Owner
}

func (c *CustomerTeamCreate) GetType() string {
	return "team"
}

func (c *CustomerTeamCreate) GetEmail() *string {
	if c == nil {
		return nil
	}
	return c.Email
}
