// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"polar/internal/utils"
	"time"
)

type CustomerSubscription struct {
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the object.
	ID                 string                        `json:"id"`
	Amount             *int64                        `json:"amount"`
	Currency           *string                       `json:"currency"`
	RecurringInterval  SubscriptionRecurringInterval `json:"recurring_interval"`
	Status             SubscriptionStatus            `json:"status"`
	CurrentPeriodStart time.Time                     `json:"current_period_start"`
	CurrentPeriodEnd   *time.Time                    `json:"current_period_end"`
	CancelAtPeriodEnd  bool                          `json:"cancel_at_period_end"`
	StartedAt          *time.Time                    `json:"started_at"`
	EndedAt            *time.Time                    `json:"ended_at"`
	CustomerID         string                        `json:"customer_id"`
	ProductID          string                        `json:"product_id"`
	PriceID            string                        `json:"price_id"`
	DiscountID         *string                       `json:"discount_id"`
	CheckoutID         *string                       `json:"checkout_id"`
	// Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
	UserID  string                      `json:"user_id"`
	Product CustomerSubscriptionProduct `json:"product"`
	Price   ProductPrice                `json:"price"`
}

func (c CustomerSubscription) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomerSubscription) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CustomerSubscription) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *CustomerSubscription) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}

func (o *CustomerSubscription) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CustomerSubscription) GetAmount() *int64 {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *CustomerSubscription) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *CustomerSubscription) GetRecurringInterval() SubscriptionRecurringInterval {
	if o == nil {
		return SubscriptionRecurringInterval("")
	}
	return o.RecurringInterval
}

func (o *CustomerSubscription) GetStatus() SubscriptionStatus {
	if o == nil {
		return SubscriptionStatus("")
	}
	return o.Status
}

func (o *CustomerSubscription) GetCurrentPeriodStart() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CurrentPeriodStart
}

func (o *CustomerSubscription) GetCurrentPeriodEnd() *time.Time {
	if o == nil {
		return nil
	}
	return o.CurrentPeriodEnd
}

func (o *CustomerSubscription) GetCancelAtPeriodEnd() bool {
	if o == nil {
		return false
	}
	return o.CancelAtPeriodEnd
}

func (o *CustomerSubscription) GetStartedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.StartedAt
}

func (o *CustomerSubscription) GetEndedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndedAt
}

func (o *CustomerSubscription) GetCustomerID() string {
	if o == nil {
		return ""
	}
	return o.CustomerID
}

func (o *CustomerSubscription) GetProductID() string {
	if o == nil {
		return ""
	}
	return o.ProductID
}

func (o *CustomerSubscription) GetPriceID() string {
	if o == nil {
		return ""
	}
	return o.PriceID
}

func (o *CustomerSubscription) GetDiscountID() *string {
	if o == nil {
		return nil
	}
	return o.DiscountID
}

func (o *CustomerSubscription) GetCheckoutID() *string {
	if o == nil {
		return nil
	}
	return o.CheckoutID
}

func (o *CustomerSubscription) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

func (o *CustomerSubscription) GetProduct() CustomerSubscriptionProduct {
	if o == nil {
		return CustomerSubscriptionProduct{}
	}
	return o.Product
}

func (o *CustomerSubscription) GetPrice() ProductPrice {
	if o == nil {
		return ProductPrice{}
	}
	return o.Price
}
