// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type CustomerOrderSubscription struct {
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the object.
	ID string `json:"id"`
	// The amount of the subscription.
	Amount int64 `json:"amount"`
	// The currency of the subscription.
	Currency          string                        `json:"currency"`
	RecurringInterval SubscriptionRecurringInterval `json:"recurring_interval"`
	Status            SubscriptionStatus            `json:"status"`
	// The start timestamp of the current billing period.
	CurrentPeriodStart time.Time `json:"current_period_start"`
	// The end timestamp of the current billing period.
	CurrentPeriodEnd *time.Time `json:"current_period_end"`
	// Whether the subscription will be canceled at the end of the current period.
	CancelAtPeriodEnd bool `json:"cancel_at_period_end"`
	// The timestamp when the subscription was canceled. The subscription might still be active if `cancel_at_period_end` is `true`.
	CanceledAt *time.Time `json:"canceled_at"`
	// The timestamp when the subscription started.
	StartedAt *time.Time `json:"started_at"`
	// The timestamp when the subscription will end.
	EndsAt *time.Time `json:"ends_at"`
	// The timestamp when the subscription ended.
	EndedAt *time.Time `json:"ended_at"`
	// The ID of the subscribed customer.
	CustomerID string `json:"customer_id"`
	// The ID of the subscribed product.
	ProductID string `json:"product_id"`
	// The ID of the applied discount, if any.
	DiscountID                  *string                     `json:"discount_id"`
	CheckoutID                  *string                     `json:"checkout_id"`
	CustomerCancellationReason  *CustomerCancellationReason `json:"customer_cancellation_reason"`
	CustomerCancellationComment *string                     `json:"customer_cancellation_comment"`
}

func (c CustomerOrderSubscription) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomerOrderSubscription) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"created_at", "modified_at", "id", "amount", "currency", "recurring_interval", "status", "current_period_start", "current_period_end", "cancel_at_period_end", "canceled_at", "started_at", "ends_at", "ended_at", "customer_id", "product_id", "discount_id", "checkout_id", "customer_cancellation_reason", "customer_cancellation_comment"}); err != nil {
		return err
	}
	return nil
}

func (c *CustomerOrderSubscription) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CustomerOrderSubscription) GetModifiedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ModifiedAt
}

func (c *CustomerOrderSubscription) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CustomerOrderSubscription) GetAmount() int64 {
	if c == nil {
		return 0
	}
	return c.Amount
}

func (c *CustomerOrderSubscription) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *CustomerOrderSubscription) GetRecurringInterval() SubscriptionRecurringInterval {
	if c == nil {
		return SubscriptionRecurringInterval("")
	}
	return c.RecurringInterval
}

func (c *CustomerOrderSubscription) GetStatus() SubscriptionStatus {
	if c == nil {
		return SubscriptionStatus("")
	}
	return c.Status
}

func (c *CustomerOrderSubscription) GetCurrentPeriodStart() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CurrentPeriodStart
}

func (c *CustomerOrderSubscription) GetCurrentPeriodEnd() *time.Time {
	if c == nil {
		return nil
	}
	return c.CurrentPeriodEnd
}

func (c *CustomerOrderSubscription) GetCancelAtPeriodEnd() bool {
	if c == nil {
		return false
	}
	return c.CancelAtPeriodEnd
}

func (c *CustomerOrderSubscription) GetCanceledAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CanceledAt
}

func (c *CustomerOrderSubscription) GetStartedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartedAt
}

func (c *CustomerOrderSubscription) GetEndsAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndsAt
}

func (c *CustomerOrderSubscription) GetEndedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndedAt
}

func (c *CustomerOrderSubscription) GetCustomerID() string {
	if c == nil {
		return ""
	}
	return c.CustomerID
}

func (c *CustomerOrderSubscription) GetProductID() string {
	if c == nil {
		return ""
	}
	return c.ProductID
}

func (c *CustomerOrderSubscription) GetDiscountID() *string {
	if c == nil {
		return nil
	}
	return c.DiscountID
}

func (c *CustomerOrderSubscription) GetCheckoutID() *string {
	if c == nil {
		return nil
	}
	return c.CheckoutID
}

func (c *CustomerOrderSubscription) GetCustomerCancellationReason() *CustomerCancellationReason {
	if c == nil {
		return nil
	}
	return c.CustomerCancellationReason
}

func (c *CustomerOrderSubscription) GetCustomerCancellationComment() *string {
	if c == nil {
		return nil
	}
	return c.CustomerCancellationComment
}
