// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
)

type CustomerSubscriptionUpdateType string

const (
	CustomerSubscriptionUpdateTypeCustomerSubscriptionUpdateProduct CustomerSubscriptionUpdateType = "CustomerSubscriptionUpdateProduct"
	CustomerSubscriptionUpdateTypeCustomerSubscriptionCancel        CustomerSubscriptionUpdateType = "CustomerSubscriptionCancel"
)

type CustomerSubscriptionUpdate struct {
	CustomerSubscriptionUpdateProduct *CustomerSubscriptionUpdateProduct `queryParam:"inline" name:"CustomerSubscriptionUpdate"`
	CustomerSubscriptionCancel        *CustomerSubscriptionCancel        `queryParam:"inline" name:"CustomerSubscriptionUpdate"`

	Type CustomerSubscriptionUpdateType
}

func CreateCustomerSubscriptionUpdateCustomerSubscriptionUpdateProduct(customerSubscriptionUpdateProduct CustomerSubscriptionUpdateProduct) CustomerSubscriptionUpdate {
	typ := CustomerSubscriptionUpdateTypeCustomerSubscriptionUpdateProduct

	return CustomerSubscriptionUpdate{
		CustomerSubscriptionUpdateProduct: &customerSubscriptionUpdateProduct,
		Type:                              typ,
	}
}

func CreateCustomerSubscriptionUpdateCustomerSubscriptionCancel(customerSubscriptionCancel CustomerSubscriptionCancel) CustomerSubscriptionUpdate {
	typ := CustomerSubscriptionUpdateTypeCustomerSubscriptionCancel

	return CustomerSubscriptionUpdate{
		CustomerSubscriptionCancel: &customerSubscriptionCancel,
		Type:                       typ,
	}
}

func (u *CustomerSubscriptionUpdate) UnmarshalJSON(data []byte) error {

	var customerSubscriptionUpdateProduct CustomerSubscriptionUpdateProduct = CustomerSubscriptionUpdateProduct{}
	if err := utils.UnmarshalJSON(data, &customerSubscriptionUpdateProduct, "", true, nil); err == nil {
		u.CustomerSubscriptionUpdateProduct = &customerSubscriptionUpdateProduct
		u.Type = CustomerSubscriptionUpdateTypeCustomerSubscriptionUpdateProduct
		return nil
	}

	var customerSubscriptionCancel CustomerSubscriptionCancel = CustomerSubscriptionCancel{}
	if err := utils.UnmarshalJSON(data, &customerSubscriptionCancel, "", true, nil); err == nil {
		u.CustomerSubscriptionCancel = &customerSubscriptionCancel
		u.Type = CustomerSubscriptionUpdateTypeCustomerSubscriptionCancel
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CustomerSubscriptionUpdate", string(data))
}

func (u CustomerSubscriptionUpdate) MarshalJSON() ([]byte, error) {
	if u.CustomerSubscriptionUpdateProduct != nil {
		return utils.MarshalJSON(u.CustomerSubscriptionUpdateProduct, "", true)
	}

	if u.CustomerSubscriptionCancel != nil {
		return utils.MarshalJSON(u.CustomerSubscriptionCancel, "", true)
	}

	return nil, errors.New("could not marshal union type CustomerSubscriptionUpdate: all fields are null")
}
