// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CustomerSessionCustomerExternalIDCreate - Schema for creating a customer session using an external customer ID.
type CustomerSessionCustomerExternalIDCreate struct {
	// External ID of the customer to create a session for.
	ExternalCustomerID string `json:"external_customer_id"`
}

func (o *CustomerSessionCustomerExternalIDCreate) GetExternalCustomerID() string {
	if o == nil {
		return ""
	}
	return o.ExternalCustomerID
}
