// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
)

type CustomFieldUpdateCheckboxMetadataType string

const (
	CustomFieldUpdateCheckboxMetadataTypeStr     CustomFieldUpdateCheckboxMetadataType = "str"
	CustomFieldUpdateCheckboxMetadataTypeInteger CustomFieldUpdateCheckboxMetadataType = "integer"
	CustomFieldUpdateCheckboxMetadataTypeBoolean CustomFieldUpdateCheckboxMetadataType = "boolean"
)

type CustomFieldUpdateCheckboxMetadata struct {
	Str     *string `queryParam:"inline"`
	Integer *int64  `queryParam:"inline"`
	Boolean *bool   `queryParam:"inline"`

	Type CustomFieldUpdateCheckboxMetadataType
}

func CreateCustomFieldUpdateCheckboxMetadataStr(str string) CustomFieldUpdateCheckboxMetadata {
	typ := CustomFieldUpdateCheckboxMetadataTypeStr

	return CustomFieldUpdateCheckboxMetadata{
		Str:  &str,
		Type: typ,
	}
}

func CreateCustomFieldUpdateCheckboxMetadataInteger(integer int64) CustomFieldUpdateCheckboxMetadata {
	typ := CustomFieldUpdateCheckboxMetadataTypeInteger

	return CustomFieldUpdateCheckboxMetadata{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateCustomFieldUpdateCheckboxMetadataBoolean(boolean bool) CustomFieldUpdateCheckboxMetadata {
	typ := CustomFieldUpdateCheckboxMetadataTypeBoolean

	return CustomFieldUpdateCheckboxMetadata{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *CustomFieldUpdateCheckboxMetadata) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = &str
		u.Type = CustomFieldUpdateCheckboxMetadataTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, true); err == nil {
		u.Integer = &integer
		u.Type = CustomFieldUpdateCheckboxMetadataTypeInteger
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, true); err == nil {
		u.Boolean = &boolean
		u.Type = CustomFieldUpdateCheckboxMetadataTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CustomFieldUpdateCheckboxMetadata", string(data))
}

func (u CustomFieldUpdateCheckboxMetadata) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type CustomFieldUpdateCheckboxMetadata: all fields are null")
}

// CustomFieldUpdateCheckbox - Schema to update a custom field of type checkbox.
type CustomFieldUpdateCheckbox struct {
	Metadata   map[string]CustomFieldUpdateCheckboxMetadata `json:"metadata,omitempty"`
	Name       *string                                      `json:"name,omitempty"`
	Slug       *string                                      `json:"slug,omitempty"`
	type_      string                                       `const:"checkbox" json:"type"`
	Properties *CustomFieldCheckboxProperties               `json:"properties,omitempty"`
}

func (c CustomFieldUpdateCheckbox) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomFieldUpdateCheckbox) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CustomFieldUpdateCheckbox) GetMetadata() map[string]CustomFieldUpdateCheckboxMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *CustomFieldUpdateCheckbox) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CustomFieldUpdateCheckbox) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *CustomFieldUpdateCheckbox) GetType() string {
	return "checkbox"
}

func (o *CustomFieldUpdateCheckbox) GetProperties() *CustomFieldCheckboxProperties {
	if o == nil {
		return nil
	}
	return o.Properties
}
