// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
)

type CustomerPaymentMethodCreateSucceededResponseOutput struct {
	status        string                `const:"succeeded" json:"status"`
	PaymentMethod CustomerPaymentMethod `json:"payment_method"`
}

func (c CustomerPaymentMethodCreateSucceededResponseOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomerPaymentMethodCreateSucceededResponseOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"status", "payment_method"}); err != nil {
		return err
	}
	return nil
}

func (c *CustomerPaymentMethodCreateSucceededResponseOutput) GetStatus() string {
	return "succeeded"
}

func (c *CustomerPaymentMethodCreateSucceededResponseOutput) GetPaymentMethod() CustomerPaymentMethod {
	if c == nil {
		return CustomerPaymentMethod{}
	}
	return c.PaymentMethod
}
