// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
)

type CustomerCreateMetadataType string

const (
	CustomerCreateMetadataTypeStr     CustomerCreateMetadataType = "str"
	CustomerCreateMetadataTypeInteger CustomerCreateMetadataType = "integer"
	CustomerCreateMetadataTypeNumber  CustomerCreateMetadataType = "number"
	CustomerCreateMetadataTypeBoolean CustomerCreateMetadataType = "boolean"
)

type CustomerCreateMetadata struct {
	Str     *string  `queryParam:"inline,name=metadata"`
	Integer *int64   `queryParam:"inline,name=metadata"`
	Number  *float64 `queryParam:"inline,name=metadata"`
	Boolean *bool    `queryParam:"inline,name=metadata"`

	Type CustomerCreateMetadataType
}

func CreateCustomerCreateMetadataStr(str string) CustomerCreateMetadata {
	typ := CustomerCreateMetadataTypeStr

	return CustomerCreateMetadata{
		Str:  &str,
		Type: typ,
	}
}

func CreateCustomerCreateMetadataInteger(integer int64) CustomerCreateMetadata {
	typ := CustomerCreateMetadataTypeInteger

	return CustomerCreateMetadata{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateCustomerCreateMetadataNumber(number float64) CustomerCreateMetadata {
	typ := CustomerCreateMetadataTypeNumber

	return CustomerCreateMetadata{
		Number: &number,
		Type:   typ,
	}
}

func CreateCustomerCreateMetadataBoolean(boolean bool) CustomerCreateMetadata {
	typ := CustomerCreateMetadataTypeBoolean

	return CustomerCreateMetadata{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *CustomerCreateMetadata) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = CustomerCreateMetadataTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = CustomerCreateMetadataTypeInteger
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = CustomerCreateMetadataTypeNumber
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = CustomerCreateMetadataTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CustomerCreateMetadata", string(data))
}

func (u CustomerCreateMetadata) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type CustomerCreateMetadata: all fields are null")
}

type CustomerCreateTaxIDType string

const (
	CustomerCreateTaxIDTypeStr         CustomerCreateTaxIDType = "str"
	CustomerCreateTaxIDTypeTaxIDFormat CustomerCreateTaxIDType = "TaxIDFormat"
)

type CustomerCreateTaxID struct {
	Str         *string      `queryParam:"inline,name=tax_id"`
	TaxIDFormat *TaxIDFormat `queryParam:"inline,name=tax_id"`

	Type CustomerCreateTaxIDType
}

func CreateCustomerCreateTaxIDStr(str string) CustomerCreateTaxID {
	typ := CustomerCreateTaxIDTypeStr

	return CustomerCreateTaxID{
		Str:  &str,
		Type: typ,
	}
}

func CreateCustomerCreateTaxIDTaxIDFormat(taxIDFormat TaxIDFormat) CustomerCreateTaxID {
	typ := CustomerCreateTaxIDTypeTaxIDFormat

	return CustomerCreateTaxID{
		TaxIDFormat: &taxIDFormat,
		Type:        typ,
	}
}

func (u *CustomerCreateTaxID) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = CustomerCreateTaxIDTypeStr
		return nil
	}

	var taxIDFormat TaxIDFormat = TaxIDFormat("")
	if err := utils.UnmarshalJSON(data, &taxIDFormat, "", true, nil); err == nil {
		u.TaxIDFormat = &taxIDFormat
		u.Type = CustomerCreateTaxIDTypeTaxIDFormat
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CustomerCreateTaxID", string(data))
}

func (u CustomerCreateTaxID) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.TaxIDFormat != nil {
		return utils.MarshalJSON(u.TaxIDFormat, "", true)
	}

	return nil, errors.New("could not marshal union type CustomerCreateTaxID: all fields are null")
}

type CustomerCreate struct {
	// Key-value object allowing you to store additional information.
	//
	// The key must be a string with a maximum length of **40 characters**.
	// The value must be either:
	//
	// * A string with a maximum length of **500 characters**
	// * An integer
	// * A floating-point number
	// * A boolean
	//
	// You can store up to **50 key-value pairs**.
	Metadata map[string]CustomerCreateMetadata `json:"metadata,omitempty"`
	// The ID of the customer in your system. This must be unique within the organization. Once set, it can't be updated.
	ExternalID *string `json:"external_id,omitempty"`
	// The email address of the customer. This must be unique within the organization.
	Email string `json:"email"`
	// The name of the customer.
	Name           *string                `json:"name,omitempty"`
	BillingAddress *AddressInput          `json:"billing_address,omitempty"`
	TaxID          []*CustomerCreateTaxID `json:"tax_id,omitempty"`
	// The ID of the organization owning the customer. **Required unless you use an organization token.**
	OrganizationID *string `json:"organization_id,omitempty"`
}

func (c *CustomerCreate) GetMetadata() map[string]CustomerCreateMetadata {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CustomerCreate) GetExternalID() *string {
	if c == nil {
		return nil
	}
	return c.ExternalID
}

func (c *CustomerCreate) GetEmail() string {
	if c == nil {
		return ""
	}
	return c.Email
}

func (c *CustomerCreate) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CustomerCreate) GetBillingAddress() *AddressInput {
	if c == nil {
		return nil
	}
	return c.BillingAddress
}

func (c *CustomerCreate) GetTaxID() []*CustomerCreateTaxID {
	if c == nil {
		return nil
	}
	return c.TaxID
}

func (c *CustomerCreate) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}
