// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

// CustomerPortalMember - A member of the customer's team as seen in the customer portal.
type CustomerPortalMember struct {
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the object.
	ID string `json:"id"`
	// The email address of the member.
	Email string `json:"email"`
	// The name of the member.
	Name *string    `json:"name"`
	Role MemberRole `json:"role"`
}

func (c CustomerPortalMember) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomerPortalMember) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomerPortalMember) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CustomerPortalMember) GetModifiedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ModifiedAt
}

func (c *CustomerPortalMember) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CustomerPortalMember) GetEmail() string {
	if c == nil {
		return ""
	}
	return c.Email
}

func (c *CustomerPortalMember) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CustomerPortalMember) GetRole() MemberRole {
	if c == nil {
		return MemberRole("")
	}
	return c.Role
}
