// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type DiscountFixedRepeatDurationMetadataType string

const (
	DiscountFixedRepeatDurationMetadataTypeStr     DiscountFixedRepeatDurationMetadataType = "str"
	DiscountFixedRepeatDurationMetadataTypeInteger DiscountFixedRepeatDurationMetadataType = "integer"
	DiscountFixedRepeatDurationMetadataTypeNumber  DiscountFixedRepeatDurationMetadataType = "number"
	DiscountFixedRepeatDurationMetadataTypeBoolean DiscountFixedRepeatDurationMetadataType = "boolean"
)

type DiscountFixedRepeatDurationMetadata struct {
	Str     *string  `queryParam:"inline" name:"metadata"`
	Integer *int64   `queryParam:"inline" name:"metadata"`
	Number  *float64 `queryParam:"inline" name:"metadata"`
	Boolean *bool    `queryParam:"inline" name:"metadata"`

	Type DiscountFixedRepeatDurationMetadataType
}

func CreateDiscountFixedRepeatDurationMetadataStr(str string) DiscountFixedRepeatDurationMetadata {
	typ := DiscountFixedRepeatDurationMetadataTypeStr

	return DiscountFixedRepeatDurationMetadata{
		Str:  &str,
		Type: typ,
	}
}

func CreateDiscountFixedRepeatDurationMetadataInteger(integer int64) DiscountFixedRepeatDurationMetadata {
	typ := DiscountFixedRepeatDurationMetadataTypeInteger

	return DiscountFixedRepeatDurationMetadata{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateDiscountFixedRepeatDurationMetadataNumber(number float64) DiscountFixedRepeatDurationMetadata {
	typ := DiscountFixedRepeatDurationMetadataTypeNumber

	return DiscountFixedRepeatDurationMetadata{
		Number: &number,
		Type:   typ,
	}
}

func CreateDiscountFixedRepeatDurationMetadataBoolean(boolean bool) DiscountFixedRepeatDurationMetadata {
	typ := DiscountFixedRepeatDurationMetadataTypeBoolean

	return DiscountFixedRepeatDurationMetadata{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *DiscountFixedRepeatDurationMetadata) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = DiscountFixedRepeatDurationMetadataTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = DiscountFixedRepeatDurationMetadataTypeInteger
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = DiscountFixedRepeatDurationMetadataTypeNumber
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = DiscountFixedRepeatDurationMetadataTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for DiscountFixedRepeatDurationMetadata", string(data))
}

func (u DiscountFixedRepeatDurationMetadata) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type DiscountFixedRepeatDurationMetadata: all fields are null")
}

// DiscountFixedRepeatDuration - Schema for a fixed amount discount that is applied on every invoice
// for a certain number of months.
type DiscountFixedRepeatDuration struct {
	Duration         DiscountDuration `json:"duration"`
	DurationInMonths int64            `json:"duration_in_months"`
	Type             DiscountType     `json:"type"`
	Amount           int64            `json:"amount"`
	Currency         string           `json:"currency"`
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the object.
	ID       string                                         `json:"id"`
	Metadata map[string]DiscountFixedRepeatDurationMetadata `json:"metadata"`
	// Name of the discount. Will be displayed to the customer when the discount is applied.
	Name string `json:"name"`
	// Code customers can use to apply the discount during checkout.
	Code *string `json:"code"`
	// Timestamp after which the discount is redeemable.
	StartsAt *time.Time `json:"starts_at"`
	// Timestamp after which the discount is no longer redeemable.
	EndsAt *time.Time `json:"ends_at"`
	// Maximum number of times the discount can be redeemed.
	MaxRedemptions *int64 `json:"max_redemptions"`
	// Number of times the discount has been redeemed.
	RedemptionsCount int64 `json:"redemptions_count"`
	// The organization ID.
	OrganizationID string            `json:"organization_id"`
	Products       []DiscountProduct `json:"products"`
}

func (d DiscountFixedRepeatDuration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DiscountFixedRepeatDuration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"duration", "duration_in_months", "type", "amount", "currency", "created_at", "modified_at", "id", "metadata", "name", "code", "starts_at", "ends_at", "max_redemptions", "redemptions_count", "organization_id", "products"}); err != nil {
		return err
	}
	return nil
}

func (d *DiscountFixedRepeatDuration) GetDuration() DiscountDuration {
	if d == nil {
		return DiscountDuration("")
	}
	return d.Duration
}

func (d *DiscountFixedRepeatDuration) GetDurationInMonths() int64 {
	if d == nil {
		return 0
	}
	return d.DurationInMonths
}

func (d *DiscountFixedRepeatDuration) GetType() DiscountType {
	if d == nil {
		return DiscountType("")
	}
	return d.Type
}

func (d *DiscountFixedRepeatDuration) GetAmount() int64 {
	if d == nil {
		return 0
	}
	return d.Amount
}

func (d *DiscountFixedRepeatDuration) GetCurrency() string {
	if d == nil {
		return ""
	}
	return d.Currency
}

func (d *DiscountFixedRepeatDuration) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}

func (d *DiscountFixedRepeatDuration) GetModifiedAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.ModifiedAt
}

func (d *DiscountFixedRepeatDuration) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DiscountFixedRepeatDuration) GetMetadata() map[string]DiscountFixedRepeatDurationMetadata {
	if d == nil {
		return map[string]DiscountFixedRepeatDurationMetadata{}
	}
	return d.Metadata
}

func (d *DiscountFixedRepeatDuration) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DiscountFixedRepeatDuration) GetCode() *string {
	if d == nil {
		return nil
	}
	return d.Code
}

func (d *DiscountFixedRepeatDuration) GetStartsAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.StartsAt
}

func (d *DiscountFixedRepeatDuration) GetEndsAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.EndsAt
}

func (d *DiscountFixedRepeatDuration) GetMaxRedemptions() *int64 {
	if d == nil {
		return nil
	}
	return d.MaxRedemptions
}

func (d *DiscountFixedRepeatDuration) GetRedemptionsCount() int64 {
	if d == nil {
		return 0
	}
	return d.RedemptionsCount
}

func (d *DiscountFixedRepeatDuration) GetOrganizationID() string {
	if d == nil {
		return ""
	}
	return d.OrganizationID
}

func (d *DiscountFixedRepeatDuration) GetProducts() []DiscountProduct {
	if d == nil {
		return []DiscountProduct{}
	}
	return d.Products
}
