// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
)

type DiscountCreateType string

const (
	DiscountCreateTypeFixed      DiscountCreateType = "fixed"
	DiscountCreateTypePercentage DiscountCreateType = "percentage"
)

type DiscountCreate struct {
	DiscountFixedCreate      *DiscountFixedCreate      `queryParam:"inline" union:"member"`
	DiscountPercentageCreate *DiscountPercentageCreate `queryParam:"inline" union:"member"`

	Type DiscountCreateType
}

func CreateDiscountCreateFixed(fixed DiscountFixedCreate) DiscountCreate {
	typ := DiscountCreateTypeFixed

	return DiscountCreate{
		DiscountFixedCreate: &fixed,
		Type:                typ,
	}
}

func CreateDiscountCreatePercentage(percentage DiscountPercentageCreate) DiscountCreate {
	typ := DiscountCreateTypePercentage

	return DiscountCreate{
		DiscountPercentageCreate: &percentage,
		Type:                     typ,
	}
}

func (u *DiscountCreate) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "fixed":
		discountFixedCreate := new(DiscountFixedCreate)
		if err := utils.UnmarshalJSON(data, &discountFixedCreate, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == fixed) type DiscountFixedCreate within DiscountCreate: %w", string(data), err)
		}

		u.DiscountFixedCreate = discountFixedCreate
		u.Type = DiscountCreateTypeFixed
		return nil
	case "percentage":
		discountPercentageCreate := new(DiscountPercentageCreate)
		if err := utils.UnmarshalJSON(data, &discountPercentageCreate, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == percentage) type DiscountPercentageCreate within DiscountCreate: %w", string(data), err)
		}

		u.DiscountPercentageCreate = discountPercentageCreate
		u.Type = DiscountCreateTypePercentage
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for DiscountCreate", string(data))
}

func (u DiscountCreate) MarshalJSON() ([]byte, error) {
	if u.DiscountFixedCreate != nil {
		return utils.MarshalJSON(u.DiscountFixedCreate, "", true)
	}

	if u.DiscountPercentageCreate != nil {
		return utils.MarshalJSON(u.DiscountPercentageCreate, "", true)
	}

	return nil, errors.New("could not marshal union type DiscountCreate: all fields are null")
}
