// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type DiscountPercentageOnceForeverDurationBase struct {
	Duration DiscountDuration `json:"duration"`
	Type     DiscountType     `json:"type"`
	// Discount percentage in basis points. A basis point is 1/100th of a percent. For example, 1000 basis points equals a 10% discount.
	BasisPoints int64 `json:"basis_points"`
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the object.
	ID       string                        `json:"id"`
	Metadata map[string]MetadataOutputType `json:"metadata"`
	// Name of the discount. Will be displayed to the customer when the discount is applied.
	Name string `json:"name"`
	// Code customers can use to apply the discount during checkout.
	Code *string `json:"code"`
	// Timestamp after which the discount is redeemable.
	StartsAt *time.Time `json:"starts_at"`
	// Timestamp after which the discount is no longer redeemable.
	EndsAt *time.Time `json:"ends_at"`
	// Maximum number of times the discount can be redeemed.
	MaxRedemptions *int64 `json:"max_redemptions"`
	// Number of times the discount has been redeemed.
	RedemptionsCount int64 `json:"redemptions_count"`
	// The organization ID.
	OrganizationID string `json:"organization_id"`
}

func (d DiscountPercentageOnceForeverDurationBase) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DiscountPercentageOnceForeverDurationBase) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"duration", "type", "basis_points", "created_at", "id", "metadata", "name", "redemptions_count", "organization_id"}); err != nil {
		return err
	}
	return nil
}

func (d *DiscountPercentageOnceForeverDurationBase) GetDuration() DiscountDuration {
	if d == nil {
		return DiscountDuration("")
	}
	return d.Duration
}

func (d *DiscountPercentageOnceForeverDurationBase) GetType() DiscountType {
	if d == nil {
		return DiscountType("")
	}
	return d.Type
}

func (d *DiscountPercentageOnceForeverDurationBase) GetBasisPoints() int64 {
	if d == nil {
		return 0
	}
	return d.BasisPoints
}

func (d *DiscountPercentageOnceForeverDurationBase) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}

func (d *DiscountPercentageOnceForeverDurationBase) GetModifiedAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.ModifiedAt
}

func (d *DiscountPercentageOnceForeverDurationBase) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DiscountPercentageOnceForeverDurationBase) GetMetadata() map[string]MetadataOutputType {
	if d == nil {
		return map[string]MetadataOutputType{}
	}
	return d.Metadata
}

func (d *DiscountPercentageOnceForeverDurationBase) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DiscountPercentageOnceForeverDurationBase) GetCode() *string {
	if d == nil {
		return nil
	}
	return d.Code
}

func (d *DiscountPercentageOnceForeverDurationBase) GetStartsAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.StartsAt
}

func (d *DiscountPercentageOnceForeverDurationBase) GetEndsAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.EndsAt
}

func (d *DiscountPercentageOnceForeverDurationBase) GetMaxRedemptions() *int64 {
	if d == nil {
		return nil
	}
	return d.MaxRedemptions
}

func (d *DiscountPercentageOnceForeverDurationBase) GetRedemptionsCount() int64 {
	if d == nil {
		return 0
	}
	return d.RedemptionsCount
}

func (d *DiscountPercentageOnceForeverDurationBase) GetOrganizationID() string {
	if d == nil {
		return ""
	}
	return d.OrganizationID
}
