// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"polar/internal/utils"
	"time"
)

type DiscountPercentageOnceForeverDurationMetadataType string

const (
	DiscountPercentageOnceForeverDurationMetadataTypeStr     DiscountPercentageOnceForeverDurationMetadataType = "str"
	DiscountPercentageOnceForeverDurationMetadataTypeInteger DiscountPercentageOnceForeverDurationMetadataType = "integer"
	DiscountPercentageOnceForeverDurationMetadataTypeBoolean DiscountPercentageOnceForeverDurationMetadataType = "boolean"
)

type DiscountPercentageOnceForeverDurationMetadata struct {
	Str     *string `queryParam:"inline"`
	Integer *int64  `queryParam:"inline"`
	Boolean *bool   `queryParam:"inline"`

	Type DiscountPercentageOnceForeverDurationMetadataType
}

func CreateDiscountPercentageOnceForeverDurationMetadataStr(str string) DiscountPercentageOnceForeverDurationMetadata {
	typ := DiscountPercentageOnceForeverDurationMetadataTypeStr

	return DiscountPercentageOnceForeverDurationMetadata{
		Str:  &str,
		Type: typ,
	}
}

func CreateDiscountPercentageOnceForeverDurationMetadataInteger(integer int64) DiscountPercentageOnceForeverDurationMetadata {
	typ := DiscountPercentageOnceForeverDurationMetadataTypeInteger

	return DiscountPercentageOnceForeverDurationMetadata{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateDiscountPercentageOnceForeverDurationMetadataBoolean(boolean bool) DiscountPercentageOnceForeverDurationMetadata {
	typ := DiscountPercentageOnceForeverDurationMetadataTypeBoolean

	return DiscountPercentageOnceForeverDurationMetadata{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *DiscountPercentageOnceForeverDurationMetadata) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = &str
		u.Type = DiscountPercentageOnceForeverDurationMetadataTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, true); err == nil {
		u.Integer = &integer
		u.Type = DiscountPercentageOnceForeverDurationMetadataTypeInteger
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, true); err == nil {
		u.Boolean = &boolean
		u.Type = DiscountPercentageOnceForeverDurationMetadataTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for DiscountPercentageOnceForeverDurationMetadata", string(data))
}

func (u DiscountPercentageOnceForeverDurationMetadata) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type DiscountPercentageOnceForeverDurationMetadata: all fields are null")
}

// DiscountPercentageOnceForeverDuration - Schema for a percentage discount that is applied once or forever.
type DiscountPercentageOnceForeverDuration struct {
	Duration    DiscountDuration `json:"duration"`
	Type        DiscountType     `json:"type"`
	BasisPoints int64            `json:"basis_points"`
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the object.
	ID       string                                                   `json:"id"`
	Metadata map[string]DiscountPercentageOnceForeverDurationMetadata `json:"metadata"`
	// Name of the discount. Will be displayed to the customer when the discount is applied.
	Name string `json:"name"`
	// Code customers can use to apply the discount during checkout.
	Code *string `json:"code"`
	// Timestamp after which the discount is redeemable.
	StartsAt *time.Time `json:"starts_at"`
	// Timestamp after which the discount is no longer redeemable.
	EndsAt *time.Time `json:"ends_at"`
	// Maximum number of times the discount can be redeemed.
	MaxRedemptions *int64 `json:"max_redemptions"`
	// Number of times the discount has been redeemed.
	RedemptionsCount int64 `json:"redemptions_count"`
	// The organization ID.
	OrganizationID string            `json:"organization_id"`
	Products       []DiscountProduct `json:"products"`
}

func (d DiscountPercentageOnceForeverDuration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DiscountPercentageOnceForeverDuration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *DiscountPercentageOnceForeverDuration) GetDuration() DiscountDuration {
	if o == nil {
		return DiscountDuration("")
	}
	return o.Duration
}

func (o *DiscountPercentageOnceForeverDuration) GetType() DiscountType {
	if o == nil {
		return DiscountType("")
	}
	return o.Type
}

func (o *DiscountPercentageOnceForeverDuration) GetBasisPoints() int64 {
	if o == nil {
		return 0
	}
	return o.BasisPoints
}

func (o *DiscountPercentageOnceForeverDuration) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *DiscountPercentageOnceForeverDuration) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}

func (o *DiscountPercentageOnceForeverDuration) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DiscountPercentageOnceForeverDuration) GetMetadata() map[string]DiscountPercentageOnceForeverDurationMetadata {
	if o == nil {
		return map[string]DiscountPercentageOnceForeverDurationMetadata{}
	}
	return o.Metadata
}

func (o *DiscountPercentageOnceForeverDuration) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DiscountPercentageOnceForeverDuration) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *DiscountPercentageOnceForeverDuration) GetStartsAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.StartsAt
}

func (o *DiscountPercentageOnceForeverDuration) GetEndsAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndsAt
}

func (o *DiscountPercentageOnceForeverDuration) GetMaxRedemptions() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxRedemptions
}

func (o *DiscountPercentageOnceForeverDuration) GetRedemptionsCount() int64 {
	if o == nil {
		return 0
	}
	return o.RedemptionsCount
}

func (o *DiscountPercentageOnceForeverDuration) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *DiscountPercentageOnceForeverDuration) GetProducts() []DiscountProduct {
	if o == nil {
		return []DiscountProduct{}
	}
	return o.Products
}
