// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
)

type EventType string

const (
	EventTypeSystemEvent EventType = "SystemEvent"
	EventTypeUserEvent   EventType = "UserEvent"
)

type Event struct {
	SystemEvent *SystemEvent `queryParam:"inline" name:"Event"`
	UserEvent   *UserEvent   `queryParam:"inline" name:"Event"`

	Type EventType
}

func CreateEventSystemEvent(systemEvent SystemEvent) Event {
	typ := EventTypeSystemEvent

	return Event{
		SystemEvent: &systemEvent,
		Type:        typ,
	}
}

func CreateEventUserEvent(userEvent UserEvent) Event {
	typ := EventTypeUserEvent

	return Event{
		UserEvent: &userEvent,
		Type:      typ,
	}
}

func (u *Event) UnmarshalJSON(data []byte) error {

	var userEvent UserEvent = UserEvent{}
	if err := utils.UnmarshalJSON(data, &userEvent, "", true, nil); err == nil {
		u.UserEvent = &userEvent
		u.Type = EventTypeUserEvent
		return nil
	}

	var systemEvent SystemEvent = SystemEvent{}
	if err := utils.UnmarshalJSON(data, &systemEvent, "", true, nil); err == nil {
		u.SystemEvent = &systemEvent
		u.Type = EventTypeSystemEvent
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Event", string(data))
}

func (u Event) MarshalJSON() ([]byte, error) {
	if u.SystemEvent != nil {
		return utils.MarshalJSON(u.SystemEvent, "", true)
	}

	if u.UserEvent != nil {
		return utils.MarshalJSON(u.UserEvent, "", true)
	}

	return nil, errors.New("could not marshal union type Event: all fields are null")
}
