// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
)

type ValueType string

const (
	ValueTypeStr     ValueType = "str"
	ValueTypeInteger ValueType = "integer"
	ValueTypeBoolean ValueType = "boolean"
)

type Value struct {
	Str     *string `queryParam:"inline"`
	Integer *int64  `queryParam:"inline"`
	Boolean *bool   `queryParam:"inline"`

	Type ValueType
}

func CreateValueStr(str string) Value {
	typ := ValueTypeStr

	return Value{
		Str:  &str,
		Type: typ,
	}
}

func CreateValueInteger(integer int64) Value {
	typ := ValueTypeInteger

	return Value{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateValueBoolean(boolean bool) Value {
	typ := ValueTypeBoolean

	return Value{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *Value) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, false); err == nil {
		u.Str = &str
		u.Type = ValueTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, false); err == nil {
		u.Integer = &integer
		u.Type = ValueTypeInteger
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, false); err == nil {
		u.Boolean = &boolean
		u.Type = ValueTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value", string(data))
}

func (u Value) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type Value: all fields are null")
}

type FilterClause struct {
	Property string         `json:"property"`
	Operator FilterOperator `json:"operator"`
	Value    Value          `json:"value"`
}

func (o *FilterClause) GetProperty() string {
	if o == nil {
		return ""
	}
	return o.Property
}

func (o *FilterClause) GetOperator() FilterOperator {
	if o == nil {
		return FilterOperator("")
	}
	return o.Operator
}

func (o *FilterClause) GetValue() Value {
	if o == nil {
		return Value{}
	}
	return o.Value
}
