// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type LicenseKeyUpdate struct {
	Status           *LicenseKeyStatus `json:"status,omitempty"`
	Usage            *int64            `default:"0" json:"usage"`
	LimitActivations *int64            `json:"limit_activations,omitempty"`
	LimitUsage       *int64            `json:"limit_usage,omitempty"`
	ExpiresAt        *time.Time        `json:"expires_at,omitempty"`
}

func (l LicenseKeyUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LicenseKeyUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LicenseKeyUpdate) GetStatus() *LicenseKeyStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *LicenseKeyUpdate) GetUsage() *int64 {
	if l == nil {
		return nil
	}
	return l.Usage
}

func (l *LicenseKeyUpdate) GetLimitActivations() *int64 {
	if l == nil {
		return nil
	}
	return l.LimitActivations
}

func (l *LicenseKeyUpdate) GetLimitUsage() *int64 {
	if l == nil {
		return nil
	}
	return l.LimitUsage
}

func (l *LicenseKeyUpdate) GetExpiresAt() *time.Time {
	if l == nil {
		return nil
	}
	return l.ExpiresAt
}
