// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type LicenseKeyRead struct {
	// The ID of the object.
	ID string `json:"id"`
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt     *time.Time         `json:"modified_at"`
	OrganizationID string             `json:"organization_id"`
	CustomerID     string             `json:"customer_id"`
	Customer       LicenseKeyCustomer `json:"customer"`
	// The benefit ID.
	BenefitID        string           `json:"benefit_id"`
	Key              string           `json:"key"`
	DisplayKey       string           `json:"display_key"`
	Status           LicenseKeyStatus `json:"status"`
	LimitActivations *int64           `json:"limit_activations"`
	Usage            int64            `json:"usage"`
	LimitUsage       *int64           `json:"limit_usage"`
	Validations      int64            `json:"validations"`
	LastValidatedAt  *time.Time       `json:"last_validated_at"`
	ExpiresAt        *time.Time       `json:"expires_at"`
}

func (l LicenseKeyRead) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LicenseKeyRead) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"id", "created_at", "modified_at", "organization_id", "customer_id", "customer", "benefit_id", "key", "display_key", "status", "limit_activations", "usage", "limit_usage", "validations", "last_validated_at", "expires_at"}); err != nil {
		return err
	}
	return nil
}

func (o *LicenseKeyRead) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *LicenseKeyRead) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *LicenseKeyRead) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}

func (o *LicenseKeyRead) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *LicenseKeyRead) GetCustomerID() string {
	if o == nil {
		return ""
	}
	return o.CustomerID
}

func (o *LicenseKeyRead) GetCustomer() LicenseKeyCustomer {
	if o == nil {
		return LicenseKeyCustomer{}
	}
	return o.Customer
}

func (o *LicenseKeyRead) GetBenefitID() string {
	if o == nil {
		return ""
	}
	return o.BenefitID
}

func (o *LicenseKeyRead) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *LicenseKeyRead) GetDisplayKey() string {
	if o == nil {
		return ""
	}
	return o.DisplayKey
}

func (o *LicenseKeyRead) GetStatus() LicenseKeyStatus {
	if o == nil {
		return LicenseKeyStatus("")
	}
	return o.Status
}

func (o *LicenseKeyRead) GetLimitActivations() *int64 {
	if o == nil {
		return nil
	}
	return o.LimitActivations
}

func (o *LicenseKeyRead) GetUsage() int64 {
	if o == nil {
		return 0
	}
	return o.Usage
}

func (o *LicenseKeyRead) GetLimitUsage() *int64 {
	if o == nil {
		return nil
	}
	return o.LimitUsage
}

func (o *LicenseKeyRead) GetValidations() int64 {
	if o == nil {
		return 0
	}
	return o.Validations
}

func (o *LicenseKeyRead) GetLastValidatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastValidatedAt
}

func (o *LicenseKeyRead) GetExpiresAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}
