// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceCustomerBenefitGrant struct {
	Items      []CustomerBenefitGrant `json:"items"`
	Pagination Pagination             `json:"pagination"`
}

func (l *ListResourceCustomerBenefitGrant) GetItems() []CustomerBenefitGrant {
	if l == nil {
		return []CustomerBenefitGrant{}
	}
	return l.Items
}

func (l *ListResourceCustomerBenefitGrant) GetPagination() Pagination {
	if l == nil {
		return Pagination{}
	}
	return l.Pagination
}
