// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MemberUpdate - Schema for updating a member.
type MemberUpdate struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
	// The role of the member within the customer.
	Role *MemberRole `json:"role,omitempty"`
}

func (m *MemberUpdate) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MemberUpdate) GetEmail() *string {
	if m == nil {
		return nil
	}
	return m.Email
}

func (m *MemberUpdate) GetRole() *MemberRole {
	if m == nil {
		return nil
	}
	return m.Role
}
