// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MeterQuantities struct {
	Quantities []MeterQuantity `json:"quantities"`
	// The total quantity for the period.
	Total float64 `json:"total"`
}

func (o *MeterQuantities) GetQuantities() []MeterQuantity {
	if o == nil {
		return []MeterQuantity{}
	}
	return o.Quantities
}

func (o *MeterQuantities) GetTotal() float64 {
	if o == nil {
		return 0.0
	}
	return o.Total
}
