// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

// MeterCreditEvent - An event created by Polar when credits are added to a customer meter.
type MeterCreditEvent struct {
	// The ID of the object.
	ID string `json:"id"`
	// The timestamp of the event.
	Timestamp time.Time `json:"timestamp"`
	// The ID of the organization owning the event.
	OrganizationID string `json:"organization_id"`
	// ID of the customer in your Polar organization associated with the event.
	CustomerID *string `json:"customer_id"`
	// The customer associated with the event.
	Customer *Customer `json:"customer"`
	// ID of the customer in your system associated with the event.
	ExternalCustomerID *string `json:"external_customer_id"`
	// The source of the event. `system` events are created by Polar. `user` events are the one you create through our ingestion API.
	source string `const:"system" json:"source"`
	// The name of the event.
	name     string                `const:"meter.credited" json:"name"`
	Metadata MeterCreditedMetadata `json:"metadata"`
}

func (m MeterCreditEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MeterCreditEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"id", "timestamp", "organization_id", "customer_id", "customer", "external_customer_id", "source", "name", "metadata"}); err != nil {
		return err
	}
	return nil
}

func (m *MeterCreditEvent) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *MeterCreditEvent) GetTimestamp() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.Timestamp
}

func (m *MeterCreditEvent) GetOrganizationID() string {
	if m == nil {
		return ""
	}
	return m.OrganizationID
}

func (m *MeterCreditEvent) GetCustomerID() *string {
	if m == nil {
		return nil
	}
	return m.CustomerID
}

func (m *MeterCreditEvent) GetCustomer() *Customer {
	if m == nil {
		return nil
	}
	return m.Customer
}

func (m *MeterCreditEvent) GetExternalCustomerID() *string {
	if m == nil {
		return nil
	}
	return m.ExternalCustomerID
}

func (m *MeterCreditEvent) GetSource() string {
	return "system"
}

func (m *MeterCreditEvent) GetName() string {
	return "meter.credited"
}

func (m *MeterCreditEvent) GetMetadata() MeterCreditedMetadata {
	if m == nil {
		return MeterCreditedMetadata{}
	}
	return m.Metadata
}
