// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MeterCreditedMetadata struct {
	MeterID  string `json:"meter_id"`
	Units    int64  `json:"units"`
	Rollover bool   `json:"rollover"`
}

func (o *MeterCreditedMetadata) GetMeterID() string {
	if o == nil {
		return ""
	}
	return o.MeterID
}

func (o *MeterCreditedMetadata) GetUnits() int64 {
	if o == nil {
		return 0
	}
	return o.Units
}

func (o *MeterCreditedMetadata) GetRollover() bool {
	if o == nil {
		return false
	}
	return o.Rollover
}
