// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type MeterMetadataType string

const (
	MeterMetadataTypeStr     MeterMetadataType = "str"
	MeterMetadataTypeInteger MeterMetadataType = "integer"
	MeterMetadataTypeNumber  MeterMetadataType = "number"
	MeterMetadataTypeBoolean MeterMetadataType = "boolean"
)

type MeterMetadata struct {
	Str     *string  `queryParam:"inline"`
	Integer *int64   `queryParam:"inline"`
	Number  *float64 `queryParam:"inline"`
	Boolean *bool    `queryParam:"inline"`

	Type MeterMetadataType
}

func CreateMeterMetadataStr(str string) MeterMetadata {
	typ := MeterMetadataTypeStr

	return MeterMetadata{
		Str:  &str,
		Type: typ,
	}
}

func CreateMeterMetadataInteger(integer int64) MeterMetadata {
	typ := MeterMetadataTypeInteger

	return MeterMetadata{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateMeterMetadataNumber(number float64) MeterMetadata {
	typ := MeterMetadataTypeNumber

	return MeterMetadata{
		Number: &number,
		Type:   typ,
	}
}

func CreateMeterMetadataBoolean(boolean bool) MeterMetadata {
	typ := MeterMetadataTypeBoolean

	return MeterMetadata{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *MeterMetadata) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = &str
		u.Type = MeterMetadataTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, true); err == nil {
		u.Integer = &integer
		u.Type = MeterMetadataTypeInteger
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, true); err == nil {
		u.Number = &number
		u.Type = MeterMetadataTypeNumber
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, true); err == nil {
		u.Boolean = &boolean
		u.Type = MeterMetadataTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for MeterMetadata", string(data))
}

func (u MeterMetadata) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type MeterMetadata: all fields are null")
}

type MeterAggregationType string

const (
	MeterAggregationTypeAvg   MeterAggregationType = "avg"
	MeterAggregationTypeCount MeterAggregationType = "count"
	MeterAggregationTypeMax   MeterAggregationType = "max"
	MeterAggregationTypeMin   MeterAggregationType = "min"
	MeterAggregationTypeSum   MeterAggregationType = "sum"
)

// MeterAggregation - The aggregation to apply on the filtered events to calculate the meter.
type MeterAggregation struct {
	CountAggregation    *CountAggregation    `queryParam:"inline"`
	PropertyAggregation *PropertyAggregation `queryParam:"inline"`

	Type MeterAggregationType
}

func CreateMeterAggregationAvg(avg PropertyAggregation) MeterAggregation {
	typ := MeterAggregationTypeAvg

	typStr := Func(typ)
	avg.Func = typStr

	return MeterAggregation{
		PropertyAggregation: &avg,
		Type:                typ,
	}
}

func CreateMeterAggregationCount(count CountAggregation) MeterAggregation {
	typ := MeterAggregationTypeCount

	return MeterAggregation{
		CountAggregation: &count,
		Type:             typ,
	}
}

func CreateMeterAggregationMax(max PropertyAggregation) MeterAggregation {
	typ := MeterAggregationTypeMax

	typStr := Func(typ)
	max.Func = typStr

	return MeterAggregation{
		PropertyAggregation: &max,
		Type:                typ,
	}
}

func CreateMeterAggregationMin(min PropertyAggregation) MeterAggregation {
	typ := MeterAggregationTypeMin

	typStr := Func(typ)
	min.Func = typStr

	return MeterAggregation{
		PropertyAggregation: &min,
		Type:                typ,
	}
}

func CreateMeterAggregationSum(sum PropertyAggregation) MeterAggregation {
	typ := MeterAggregationTypeSum

	typStr := Func(typ)
	sum.Func = typStr

	return MeterAggregation{
		PropertyAggregation: &sum,
		Type:                typ,
	}
}

func (u *MeterAggregation) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Func string `json:"func"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Func {
	case "avg":
		propertyAggregation := new(PropertyAggregation)
		if err := utils.UnmarshalJSON(data, &propertyAggregation, "", true, false); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Func == avg) type PropertyAggregation within MeterAggregation: %w", string(data), err)
		}

		u.PropertyAggregation = propertyAggregation
		u.Type = MeterAggregationTypeAvg
		return nil
	case "count":
		countAggregation := new(CountAggregation)
		if err := utils.UnmarshalJSON(data, &countAggregation, "", true, false); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Func == count) type CountAggregation within MeterAggregation: %w", string(data), err)
		}

		u.CountAggregation = countAggregation
		u.Type = MeterAggregationTypeCount
		return nil
	case "max":
		propertyAggregation := new(PropertyAggregation)
		if err := utils.UnmarshalJSON(data, &propertyAggregation, "", true, false); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Func == max) type PropertyAggregation within MeterAggregation: %w", string(data), err)
		}

		u.PropertyAggregation = propertyAggregation
		u.Type = MeterAggregationTypeMax
		return nil
	case "min":
		propertyAggregation := new(PropertyAggregation)
		if err := utils.UnmarshalJSON(data, &propertyAggregation, "", true, false); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Func == min) type PropertyAggregation within MeterAggregation: %w", string(data), err)
		}

		u.PropertyAggregation = propertyAggregation
		u.Type = MeterAggregationTypeMin
		return nil
	case "sum":
		propertyAggregation := new(PropertyAggregation)
		if err := utils.UnmarshalJSON(data, &propertyAggregation, "", true, false); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Func == sum) type PropertyAggregation within MeterAggregation: %w", string(data), err)
		}

		u.PropertyAggregation = propertyAggregation
		u.Type = MeterAggregationTypeSum
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for MeterAggregation", string(data))
}

func (u MeterAggregation) MarshalJSON() ([]byte, error) {
	if u.CountAggregation != nil {
		return utils.MarshalJSON(u.CountAggregation, "", true)
	}

	if u.PropertyAggregation != nil {
		return utils.MarshalJSON(u.PropertyAggregation, "", true)
	}

	return nil, errors.New("could not marshal union type MeterAggregation: all fields are null")
}

type Meter struct {
	Metadata map[string]MeterMetadata `json:"metadata"`
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the object.
	ID string `json:"id"`
	// The name of the meter. Will be shown on customer's invoices and usage.
	Name   string `json:"name"`
	Filter Filter `json:"filter"`
	// The aggregation to apply on the filtered events to calculate the meter.
	Aggregation MeterAggregation `json:"aggregation"`
	// The ID of the organization owning the meter.
	OrganizationID string `json:"organization_id"`
}

func (m Meter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Meter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Meter) GetMetadata() map[string]MeterMetadata {
	if o == nil {
		return map[string]MeterMetadata{}
	}
	return o.Metadata
}

func (o *Meter) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Meter) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}

func (o *Meter) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Meter) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Meter) GetFilter() Filter {
	if o == nil {
		return Filter{}
	}
	return o.Filter
}

func (o *Meter) GetAggregation() MeterAggregation {
	if o == nil {
		return MeterAggregation{}
	}
	return o.Aggregation
}

func (o *Meter) GetAggregationAvg() *PropertyAggregation {
	return o.GetAggregation().PropertyAggregation
}

func (o *Meter) GetAggregationCount() *CountAggregation {
	return o.GetAggregation().CountAggregation
}

func (o *Meter) GetAggregationMax() *PropertyAggregation {
	return o.GetAggregation().PropertyAggregation
}

func (o *Meter) GetAggregationMin() *PropertyAggregation {
	return o.GetAggregation().PropertyAggregation
}

func (o *Meter) GetAggregationSum() *PropertyAggregation {
	return o.GetAggregation().PropertyAggregation
}

func (o *Meter) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}
