// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"polar/internal/utils"
	"time"
)

type OrganizationAvatarFileReadService string

const (
	OrganizationAvatarFileReadServiceOrganizationAvatar OrganizationAvatarFileReadService = "organization_avatar"
)

func (e OrganizationAvatarFileReadService) ToPointer() *OrganizationAvatarFileReadService {
	return &e
}
func (e *OrganizationAvatarFileReadService) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "organization_avatar":
		*e = OrganizationAvatarFileReadService(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OrganizationAvatarFileReadService: %v", v)
	}
}

// OrganizationAvatarFileRead - File to be used as an organization avatar.
type OrganizationAvatarFileRead struct {
	// The ID of the object.
	ID                   string                            `json:"id"`
	OrganizationID       string                            `json:"organization_id"`
	Name                 string                            `json:"name"`
	Path                 string                            `json:"path"`
	MimeType             string                            `json:"mime_type"`
	Size                 int64                             `json:"size"`
	StorageVersion       *string                           `json:"storage_version"`
	ChecksumEtag         *string                           `json:"checksum_etag"`
	ChecksumSha256Base64 *string                           `json:"checksum_sha256_base64"`
	ChecksumSha256Hex    *string                           `json:"checksum_sha256_hex"`
	LastModifiedAt       *time.Time                        `json:"last_modified_at"`
	Version              *string                           `json:"version"`
	service              OrganizationAvatarFileReadService `const:"organization_avatar" json:"service"`
	IsUploaded           bool                              `json:"is_uploaded"`
	CreatedAt            time.Time                         `json:"created_at"`
	SizeReadable         string                            `json:"size_readable"`
	PublicURL            string                            `json:"public_url"`
}

func (o OrganizationAvatarFileRead) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationAvatarFileRead) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationAvatarFileRead) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OrganizationAvatarFileRead) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *OrganizationAvatarFileRead) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OrganizationAvatarFileRead) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

func (o *OrganizationAvatarFileRead) GetMimeType() string {
	if o == nil {
		return ""
	}
	return o.MimeType
}

func (o *OrganizationAvatarFileRead) GetSize() int64 {
	if o == nil {
		return 0
	}
	return o.Size
}

func (o *OrganizationAvatarFileRead) GetStorageVersion() *string {
	if o == nil {
		return nil
	}
	return o.StorageVersion
}

func (o *OrganizationAvatarFileRead) GetChecksumEtag() *string {
	if o == nil {
		return nil
	}
	return o.ChecksumEtag
}

func (o *OrganizationAvatarFileRead) GetChecksumSha256Base64() *string {
	if o == nil {
		return nil
	}
	return o.ChecksumSha256Base64
}

func (o *OrganizationAvatarFileRead) GetChecksumSha256Hex() *string {
	if o == nil {
		return nil
	}
	return o.ChecksumSha256Hex
}

func (o *OrganizationAvatarFileRead) GetLastModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastModifiedAt
}

func (o *OrganizationAvatarFileRead) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *OrganizationAvatarFileRead) GetService() OrganizationAvatarFileReadService {
	return OrganizationAvatarFileReadServiceOrganizationAvatar
}

func (o *OrganizationAvatarFileRead) GetIsUploaded() bool {
	if o == nil {
		return false
	}
	return o.IsUploaded
}

func (o *OrganizationAvatarFileRead) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *OrganizationAvatarFileRead) GetSizeReadable() string {
	if o == nil {
		return ""
	}
	return o.SizeReadable
}

func (o *OrganizationAvatarFileRead) GetPublicURL() string {
	if o == nil {
		return ""
	}
	return o.PublicURL
}
