// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaymentMethodCardMetadata struct {
	Brand    string  `json:"brand"`
	Last4    string  `json:"last4"`
	ExpMonth int64   `json:"exp_month"`
	ExpYear  int64   `json:"exp_year"`
	Wallet   *string `json:"wallet,omitempty"`
}

func (o *PaymentMethodCardMetadata) GetBrand() string {
	if o == nil {
		return ""
	}
	return o.Brand
}

func (o *PaymentMethodCardMetadata) GetLast4() string {
	if o == nil {
		return ""
	}
	return o.Last4
}

func (o *PaymentMethodCardMetadata) GetExpMonth() int64 {
	if o == nil {
		return 0
	}
	return o.ExpMonth
}

func (o *PaymentMethodCardMetadata) GetExpYear() int64 {
	if o == nil {
		return 0
	}
	return o.ExpYear
}

func (o *PaymentMethodCardMetadata) GetWallet() *string {
	if o == nil {
		return nil
	}
	return o.Wallet
}
