// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

// ProductMediaFileRead - File to be used as a product media file.
type ProductMediaFileRead struct {
	// The ID of the object.
	ID                   string     `json:"id"`
	OrganizationID       string     `json:"organization_id"`
	Name                 string     `json:"name"`
	Path                 string     `json:"path"`
	MimeType             string     `json:"mime_type"`
	Size                 int64      `json:"size"`
	StorageVersion       *string    `json:"storage_version"`
	ChecksumEtag         *string    `json:"checksum_etag"`
	ChecksumSha256Base64 *string    `json:"checksum_sha256_base64"`
	ChecksumSha256Hex    *string    `json:"checksum_sha256_hex"`
	LastModifiedAt       *time.Time `json:"last_modified_at"`
	Version              *string    `json:"version"`
	service              string     `const:"product_media" json:"service"`
	IsUploaded           bool       `json:"is_uploaded"`
	CreatedAt            time.Time  `json:"created_at"`
	SizeReadable         string     `json:"size_readable"`
	PublicURL            string     `json:"public_url"`
}

func (p ProductMediaFileRead) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProductMediaFileRead) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"id", "organization_id", "name", "path", "mime_type", "size", "storage_version", "checksum_etag", "checksum_sha256_base64", "checksum_sha256_hex", "last_modified_at", "version", "service", "is_uploaded", "created_at", "size_readable", "public_url"}); err != nil {
		return err
	}
	return nil
}

func (p *ProductMediaFileRead) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *ProductMediaFileRead) GetOrganizationID() string {
	if p == nil {
		return ""
	}
	return p.OrganizationID
}

func (p *ProductMediaFileRead) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *ProductMediaFileRead) GetPath() string {
	if p == nil {
		return ""
	}
	return p.Path
}

func (p *ProductMediaFileRead) GetMimeType() string {
	if p == nil {
		return ""
	}
	return p.MimeType
}

func (p *ProductMediaFileRead) GetSize() int64 {
	if p == nil {
		return 0
	}
	return p.Size
}

func (p *ProductMediaFileRead) GetStorageVersion() *string {
	if p == nil {
		return nil
	}
	return p.StorageVersion
}

func (p *ProductMediaFileRead) GetChecksumEtag() *string {
	if p == nil {
		return nil
	}
	return p.ChecksumEtag
}

func (p *ProductMediaFileRead) GetChecksumSha256Base64() *string {
	if p == nil {
		return nil
	}
	return p.ChecksumSha256Base64
}

func (p *ProductMediaFileRead) GetChecksumSha256Hex() *string {
	if p == nil {
		return nil
	}
	return p.ChecksumSha256Hex
}

func (p *ProductMediaFileRead) GetLastModifiedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.LastModifiedAt
}

func (p *ProductMediaFileRead) GetVersion() *string {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *ProductMediaFileRead) GetService() string {
	return "product_media"
}

func (p *ProductMediaFileRead) GetIsUploaded() bool {
	if p == nil {
		return false
	}
	return p.IsUploaded
}

func (p *ProductMediaFileRead) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *ProductMediaFileRead) GetSizeReadable() string {
	if p == nil {
		return ""
	}
	return p.SizeReadable
}

func (p *ProductMediaFileRead) GetPublicURL() string {
	if p == nil {
		return ""
	}
	return p.PublicURL
}
