// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ProductPriceSource string

const (
	ProductPriceSourceCatalog ProductPriceSource = "catalog"
	ProductPriceSourceAdHoc   ProductPriceSource = "ad_hoc"
)

func (e ProductPriceSource) ToPointer() *ProductPriceSource {
	return &e
}
func (e *ProductPriceSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "catalog":
		fallthrough
	case "ad_hoc":
		*e = ProductPriceSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProductPriceSource: %v", v)
	}
}
