// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

// ProductPriceSeatBased - A seat-based price for a product.
type ProductPriceSeatBased struct {
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the price.
	ID         string `json:"id"`
	amountType string `const:"seat_based" json:"amount_type"`
	// Whether the price is archived and no longer available.
	IsArchived bool `json:"is_archived"`
	// The ID of the product owning the price.
	ProductID string           `json:"product_id"`
	Type      ProductPriceType `json:"type"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	RecurringInterval *SubscriptionRecurringInterval `json:"recurring_interval"`
	// The currency.
	PriceCurrency string `json:"price_currency"`
	// List of pricing tiers for seat-based pricing.
	SeatTiers ProductPriceSeatTiers `json:"seat_tiers"`
}

func (p ProductPriceSeatBased) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProductPriceSeatBased) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"created_at", "id", "amount_type", "is_archived", "product_id", "type", "price_currency", "seat_tiers"}); err != nil {
		return err
	}
	return nil
}

func (p *ProductPriceSeatBased) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *ProductPriceSeatBased) GetModifiedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.ModifiedAt
}

func (p *ProductPriceSeatBased) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *ProductPriceSeatBased) GetAmountType() string {
	return "seat_based"
}

func (p *ProductPriceSeatBased) GetIsArchived() bool {
	if p == nil {
		return false
	}
	return p.IsArchived
}

func (p *ProductPriceSeatBased) GetProductID() string {
	if p == nil {
		return ""
	}
	return p.ProductID
}

func (p *ProductPriceSeatBased) GetType() ProductPriceType {
	if p == nil {
		return ProductPriceType("")
	}
	return p.Type
}

func (p *ProductPriceSeatBased) GetRecurringInterval() *SubscriptionRecurringInterval {
	if p == nil {
		return nil
	}
	return p.RecurringInterval
}

func (p *ProductPriceSeatBased) GetPriceCurrency() string {
	if p == nil {
		return ""
	}
	return p.PriceCurrency
}

func (p *ProductPriceSeatBased) GetSeatTiers() ProductPriceSeatTiers {
	if p == nil {
		return ProductPriceSeatTiers{}
	}
	return p.SeatTiers
}
