// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

// ProductPriceFixedOutput - A fixed price for a product.
type ProductPriceFixedOutput struct {
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the price.
	ID         string `json:"id"`
	amountType string `const:"fixed" json:"amount_type"`
	// Whether the price is archived and no longer available.
	IsArchived bool `json:"is_archived"`
	// The ID of the product owning the price.
	ProductID string           `json:"product_id"`
	Type      ProductPriceType `json:"type"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	RecurringInterval *SubscriptionRecurringInterval `json:"recurring_interval"`
	// The currency.
	PriceCurrency string `json:"price_currency"`
	// The price in cents.
	PriceAmount int64 `json:"price_amount"`
}

func (p ProductPriceFixedOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProductPriceFixedOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"created_at", "id", "amount_type", "is_archived", "product_id", "type", "price_currency", "price_amount"}); err != nil {
		return err
	}
	return nil
}

func (p *ProductPriceFixedOutput) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *ProductPriceFixedOutput) GetModifiedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.ModifiedAt
}

func (p *ProductPriceFixedOutput) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *ProductPriceFixedOutput) GetAmountType() string {
	return "fixed"
}

func (p *ProductPriceFixedOutput) GetIsArchived() bool {
	if p == nil {
		return false
	}
	return p.IsArchived
}

func (p *ProductPriceFixedOutput) GetProductID() string {
	if p == nil {
		return ""
	}
	return p.ProductID
}

func (p *ProductPriceFixedOutput) GetType() ProductPriceType {
	if p == nil {
		return ProductPriceType("")
	}
	return p.Type
}

func (p *ProductPriceFixedOutput) GetRecurringInterval() *SubscriptionRecurringInterval {
	if p == nil {
		return nil
	}
	return p.RecurringInterval
}

func (p *ProductPriceFixedOutput) GetPriceCurrency() string {
	if p == nil {
		return ""
	}
	return p.PriceCurrency
}

func (p *ProductPriceFixedOutput) GetPriceAmount() int64 {
	if p == nil {
		return 0
	}
	return p.PriceAmount
}
