// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Func string

const (
	FuncSum Func = "sum"
	FuncMax Func = "max"
	FuncMin Func = "min"
	FuncAvg Func = "avg"
)

func (e Func) ToPointer() *Func {
	return &e
}
func (e *Func) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "sum":
		fallthrough
	case "max":
		fallthrough
	case "min":
		fallthrough
	case "avg":
		*e = Func(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Func: %v", v)
	}
}

type PropertyAggregation struct {
	Func     Func   `json:"func"`
	Property string `json:"property"`
}

func (o *PropertyAggregation) GetFunc() Func {
	if o == nil {
		return Func("")
	}
	return o.Func
}

func (o *PropertyAggregation) GetProperty() string {
	if o == nil {
		return ""
	}
	return o.Property
}
