// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type RefundSortProperty string

const (
	RefundSortPropertyCreatedAt      RefundSortProperty = "created_at"
	RefundSortPropertyMinusCreatedAt RefundSortProperty = "-created_at"
	RefundSortPropertyAmount         RefundSortProperty = "amount"
	RefundSortPropertyMinusAmount    RefundSortProperty = "-amount"
)

func (e RefundSortProperty) ToPointer() *RefundSortProperty {
	return &e
}
func (e *RefundSortProperty) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "amount":
		fallthrough
	case "-amount":
		*e = RefundSortProperty(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RefundSortProperty: %v", v)
	}
}
