// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

// SubscriptionCycledEvent - An event created by Polar when a subscription is cycled.
type SubscriptionCycledEvent struct {
	// The ID of the object.
	ID string `json:"id"`
	// The timestamp of the event.
	Timestamp time.Time `json:"timestamp"`
	// The ID of the organization owning the event.
	OrganizationID string `json:"organization_id"`
	// ID of the customer in your Polar organization associated with the event.
	CustomerID *string `json:"customer_id"`
	// The customer associated with the event.
	Customer *Customer `json:"customer"`
	// ID of the customer in your system associated with the event.
	ExternalCustomerID *string `json:"external_customer_id"`
	// The source of the event. `system` events are created by Polar. `user` events are the one you create through our ingestion API.
	source string `const:"system" json:"source"`
	// The name of the event.
	name     string                     `const:"subscription.cycled" json:"name"`
	Metadata SubscriptionCycledMetadata `json:"metadata"`
}

func (s SubscriptionCycledEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionCycledEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"id", "timestamp", "organization_id", "customer_id", "customer", "external_customer_id", "source", "name", "metadata"}); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionCycledEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SubscriptionCycledEvent) GetTimestamp() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.Timestamp
}

func (s *SubscriptionCycledEvent) GetOrganizationID() string {
	if s == nil {
		return ""
	}
	return s.OrganizationID
}

func (s *SubscriptionCycledEvent) GetCustomerID() *string {
	if s == nil {
		return nil
	}
	return s.CustomerID
}

func (s *SubscriptionCycledEvent) GetCustomer() *Customer {
	if s == nil {
		return nil
	}
	return s.Customer
}

func (s *SubscriptionCycledEvent) GetExternalCustomerID() *string {
	if s == nil {
		return nil
	}
	return s.ExternalCustomerID
}

func (s *SubscriptionCycledEvent) GetSource() string {
	return "system"
}

func (s *SubscriptionCycledEvent) GetName() string {
	return "subscription.cycled"
}

func (s *SubscriptionCycledEvent) GetMetadata() SubscriptionCycledMetadata {
	if s == nil {
		return SubscriptionCycledMetadata{}
	}
	return s.Metadata
}
