// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

// SubscriptionBillingPeriodUpdatedEvent - An event created by Polar when a subscription billing period is updated.
type SubscriptionBillingPeriodUpdatedEvent struct {
	// The ID of the object.
	ID string `json:"id"`
	// The timestamp of the event.
	Timestamp time.Time `json:"timestamp"`
	// The ID of the organization owning the event.
	OrganizationID string `json:"organization_id"`
	// ID of the customer in your Polar organization associated with the event.
	CustomerID *string `json:"customer_id"`
	// The customer associated with the event.
	Customer *Customer `json:"customer"`
	// ID of the customer in your system associated with the event.
	ExternalCustomerID *string `json:"external_customer_id"`
	// ID of the member within the customer's organization who performed the action inside B2B.
	MemberID *string `json:"member_id,omitempty"`
	// ID of the member in your system within the customer's organization who performed the action inside B2B.
	ExternalMemberID *string `json:"external_member_id,omitempty"`
	// Number of direct child events linked to this event.
	ChildCount *int64 `default:"0" json:"child_count"`
	// The ID of the parent event.
	ParentID *string `json:"parent_id,omitempty"`
	// Human readable label of the event type.
	Label string `json:"label"`
	// The source of the event. `system` events are created by Polar. `user` events are the one you create through our ingestion API.
	source string `const:"system" json:"source"`
	// The name of the event.
	name     string                                   `const:"subscription.billing_period_updated" json:"name"`
	Metadata SubscriptionBillingPeriodUpdatedMetadata `json:"metadata"`
}

func (s SubscriptionBillingPeriodUpdatedEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionBillingPeriodUpdatedEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"id", "timestamp", "organization_id", "label", "source", "name", "metadata"}); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionBillingPeriodUpdatedEvent) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SubscriptionBillingPeriodUpdatedEvent) GetTimestamp() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.Timestamp
}

func (s *SubscriptionBillingPeriodUpdatedEvent) GetOrganizationID() string {
	if s == nil {
		return ""
	}
	return s.OrganizationID
}

func (s *SubscriptionBillingPeriodUpdatedEvent) GetCustomerID() *string {
	if s == nil {
		return nil
	}
	return s.CustomerID
}

func (s *SubscriptionBillingPeriodUpdatedEvent) GetCustomer() *Customer {
	if s == nil {
		return nil
	}
	return s.Customer
}

func (s *SubscriptionBillingPeriodUpdatedEvent) GetExternalCustomerID() *string {
	if s == nil {
		return nil
	}
	return s.ExternalCustomerID
}

func (s *SubscriptionBillingPeriodUpdatedEvent) GetMemberID() *string {
	if s == nil {
		return nil
	}
	return s.MemberID
}

func (s *SubscriptionBillingPeriodUpdatedEvent) GetExternalMemberID() *string {
	if s == nil {
		return nil
	}
	return s.ExternalMemberID
}

func (s *SubscriptionBillingPeriodUpdatedEvent) GetChildCount() *int64 {
	if s == nil {
		return nil
	}
	return s.ChildCount
}

func (s *SubscriptionBillingPeriodUpdatedEvent) GetParentID() *string {
	if s == nil {
		return nil
	}
	return s.ParentID
}

func (s *SubscriptionBillingPeriodUpdatedEvent) GetLabel() string {
	if s == nil {
		return ""
	}
	return s.Label
}

func (s *SubscriptionBillingPeriodUpdatedEvent) GetSource() string {
	return "system"
}

func (s *SubscriptionBillingPeriodUpdatedEvent) GetName() string {
	return "subscription.billing_period_updated"
}

func (s *SubscriptionBillingPeriodUpdatedEvent) GetMetadata() SubscriptionBillingPeriodUpdatedMetadata {
	if s == nil {
		return SubscriptionBillingPeriodUpdatedMetadata{}
	}
	return s.Metadata
}
