// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
)

type SubscriptionSeatsUpdatedMetadata struct {
	SubscriptionID    string `json:"subscription_id"`
	OldSeats          int64  `json:"old_seats"`
	NewSeats          int64  `json:"new_seats"`
	ProrationBehavior string `json:"proration_behavior"`
}

func (s SubscriptionSeatsUpdatedMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionSeatsUpdatedMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"subscription_id", "old_seats", "new_seats", "proration_behavior"}); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionSeatsUpdatedMetadata) GetSubscriptionID() string {
	if s == nil {
		return ""
	}
	return s.SubscriptionID
}

func (s *SubscriptionSeatsUpdatedMetadata) GetOldSeats() int64 {
	if s == nil {
		return 0
	}
	return s.OldSeats
}

func (s *SubscriptionSeatsUpdatedMetadata) GetNewSeats() int64 {
	if s == nil {
		return 0
	}
	return s.NewSeats
}

func (s *SubscriptionSeatsUpdatedMetadata) GetProrationBehavior() string {
	if s == nil {
		return ""
	}
	return s.ProrationBehavior
}
