// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type CustomFieldDataType string

const (
	CustomFieldDataTypeStr      CustomFieldDataType = "str"
	CustomFieldDataTypeInteger  CustomFieldDataType = "integer"
	CustomFieldDataTypeBoolean  CustomFieldDataType = "boolean"
	CustomFieldDataTypeDateTime CustomFieldDataType = "date-time"
)

type CustomFieldData struct {
	Str      *string    `queryParam:"inline" union:"member"`
	Integer  *int64     `queryParam:"inline" union:"member"`
	Boolean  *bool      `queryParam:"inline" union:"member"`
	DateTime *time.Time `queryParam:"inline" union:"member"`

	Type CustomFieldDataType
}

func CreateCustomFieldDataStr(str string) CustomFieldData {
	typ := CustomFieldDataTypeStr

	return CustomFieldData{
		Str:  &str,
		Type: typ,
	}
}

func CreateCustomFieldDataInteger(integer int64) CustomFieldData {
	typ := CustomFieldDataTypeInteger

	return CustomFieldData{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateCustomFieldDataBoolean(boolean bool) CustomFieldData {
	typ := CustomFieldDataTypeBoolean

	return CustomFieldData{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateCustomFieldDataDateTime(dateTime time.Time) CustomFieldData {
	typ := CustomFieldDataTypeDateTime

	return CustomFieldData{
		DateTime: &dateTime,
		Type:     typ,
	}
}

func (u *CustomFieldData) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = CustomFieldDataTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = CustomFieldDataTypeInteger
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = CustomFieldDataTypeBoolean
		return nil
	}

	var dateTime time.Time = time.Time{}
	if err := utils.UnmarshalJSON(data, &dateTime, "", true, nil); err == nil {
		u.DateTime = &dateTime
		u.Type = CustomFieldDataTypeDateTime
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CustomFieldData", string(data))
}

func (u CustomFieldData) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.DateTime != nil {
		return utils.MarshalJSON(u.DateTime, "", true)
	}

	return nil, errors.New("could not marshal union type CustomFieldData: all fields are null")
}

type SubscriptionDiscountType string

const (
	SubscriptionDiscountTypeDiscountFixedOnceForeverDurationBase      SubscriptionDiscountType = "DiscountFixedOnceForeverDurationBase"
	SubscriptionDiscountTypeDiscountFixedRepeatDurationBase           SubscriptionDiscountType = "DiscountFixedRepeatDurationBase"
	SubscriptionDiscountTypeDiscountPercentageOnceForeverDurationBase SubscriptionDiscountType = "DiscountPercentageOnceForeverDurationBase"
	SubscriptionDiscountTypeDiscountPercentageRepeatDurationBase      SubscriptionDiscountType = "DiscountPercentageRepeatDurationBase"
)

type SubscriptionDiscount struct {
	DiscountFixedOnceForeverDurationBase      *DiscountFixedOnceForeverDurationBase      `queryParam:"inline" union:"member"`
	DiscountFixedRepeatDurationBase           *DiscountFixedRepeatDurationBase           `queryParam:"inline" union:"member"`
	DiscountPercentageOnceForeverDurationBase *DiscountPercentageOnceForeverDurationBase `queryParam:"inline" union:"member"`
	DiscountPercentageRepeatDurationBase      *DiscountPercentageRepeatDurationBase      `queryParam:"inline" union:"member"`

	Type SubscriptionDiscountType
}

func CreateSubscriptionDiscountDiscountFixedOnceForeverDurationBase(discountFixedOnceForeverDurationBase DiscountFixedOnceForeverDurationBase) SubscriptionDiscount {
	typ := SubscriptionDiscountTypeDiscountFixedOnceForeverDurationBase

	return SubscriptionDiscount{
		DiscountFixedOnceForeverDurationBase: &discountFixedOnceForeverDurationBase,
		Type:                                 typ,
	}
}

func CreateSubscriptionDiscountDiscountFixedRepeatDurationBase(discountFixedRepeatDurationBase DiscountFixedRepeatDurationBase) SubscriptionDiscount {
	typ := SubscriptionDiscountTypeDiscountFixedRepeatDurationBase

	return SubscriptionDiscount{
		DiscountFixedRepeatDurationBase: &discountFixedRepeatDurationBase,
		Type:                            typ,
	}
}

func CreateSubscriptionDiscountDiscountPercentageOnceForeverDurationBase(discountPercentageOnceForeverDurationBase DiscountPercentageOnceForeverDurationBase) SubscriptionDiscount {
	typ := SubscriptionDiscountTypeDiscountPercentageOnceForeverDurationBase

	return SubscriptionDiscount{
		DiscountPercentageOnceForeverDurationBase: &discountPercentageOnceForeverDurationBase,
		Type: typ,
	}
}

func CreateSubscriptionDiscountDiscountPercentageRepeatDurationBase(discountPercentageRepeatDurationBase DiscountPercentageRepeatDurationBase) SubscriptionDiscount {
	typ := SubscriptionDiscountTypeDiscountPercentageRepeatDurationBase

	return SubscriptionDiscount{
		DiscountPercentageRepeatDurationBase: &discountPercentageRepeatDurationBase,
		Type:                                 typ,
	}
}

func (u *SubscriptionDiscount) UnmarshalJSON(data []byte) error {

	var discountFixedRepeatDurationBase DiscountFixedRepeatDurationBase = DiscountFixedRepeatDurationBase{}
	if err := utils.UnmarshalJSON(data, &discountFixedRepeatDurationBase, "", true, nil); err == nil {
		u.DiscountFixedRepeatDurationBase = &discountFixedRepeatDurationBase
		u.Type = SubscriptionDiscountTypeDiscountFixedRepeatDurationBase
		return nil
	}

	var discountFixedOnceForeverDurationBase DiscountFixedOnceForeverDurationBase = DiscountFixedOnceForeverDurationBase{}
	if err := utils.UnmarshalJSON(data, &discountFixedOnceForeverDurationBase, "", true, nil); err == nil {
		u.DiscountFixedOnceForeverDurationBase = &discountFixedOnceForeverDurationBase
		u.Type = SubscriptionDiscountTypeDiscountFixedOnceForeverDurationBase
		return nil
	}

	var discountPercentageRepeatDurationBase DiscountPercentageRepeatDurationBase = DiscountPercentageRepeatDurationBase{}
	if err := utils.UnmarshalJSON(data, &discountPercentageRepeatDurationBase, "", true, nil); err == nil {
		u.DiscountPercentageRepeatDurationBase = &discountPercentageRepeatDurationBase
		u.Type = SubscriptionDiscountTypeDiscountPercentageRepeatDurationBase
		return nil
	}

	var discountPercentageOnceForeverDurationBase DiscountPercentageOnceForeverDurationBase = DiscountPercentageOnceForeverDurationBase{}
	if err := utils.UnmarshalJSON(data, &discountPercentageOnceForeverDurationBase, "", true, nil); err == nil {
		u.DiscountPercentageOnceForeverDurationBase = &discountPercentageOnceForeverDurationBase
		u.Type = SubscriptionDiscountTypeDiscountPercentageOnceForeverDurationBase
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SubscriptionDiscount", string(data))
}

func (u SubscriptionDiscount) MarshalJSON() ([]byte, error) {
	if u.DiscountFixedOnceForeverDurationBase != nil {
		return utils.MarshalJSON(u.DiscountFixedOnceForeverDurationBase, "", true)
	}

	if u.DiscountFixedRepeatDurationBase != nil {
		return utils.MarshalJSON(u.DiscountFixedRepeatDurationBase, "", true)
	}

	if u.DiscountPercentageOnceForeverDurationBase != nil {
		return utils.MarshalJSON(u.DiscountPercentageOnceForeverDurationBase, "", true)
	}

	if u.DiscountPercentageRepeatDurationBase != nil {
		return utils.MarshalJSON(u.DiscountPercentageRepeatDurationBase, "", true)
	}

	return nil, errors.New("could not marshal union type SubscriptionDiscount: all fields are null")
}

type SubscriptionPricesType string

const (
	SubscriptionPricesTypeLegacyRecurringProductPrice SubscriptionPricesType = "LegacyRecurringProductPrice"
	SubscriptionPricesTypeProductPrice                SubscriptionPricesType = "ProductPrice"
)

type SubscriptionPrices struct {
	LegacyRecurringProductPrice *LegacyRecurringProductPrice `queryParam:"inline" union:"member"`
	ProductPrice                *ProductPrice                `queryParam:"inline" union:"member"`

	Type SubscriptionPricesType
}

func CreateSubscriptionPricesLegacyRecurringProductPrice(legacyRecurringProductPrice LegacyRecurringProductPrice) SubscriptionPrices {
	typ := SubscriptionPricesTypeLegacyRecurringProductPrice

	return SubscriptionPrices{
		LegacyRecurringProductPrice: &legacyRecurringProductPrice,
		Type:                        typ,
	}
}

func CreateSubscriptionPricesProductPrice(productPrice ProductPrice) SubscriptionPrices {
	typ := SubscriptionPricesTypeProductPrice

	return SubscriptionPrices{
		ProductPrice: &productPrice,
		Type:         typ,
	}
}

func (u *SubscriptionPrices) UnmarshalJSON(data []byte) error {

	var legacyRecurringProductPrice LegacyRecurringProductPrice = LegacyRecurringProductPrice{}
	if err := utils.UnmarshalJSON(data, &legacyRecurringProductPrice, "", true, nil); err == nil {
		u.LegacyRecurringProductPrice = &legacyRecurringProductPrice
		u.Type = SubscriptionPricesTypeLegacyRecurringProductPrice
		return nil
	}

	var productPrice ProductPrice = ProductPrice{}
	if err := utils.UnmarshalJSON(data, &productPrice, "", true, nil); err == nil {
		u.ProductPrice = &productPrice
		u.Type = SubscriptionPricesTypeProductPrice
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SubscriptionPrices", string(data))
}

func (u SubscriptionPrices) MarshalJSON() ([]byte, error) {
	if u.LegacyRecurringProductPrice != nil {
		return utils.MarshalJSON(u.LegacyRecurringProductPrice, "", true)
	}

	if u.ProductPrice != nil {
		return utils.MarshalJSON(u.ProductPrice, "", true)
	}

	return nil, errors.New("could not marshal union type SubscriptionPrices: all fields are null")
}

type Subscription struct {
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the object.
	ID string `json:"id"`
	// The amount of the subscription.
	Amount int64 `json:"amount"`
	// The currency of the subscription.
	Currency          string                        `json:"currency"`
	RecurringInterval SubscriptionRecurringInterval `json:"recurring_interval"`
	// Number of interval units of the subscription. If this is set to 1 the charge will happen every interval (e.g. every month), if set to 2 it will be every other month, and so on.
	RecurringIntervalCount int64              `json:"recurring_interval_count"`
	Status                 SubscriptionStatus `json:"status"`
	// The start timestamp of the current billing period.
	CurrentPeriodStart time.Time `json:"current_period_start"`
	// The end timestamp of the current billing period.
	CurrentPeriodEnd *time.Time `json:"current_period_end"`
	// The start timestamp of the trial period, if any.
	TrialStart *time.Time `json:"trial_start"`
	// The end timestamp of the trial period, if any.
	TrialEnd *time.Time `json:"trial_end"`
	// Whether the subscription will be canceled at the end of the current period.
	CancelAtPeriodEnd bool `json:"cancel_at_period_end"`
	// The timestamp when the subscription was canceled. The subscription might still be active if `cancel_at_period_end` is `true`.
	CanceledAt *time.Time `json:"canceled_at"`
	// The timestamp when the subscription started.
	StartedAt *time.Time `json:"started_at"`
	// The timestamp when the subscription will end.
	EndsAt *time.Time `json:"ends_at"`
	// The timestamp when the subscription ended.
	EndedAt *time.Time `json:"ended_at"`
	// The ID of the subscribed customer.
	CustomerID string `json:"customer_id"`
	// The ID of the subscribed product.
	ProductID string `json:"product_id"`
	// The ID of the applied discount, if any.
	DiscountID *string `json:"discount_id"`
	CheckoutID *string `json:"checkout_id"`
	// The number of seats for seat-based subscriptions. None for non-seat subscriptions.
	Seats                       *int64                        `json:"seats,omitempty"`
	CustomerCancellationReason  *CustomerCancellationReason   `json:"customer_cancellation_reason"`
	CustomerCancellationComment *string                       `json:"customer_cancellation_comment"`
	Metadata                    map[string]MetadataOutputType `json:"metadata"`
	// Key-value object storing custom field values.
	CustomFieldData map[string]*CustomFieldData `json:"custom_field_data,omitempty"`
	Customer        SubscriptionCustomer        `json:"customer"`
	// A product.
	Product  Product               `json:"product"`
	Discount *SubscriptionDiscount `json:"discount"`
	// List of enabled prices for the subscription.
	Prices []SubscriptionPrices `json:"prices"`
	// List of meters associated with the subscription.
	Meters []SubscriptionMeter `json:"meters"`
}

func (s Subscription) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Subscription) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Subscription) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *Subscription) GetModifiedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.ModifiedAt
}

func (s *Subscription) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Subscription) GetAmount() int64 {
	if s == nil {
		return 0
	}
	return s.Amount
}

func (s *Subscription) GetCurrency() string {
	if s == nil {
		return ""
	}
	return s.Currency
}

func (s *Subscription) GetRecurringInterval() SubscriptionRecurringInterval {
	if s == nil {
		return SubscriptionRecurringInterval("")
	}
	return s.RecurringInterval
}

func (s *Subscription) GetRecurringIntervalCount() int64 {
	if s == nil {
		return 0
	}
	return s.RecurringIntervalCount
}

func (s *Subscription) GetStatus() SubscriptionStatus {
	if s == nil {
		return SubscriptionStatus("")
	}
	return s.Status
}

func (s *Subscription) GetCurrentPeriodStart() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CurrentPeriodStart
}

func (s *Subscription) GetCurrentPeriodEnd() *time.Time {
	if s == nil {
		return nil
	}
	return s.CurrentPeriodEnd
}

func (s *Subscription) GetTrialStart() *time.Time {
	if s == nil {
		return nil
	}
	return s.TrialStart
}

func (s *Subscription) GetTrialEnd() *time.Time {
	if s == nil {
		return nil
	}
	return s.TrialEnd
}

func (s *Subscription) GetCancelAtPeriodEnd() bool {
	if s == nil {
		return false
	}
	return s.CancelAtPeriodEnd
}

func (s *Subscription) GetCanceledAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CanceledAt
}

func (s *Subscription) GetStartedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.StartedAt
}

func (s *Subscription) GetEndsAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.EndsAt
}

func (s *Subscription) GetEndedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.EndedAt
}

func (s *Subscription) GetCustomerID() string {
	if s == nil {
		return ""
	}
	return s.CustomerID
}

func (s *Subscription) GetProductID() string {
	if s == nil {
		return ""
	}
	return s.ProductID
}

func (s *Subscription) GetDiscountID() *string {
	if s == nil {
		return nil
	}
	return s.DiscountID
}

func (s *Subscription) GetCheckoutID() *string {
	if s == nil {
		return nil
	}
	return s.CheckoutID
}

func (s *Subscription) GetSeats() *int64 {
	if s == nil {
		return nil
	}
	return s.Seats
}

func (s *Subscription) GetCustomerCancellationReason() *CustomerCancellationReason {
	if s == nil {
		return nil
	}
	return s.CustomerCancellationReason
}

func (s *Subscription) GetCustomerCancellationComment() *string {
	if s == nil {
		return nil
	}
	return s.CustomerCancellationComment
}

func (s *Subscription) GetMetadata() map[string]MetadataOutputType {
	if s == nil {
		return map[string]MetadataOutputType{}
	}
	return s.Metadata
}

func (s *Subscription) GetCustomFieldData() map[string]*CustomFieldData {
	if s == nil {
		return nil
	}
	return s.CustomFieldData
}

func (s *Subscription) GetCustomer() SubscriptionCustomer {
	if s == nil {
		return SubscriptionCustomer{}
	}
	return s.Customer
}

func (s *Subscription) GetProduct() Product {
	if s == nil {
		return Product{}
	}
	return s.Product
}

func (s *Subscription) GetDiscount() *SubscriptionDiscount {
	if s == nil {
		return nil
	}
	return s.Discount
}

func (s *Subscription) GetPrices() []SubscriptionPrices {
	if s == nil {
		return []SubscriptionPrices{}
	}
	return s.Prices
}

func (s *Subscription) GetMeters() []SubscriptionMeter {
	if s == nil {
		return []SubscriptionMeter{}
	}
	return s.Meters
}
