// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
)

type SubscriptionRevokedMetadata struct {
	SubscriptionID string `json:"subscription_id"`
}

func (s SubscriptionRevokedMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionRevokedMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"subscription_id"}); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionRevokedMetadata) GetSubscriptionID() string {
	if s == nil {
		return ""
	}
	return s.SubscriptionID
}
