// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
)

// SupportCaseAttachmentFileCreate - Schema to create a file attached to a support case.
type SupportCaseAttachmentFileCreate struct {
	OrganizationID *string `json:"organization_id,omitempty"`
	Name           string  `json:"name"`
	// MIME type of the file. Images, videos, PDF, CSV, plain text, Word and Excel documents are supported.
	MimeType string `json:"mime_type"`
	// Size of the file. A maximum of 250 MB is allowed for this type of file.
	Size                 int64                 `json:"size"`
	ChecksumSha256Base64 *string               `json:"checksum_sha256_base64,omitempty"`
	Upload               S3FileCreateMultipart `json:"upload"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	service string  `const:"support_case_attachment" json:"service"`
	Version *string `json:"version,omitempty"`
}

func (s SupportCaseAttachmentFileCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SupportCaseAttachmentFileCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"name", "mime_type", "size", "upload", "service"}); err != nil {
		return err
	}
	return nil
}

func (s *SupportCaseAttachmentFileCreate) GetOrganizationID() *string {
	if s == nil {
		return nil
	}
	return s.OrganizationID
}

func (s *SupportCaseAttachmentFileCreate) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SupportCaseAttachmentFileCreate) GetMimeType() string {
	if s == nil {
		return ""
	}
	return s.MimeType
}

func (s *SupportCaseAttachmentFileCreate) GetSize() int64 {
	if s == nil {
		return 0
	}
	return s.Size
}

func (s *SupportCaseAttachmentFileCreate) GetChecksumSha256Base64() *string {
	if s == nil {
		return nil
	}
	return s.ChecksumSha256Base64
}

func (s *SupportCaseAttachmentFileCreate) GetUpload() S3FileCreateMultipart {
	if s == nil {
		return S3FileCreateMultipart{}
	}
	return s.Upload
}

func (s *SupportCaseAttachmentFileCreate) GetService() string {
	return "support_case_attachment"
}

func (s *SupportCaseAttachmentFileCreate) GetVersion() *string {
	if s == nil {
		return nil
	}
	return s.Version
}
