// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TaxBehaviorOption string

const (
	TaxBehaviorOptionLocation  TaxBehaviorOption = "location"
	TaxBehaviorOptionInclusive TaxBehaviorOption = "inclusive"
	TaxBehaviorOptionExclusive TaxBehaviorOption = "exclusive"
)

func (e TaxBehaviorOption) ToPointer() *TaxBehaviorOption {
	return &e
}
func (e *TaxBehaviorOption) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "location":
		fallthrough
	case "inclusive":
		fallthrough
	case "exclusive":
		*e = TaxBehaviorOption(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TaxBehaviorOption: %v", v)
	}
}
