// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

type UserEventMetadataType string

const (
	UserEventMetadataTypeStr     UserEventMetadataType = "str"
	UserEventMetadataTypeInteger UserEventMetadataType = "integer"
	UserEventMetadataTypeNumber  UserEventMetadataType = "number"
	UserEventMetadataTypeBoolean UserEventMetadataType = "boolean"
)

type UserEventMetadata struct {
	Str     *string  `queryParam:"inline"`
	Integer *int64   `queryParam:"inline"`
	Number  *float64 `queryParam:"inline"`
	Boolean *bool    `queryParam:"inline"`

	Type UserEventMetadataType
}

func CreateUserEventMetadataStr(str string) UserEventMetadata {
	typ := UserEventMetadataTypeStr

	return UserEventMetadata{
		Str:  &str,
		Type: typ,
	}
}

func CreateUserEventMetadataInteger(integer int64) UserEventMetadata {
	typ := UserEventMetadataTypeInteger

	return UserEventMetadata{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateUserEventMetadataNumber(number float64) UserEventMetadata {
	typ := UserEventMetadataTypeNumber

	return UserEventMetadata{
		Number: &number,
		Type:   typ,
	}
}

func CreateUserEventMetadataBoolean(boolean bool) UserEventMetadata {
	typ := UserEventMetadataTypeBoolean

	return UserEventMetadata{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *UserEventMetadata) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, false); err == nil {
		u.Str = &str
		u.Type = UserEventMetadataTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, false); err == nil {
		u.Integer = &integer
		u.Type = UserEventMetadataTypeInteger
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, false); err == nil {
		u.Number = &number
		u.Type = UserEventMetadataTypeNumber
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, false); err == nil {
		u.Boolean = &boolean
		u.Type = UserEventMetadataTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UserEventMetadata", string(data))
}

func (u UserEventMetadata) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type UserEventMetadata: all fields are null")
}

// UserEvent - An event you created through the ingestion API.
type UserEvent struct {
	Metadata map[string]UserEventMetadata `json:"metadata"`
	// The ID of the object.
	ID string `json:"id"`
	// The timestamp of the event.
	Timestamp time.Time `json:"timestamp"`
	// The ID of the organization owning the event.
	OrganizationID string `json:"organization_id"`
	// ID of the customer in your Polar organization associated with the event.
	CustomerID *string `json:"customer_id"`
	// The customer associated with the event.
	Customer *Customer `json:"customer"`
	// ID of the customer in your system associated with the event.
	ExternalCustomerID *string `json:"external_customer_id"`
	// The name of the event.
	Name string `json:"name"`
	// The source of the event. `system` events are created by Polar. `user` events are the one you create through our ingestion API.
	source string `const:"user" json:"source"`
}

func (u UserEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UserEvent) GetMetadata() map[string]UserEventMetadata {
	if o == nil {
		return map[string]UserEventMetadata{}
	}
	return o.Metadata
}

func (o *UserEvent) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UserEvent) GetTimestamp() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Timestamp
}

func (o *UserEvent) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *UserEvent) GetCustomerID() *string {
	if o == nil {
		return nil
	}
	return o.CustomerID
}

func (o *UserEvent) GetCustomer() *Customer {
	if o == nil {
		return nil
	}
	return o.Customer
}

func (o *UserEvent) GetExternalCustomerID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalCustomerID
}

func (o *UserEvent) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *UserEvent) GetSource() string {
	return "user"
}
