// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

// WebhookEvent - A webhook event.
//
// An event represent something that happened in the system
// that should be sent to the webhook endpoint.
//
// It can be delivered multiple times until it's marked as succeeded,
// each one creating a new delivery.
type WebhookEvent struct {
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the object.
	ID string `json:"id"`
	// Last HTTP code returned by the URL. `null` if no delviery has been attempted or if the endpoint was unreachable.
	LastHTTPCode *int64 `json:"last_http_code,omitempty"`
	// Whether this event was successfully delivered. `null` if no delivery has been attempted.
	Succeeded *bool `json:"succeeded,omitempty"`
	// The payload of the webhook event.
	Payload string `json:"payload"`
}

func (w WebhookEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *WebhookEvent) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *WebhookEvent) GetModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ModifiedAt
}

func (o *WebhookEvent) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *WebhookEvent) GetLastHTTPCode() *int64 {
	if o == nil {
		return nil
	}
	return o.LastHTTPCode
}

func (o *WebhookEvent) GetSucceeded() *bool {
	if o == nil {
		return nil
	}
	return o.Succeeded
}

func (o *WebhookEvent) GetPayload() string {
	if o == nil {
		return ""
	}
	return o.Payload
}
