// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

// WebhookDelivery - A webhook delivery for a webhook event.
type WebhookDelivery struct {
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt *time.Time `json:"modified_at"`
	// The ID of the object.
	ID string `json:"id"`
	// Whether the delivery was successful.
	Succeeded bool `json:"succeeded"`
	// The HTTP code returned by the URL. `null` if the endpoint was unreachable.
	HTTPCode *int64 `json:"http_code"`
	// The response body returned by the URL, or the error message if the endpoint was unreachable.
	Response *string `json:"response"`
	// A webhook event.
	//
	// An event represent something that happened in the system
	// that should be sent to the webhook endpoint.
	//
	// It can be delivered multiple times until it's marked as succeeded,
	// each one creating a new delivery.
	WebhookEvent WebhookEvent `json:"webhook_event"`
}

func (w WebhookDelivery) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookDelivery) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, []string{"created_at", "modified_at", "id", "succeeded", "http_code", "response", "webhook_event"}); err != nil {
		return err
	}
	return nil
}

func (w *WebhookDelivery) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *WebhookDelivery) GetModifiedAt() *time.Time {
	if w == nil {
		return nil
	}
	return w.ModifiedAt
}

func (w *WebhookDelivery) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *WebhookDelivery) GetSucceeded() bool {
	if w == nil {
		return false
	}
	return w.Succeeded
}

func (w *WebhookDelivery) GetHTTPCode() *int64 {
	if w == nil {
		return nil
	}
	return w.HTTPCode
}

func (w *WebhookDelivery) GetResponse() *string {
	if w == nil {
		return nil
	}
	return w.Response
}

func (w *WebhookDelivery) GetWebhookEvent() WebhookEvent {
	if w == nil {
		return WebhookEvent{}
	}
	return w.WebhookEvent
}
