// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
	"time"
)

// WebhookSubscriptionUncanceledPayload - Sent when a subscription is uncanceled.
//
// **Discord & Slack support:** Full
type WebhookSubscriptionUncanceledPayload struct {
	type_     string       `const:"subscription.uncanceled" json:"type"`
	Timestamp time.Time    `json:"timestamp"`
	Data      Subscription `json:"data"`
}

func (w WebhookSubscriptionUncanceledPayload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookSubscriptionUncanceledPayload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, []string{"type", "timestamp", "data"}); err != nil {
		return err
	}
	return nil
}

func (w *WebhookSubscriptionUncanceledPayload) GetType() string {
	return "subscription.uncanceled"
}

func (w *WebhookSubscriptionUncanceledPayload) GetTimestamp() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.Timestamp
}

func (w *WebhookSubscriptionUncanceledPayload) GetData() Subscription {
	if w == nil {
		return Subscription{}
	}
	return w.Data
}
