// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

import (
	"github.com/polarsource/polar-go/models/components"
)

type EndpointsubscriptionPastDuePostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	Any any
}

func (e *EndpointsubscriptionPastDuePostResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EndpointsubscriptionPastDuePostResponse) GetAny() any {
	if e == nil {
		return nil
	}
	return e.Any
}
