// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

import (
	"polar/models/components"
)

type EndpointbenefitCreatedPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	Any any
}

func (o *EndpointbenefitCreatedPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *EndpointbenefitCreatedPostResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}
